SwissDataScienceCenter/renku-ui

server/app/controllers/proxy.py, src/components/deploy/details/details.html, src/components/deploy/details/index.ts, src/components/deploy/execution/execution.html, src/components/deploy/execution/index.ts, src/components/deploy/index.ts, src/components/graph-item-list/index.ts, src/components/storage/files/files.html, src/components/storage/files/index.ts, src/main.ts
=> add execution details

.dockerignore, Makefile, npm-build.Dockerfile
=> docker-only makefile

Makefile
=> Added sources as dependencies in make

config/webpack.config.base.js, server/app/__init__.py
=> Properly set app root

server/app/keycloak.py, src/components/graph-item-list/index.ts
=> fix refresh and redirection when token expires

src/components/project/index.ts
=> When creating a new project, this project is automatically selected.

server/app/controllers/proxy.py, src/components/dialogs/bucket-dialog.html, src/components/dialogs/index.ts, src/components/dialogs/version-dialog.html, src/utils/renga-api.ts
Resolves #59 on the UI without involvement of the storage service:
- Add "file-from-url" option to file- and file version upload dialog.
- Add simple web-proxy to flask server app to avoid CORS problems.
=> file upload directly from url

src/components/deploy/context/index.ts, src/components/deploy/execution/index.ts, src/components/dialogs/bucket-dialog.html, src/components/dialogs/index.ts, src/components/dialogs/labels-dialog.html, src/components/dialogs/rename-dialog.html, src/components/graph-item-list/graph-item-table.html, src/components/graph-item-list/graph-item.ts, src/components/graph/graph.html, src/components/graph/index.ts, src/components/storage/buckets/index.ts, src/components/storage/files/files.html, src/components/storage/files/index.ts, src/utils/renga-api.ts
- Rename files from bucket detail view or graph view.
- Add labels on file creation.
- Add/change file labels from bucket detail view or graph view.
- Concatenate all labels to a comma-separated string which is displayed and searchable im the graph-item table view.
=> Resolves issues #57 and #66

src/components/deploy/context/index.ts, src/components/dialogs/index.ts
- Fix context detail URL
- Fix non-working cancel button by moving 'cancel" method back from the base class to the individual dialog classes.
=> Fix first two bullet points of #61

Makefile, package-lock.json, package.json, server/app/__init__.py, server/app/controllers/home.py, server/app/controllers/proxy.py, server/app/settings.py, server/app/templates/base.html, src/components/deploy/context/index.ts, src/components/deploy/execution/index.ts, src/components/dialogs/context-dialog.html, src/components/dialogs/execution-dialog.html, src/components/dialogs/index.ts, src/components/storage/files/files.html, src/components/tutorial/index.ts, src/components/tutorial/tutorial.html, src/components/user/index.ts, src/main.ts, src/utils/renga-api.ts
Let's use this pull request to review the changes (it's easier this way to see the actual diff)
=> Datajam changes into master

src/components/deploy/details/index.ts, src/utils/renga-api.ts
to be deployed after https://github.com/SwissDataScienceCenter/renga-deployer/pull/86
=> add options to reach notebooks behind k8s ingresses

.editorconfig, Makefile
tag images by default to work nicely with the global renga make
addresses https://github.com/SwissDataScienceCenter/renga/issues/121
=> makefile: make tags by default

Dockerfile, package.json
copy app to container and allow it to be run independently
addresses https://github.com/SwissDataScienceCenter/renga/pull/124
=> copy sources and static files to container

Dockerfile, docker-compose.yml, package-lock.json, package.json, public/index.html, src/App.js, src/gitlab/client.js, src/index.js, src/login/index.js
- Login with keycloak using the javascript adapter loaded from the keycloak server.
- Login with gitlab using the implicit flow (no client secret) to optain a bearer token for the gitlab API.
- Various configuration changes for the ui to run with the main renga Makefile.
=> resolves #105:

Dockerfile, Makefile, docker-entrypoint.sh, package-lock.json, package.json, public/index.html, src/index.js
- Allows a proper development setting through 'make dev'
- Still depends on gitlab and keycloak being run though make start in the main renga repo.
=> closes #120:

README.rst
addresses https://github.com/SwissDataScienceCenter/renga/issues/117
=> readme: add development note

Dockerfile, Makefile, package.json, src/index.js
- fix the dev mode of the ui ("make dev")
=> closes #133:

src/App.css, src/contribution/Contribution.container.js, src/contribution/Contribution.present.js, src/file/File.container.js, src/file/File.present.js, src/file/index.js, src/gitlab/client.js
- Enables connecting to a running notebook server from the notebook file viewer.
- Does currently assume to be on the master branch per default.
=> closes #114:

.babelrc, package-lock.json, package.json
with the correct presets under 'npm run node' to quickly test ui modules interactively.
=> Make babel-node available as npm run command

src/App.js, src/contribution/Contribution.container.js, src/contribution/Contribution.present.js, src/file/File.present.js, src/gitlab/client.js, src/ku/Ku.js, src/project/Project.js, src/project/Project.present.js, src/utils/UIComponents.js
Restructure the project page to show Kus under the project. Closes #141.
=> 141 project page

package-lock.json, package.json, src/model/Model.js, src/model/Model.test.js, src/model/RengaModels.js
...and an example for possible renga models.
=> Added Schema and Model base classes

src/file/File.present.js, src/file/Notebook.js, src/file/notebook.css, src/gitlab/client.js, src/project/Project.js, src/project/Project.present.js, src/project/Project.state.js, src/styles/_jupyter_notebook.scss, src/styles/index.scss, src/utils/EnhancedState.js
- Retrieve and show project tags from gitlab
- Retrieve and show stars from gitlab
- Added parameter to provide a name to a redux store, useful with the debugging tools
- Work on improving the styling of notebooks, but this is still WIP.
=> 132 minor ui improvments

src/model/Model-Gitlab.test.js, src/model/Model.example.js, src/model/Model.js, src/model/Model.test.js
Still to be brushed a little bit here and there, but basic ideas are there. Tests which involve API calls are still missing, the corresponding file is only a stub.
=> Improved react state and redux model bindings

src/App.js, src/gitlab/client.js, src/model/Model.js, src/model/RengaModels.js, src/project/Project.js, src/project/Project.present.js, src/project/Project.state.js, src/utils/HelperFunctions.js
Introduce very basic project creation through the ui:
- Use the new state schema / models
- Change some minor aspects of the model implementation / validation
=> 129 new project

src/model/Model.js
=> Throw error objects, not strings.

src/App.js, src/gitlab/client.js, src/ku/Ku.js, src/model/Model.js, src/project/Project.js, src/project/Project.present.js, src/project/Project.state.js
- Fixes minor cosmetic issues
- Added settings page with: 
- remote URLs
- editing of tags
=> 132 minor ui

src/gitlab/client.js, src/project/Project.state.js
=> Bugfix in project server return handling

.dockerignore, Dockerfile, Makefile, README.rst, docker-entrypoint.sh, nginx.vh.default.conf, package.json, public/config.json, src/App.js, src/index.js, src/login/index.js
* Removes dependency on KeyCloak.
* Uses nginx for serving build application.
=> Read params from config.json

src/file/File.container.js
Fix recently introduced bug which causes ui to crash when trying to render code.
=> Fix recently introduced bug 

docker-entrypoint.sh
=> Make GitLab client-id configurable

package-lock.json
Recreated package-lock.json to fix travis build build problem in appearing in various recent PRs.
=> Recreated package-lock.json

Dockerfile
Fix node version to 8.11.1 (LTS).
=> Use node 8.11.1

.travis.yml
Use `development` build on `master` now
=> Update travis job after master<-development

.travis.yml, Makefile, helm-chart/chartpress.yaml
~~Adds `Dockerfile` to the chart dependency~~
We decided the easiest for now is to build the chart and images on every push (i.e. any change in the repo triggers an image/chart build).
=> Chart dependency

src/contribution/Contribution.container.js, src/file/File.container.js, src/ku/Ku.js
Handle empty jupyterhub URLs and fix React warnings about setState on unmounted components.
=> Minor ui improvements

src/gitlab/client.js, src/project/Project.js, src/project/Project.present.js
=> Fix url behind "launch notebook server" button

src/file/File.container.js, src/project/Project.state.js
=> Several bugfixes

src/App.js, src/App.test.js, src/app-state/AppState.user.js, src/gitlab/client.js, src/gitlab/test-client.js, src/index.js, src/ku/Ku.js, src/ku/Ku.state.js, src/ku/Ku.test.js, src/landing/Landing.js, src/landing/Landing.present.js, src/landing/Landing.state.js, src/landing/Landing.test.js, src/model/Model-Gitlab.test.js, src/model/RenkuModels.js, src/project/Project.js, src/project/Project.present.js, src/project/Project.state.js, src/project/Project.test.js, src/utils/EnhancedState.js, src/utils/Errors.js
=> Improve landing page

src/gitlab/initRenkuProject.js
Updates the files that populate the repo on project init. Tested with https://github.com/SwissDataScienceCenter/renku/pull/260 and aligned with https://github.com/SwissDataScienceCenter/renku-python/pull/208.
**Do not merge before the above two PRs are merged**
=> init: update file templates

src/App.js, src/notebooks/Notebooks.container.js, src/notebooks/Notebooks.test.js, src/notebooks/index.js
This is minimal solution to #151, but we need to do a better solution when there is more time.
=> Implemented a minimal solution to for notebook admin page.

src/gitlab/client.js, src/model/RenkuModels.js, src/project/Project.js, src/project/Project.present.js, src/project/Project.state.js
Add a notification if notebook image build has failed or is still on-going.
addresses https://github.com/SwissDataScienceCenter/renku/issues/263
=> Notebook image build status notification

src/file/Notebook.js, src/gitlab/client.js, src/merge-request/MergeRequest.container.js, src/merge-request/MergeRequest.present.js, src/project/Project.js, src/project/Project.present.js
Change the name of Merge Request to something else. Fix #257.
=> Change name of Merge Request

src/file/Lineage.container.js, src/file/Lineage.present.js, src/gitlab/client.js, src/project/Project.js, src/project/Project.present.js
Restructure file tabs following suggestion in issue. Fix #220.
=> File Tab Refactoring

src/file/File.container.js, src/file/File.present.js, src/gitlab/client.js
Merge at the same time/after https://github.com/SwissDataScienceCenter/renku-notebooks/pull/25
addresses https://github.com/SwissDataScienceCenter/renku-notebooks/issues/24
=> Post request for nb server

.gitignore, package-lock.json, package.json, src/App.css, src/file/Lineage.present.js, src/file/Notebook.js, src/gitlab/client.js, src/gitlab/renkuFetch.js, src/index.js, src/ku/Ku.js, src/ku/Ku.test.js, src/project/Project.js, src/project/Project.present.js
A collection of fixes for minor UI issues.
- Ignore machine-specific config files
- Remove extra '/' in API urls
- Add "New Ku" button to kus page
- Show useful information in pending changes view if a notebook did not exist in a previous commit
- Make clear that the file listing shows linage, except the notebook subtab
- Added links to GitLab from lineage view
- Added link to GitLab to Ku view
=> Minor UI Issue Fixes

src/project/Project.js, src/project/Project.present.js
Fix the bug that causes notebooks in the lineage view to be shown as "Notebook could not be found."
=> Distinguish between file listing, file lineage, and file content urls.

docker-entrypoint.sh, helm-chart/renku-ui/templates/deployment.yaml, helm-chart/renku-ui/values.yaml, run-telepresence.sh, src/App.js, src/App.test.js, src/landing/Landing.js, src/landing/Landing.present.js, src/landing/Landing.test.js
=> Make renku info part of landing page a templateable markdown file.

public/config.json
Remove the config.json file from the repo (which has already been added to .gitignore)
=> Remove config.json

src/App.js, src/gitlab/client.js, src/gitlab/renkuFetch.js, src/index.js, src/project/Project.js
- expired access_token -> refresh token and redo request
- expired refresh_token -> send browser to login route (keycloak eventually)
- don't send cookies in regular fetch requests
- determine logged-in status based on cookie presence
Merge after https://github.com/SwissDataScienceCenter/renku-gateway/pull/46
Closes #295
=> Improve token handling

src/App.js, src/landing/Landing.js, src/landing/Landing.present.js, src/landing/Landing.state.js
Make sure the content of the templateable welcome page is accessible to all users, also the users who are logged in and have already starred a project.
=> Always show welcome page

src/App.js, src/landing/Landing.js
Pass user object to "starred" component as it is still needed to access the users starred projects.
=> Fix starred pill

docker-entrypoint.sh, helm-chart/renku-ui/templates/deployment.yaml, run-telepresence.sh, src/gitlab/client.js, src/gitlab/initRenkuProject.js, src/gitlab/renkuFetch.js, src/index.js
Update project creation such that:
- New files added to the project template are autmatically added.
- The correct version of the project template is used. The version is read from the the global chart values or from the version of the renku-ui Chart.
Builds on top of the changes in #309.
=> Update project creation

src/project/Project.present.js, src/project/Project.test.js
=> Filter out hidden paths.

package-lock.json, package.json, src/App.js, src/api-client/index.js, src/api-client/pagination.js, src/api-client/project.js, src/api-client/repository.js, src/api-client/test-client.js, src/api-client/utils.js, src/app-state/AppState.user.js, src/ku/Ku.js, src/merge-request/MergeRequest.container.js, src/project/Project.js, src/project/Project.present.js, src/project/Project.state.js, src/project/Project.test.js, src/utils/UIComponents.js
Implement pagination for project overview.
--
Do merge after https://github.com/SwissDataScienceCenter/renku-gateway/pull/54
=> Pagination

package-lock.json, package.json
- Recreated package-lock.json with npm 8.12.0
- Bumpbed react-scripts to 1.1.5 because of several dependencies with vulnerabilities
- Remvoed unused keycloak-js dependency
=> Clean up dependencies (resolves #332):

src/App.js, src/file/File.container.js, src/file/File.present.js, src/file/Lineage.container.js, src/login/index.js, src/notebooks/Notebooks.container.js, src/notebooks/Notebooks.present.js, src/notebooks/index.js, src/project/Project.js, src/project/Project.present.js
Please note that the majority of the code changes proposed in this PR will be revisited once the connection between the ui and jupyterhub us routed through the gateway.
=> Set server options

package-lock.json, src/App.js, src/api-client/errors.js, src/api-client/index.js, src/api-client/instance.js, src/api-client/project.js, src/api-client/test-client.js, src/api-client/test-samples/index.js, src/api-client/test-samples/namespaces.js, src/model/RenkuModels.js, src/model/RenkuModels.test.js, src/project/Project.js, src/project/Project.present.js, src/project/Project.style.css, src/project/Project.test.js, src/utils/UIComponents.js
=> Select namespace by project creation

src/project/Project.present.js
=> Show all suggestions when the namespace search gets focus

src/contribution/Contribution.present.js, src/ku/Ku.js
=> Added support for markdown content in Ku descriptions and contributions.

src/contribution/Contribution.present.js, src/file/Lineage.container.js, src/file/Lineage.present.js, src/ku/Ku.js
Do not crash if the linage cannot be loaded. Show an error message instead.
=> UI bug: Crash on lineage

src/file/Lineage.present.js, src/ku/Ku.js, src/merge-request/MergeRequest.present.js, src/notebooks/Notebooks.container.js, src/project/Project.present.js, src/utils/UIComponents.js
Did the ExternalLink part of #261. Fixed a warning (only needed to be done in one place after refactoring).
=> Refactored out a component for external links.

src/file/Lineage.container.js, src/file/Lineage.present.js
UI changes to support https://github.com/SwissDataScienceCenter/renku-python/pull/340 / https://github.com/SwissDataScienceCenter/renku-python/issues/339.
Should be merged after the above.
=> Changes to graph visualization to support new dot file.

.travis.yml, package-lock.json, package.json, src/App.js, src/api-client/errors.js, src/api-client/index.js, src/api-client/instance.js, src/api-client/ku.js, src/api-client/project.js, src/api-client/repository.js, src/api-client/user.js, src/api-client/utils.js, src/app-state/AppState.user.js, src/file/File.container.js, src/file/File.present.js, src/file/Lineage.container.js, src/index.js, src/login/index.js, src/notebooks/Notebooks.container.js, src/project/Project.js, src/project/Project.state.js
Closes #307.
Merge together with ~~https://github.com/SwissDataScienceCenter/renku-gateway/pull/58~~ https://github.com/SwissDataScienceCenter/renku-gateway/pull/63!
=> Refactor token/cookie handling

.travis.yml, travis-deploy.sh
tagged build: https://travis-ci.org/SwissDataScienceCenter/renku-ui/builds/460158643
=> ci: deploy on tag push

package-lock.json, package.json, src/setupTests.js
Upgrading to the latest react-scripts fixes some complaints in npm audit.
=> Upgraded to current react-scripts version.

src/App.js, src/landing/Landing.js, src/landing/Landing.present.js, src/project/list/ProjectList.container.js, src/project/list/ProjectList.present.js, src/project/list/ProjectList.state.js, src/project/list/ProjectList.test.js, src/utils/quicknav/QuickNav.container.js
=> Tabs added to projects page (your projects, starred projects, search)

.gitignore, run-telepresence.sh
* Added VS Code project folder to .gitignore
* Display namespace in run-telepresence.sh
=> Minor improvements

CHANGELOG.md, helm-chart/renku-ui/Chart.yaml
* Updated CHANGELOG.md
Q: Currently the changelog and milestone reference version 0.4.0. If we decide to name it 0.3.1, we need to rename the milestone and update the changelog.
=> Release 0.4.0

src/api-client/index.js, src/api-client/notebook-servers.js, src/notebooks/Notebooks.container.js, src/notebooks/Notebooks.present.js, src/notebooks/index.js, src/project/Project.js, src/project/Project.present.js, src/project/Project.state.js, src/utils/UIComponents.js
First steps of #351
Not sure if I should move the `fetchNotebookServers` logic inside the `NotebookServers` component. I also have some doubts about a few choices I have made, I'll add some comment in the code
=> Added Notebooks Server tab in Projects page

helm-chart/renku-ui/Chart.yaml
Update the version number after tagging 0.4.0.
=> Update Chart.yaml for post 0.4.0.

Dockerfile, helm-chart/renku-ui/templates/deployment.yaml, helm-chart/renku-ui/templates/service.yaml, helm-chart/renku-ui/values.yaml, nginx.vh.default.conf
=> Switch to nginx-unprivileged base image to not run as root.

src/file/File.container.js, src/file/index.js, src/landing/NavBar.js, src/notebooks/Notebooks.container.js, src/notebooks/Notebooks.present.js, src/project/Project.js, src/project/Project.present.js, src/project/Project.state.js
This addresses the first 2 points of #340
=> Moving Jupyter interactions to Notebook Servers

package-lock.json, package.json, src/api-client/graph.js, src/api-client/repository.js, src/file/Lineage.container.js, src/file/Lineage.present.js, src/project/Project.js
- Remove dot-file parsing from lineage component
- Query graph api instead of artefact api
- Adapt to new graph serialization
Addresses #362 
Merge after #374
=> Use graph services for lineage display

src/app-state/UserState.js, src/app-state/UserState.test.js, src/file/File.present.js, src/ku/Ku.js, src/ku/Ku.test.js, src/landing/Landing.js, src/landing/Landing.present.js, src/landing/Landing.test.js, src/landing/NavBar.js, src/model/RenkuModels.js, src/project/Project.js, src/project/Project.present.js, src/project/Project.state.js, src/project/Project.test.js, src/project/list/ProjectList.present.js, src/project/list/ProjectList.test.js
This addresses the first part of #406 and closes #389 
The re-factor involves the following:
* `UserState` is initialized with the attribute `available` to verify if the user login has finished or not. This required a few changes in pages where user existence is checked and in unit tests -- these have also expanded to test for both logged in and anonymous user where meaningful.
* `Project` page first verifies if the user login is still ongoing, and it waits until this step is completed before fetching project data. This helps to avoid re-loading component multiple times in short timespan.
* A "404" page is displayed when the project is not available. **Info:** please feel free to suggest any update on both text and layout -- see more below.
* Webhooks variables stored in redux are moved …
=> Re-factoring of Project and UserModel

package-lock.json, package.json, src/file/File.present.js
When a file is not found or could not be loaded there is an error message:
Also deleted some console.log that where left from a previous commit.
=> Added message of not found or not loaded when there is an error when fetching a file

package-lock.json, package.json, src/file/File.present.js
It looks like an update on the version of the notebook previewer fixes this issue.
The other version was deprecated: https://github.com/nteract/notebook-preview 
Now using: https://github.com/nteract/notebook-render
=> Update of the notebook viewer version

src/project/Project.js
Requirement to validate/create webhook downgraded to access level `Maintainer` instead of being the project's owner.
Can be tested from here: https://lorenzotest.dev.renku.ch/projects/93/ -- I added you as maintainers to that project
=> fix webhook permission requirement

src/project/list/ProjectList.container.js
Fix the weird bug #441 by updating the `View` component in the `ProjectList.container.js` file in this way
* listener moved from `constructor` to `componentDidMount`
* listener removed in `componentWillUnmount`
* filter through regular expression added to onUrlParametersChange
I suspect there may be a better way to solve this problem by changing `onPaginationPageChange` in a way that force `this.props.history.push` to work even when the `search` part of the url is updated. I spent some time trying that without success.
closes #441
=> projectlist listener adjusted

src/api-client/project.js, src/file/File.present.js, src/file/Lineage.container.js, src/file/Lineage.present.js, src/project/Project.js, src/project/Project.present.js, src/project/Project.state.js, src/project/filestreeview/FilesTreeView.js, src/project/filestreeview/treeviewstyle.css
=> Icons and functionality improvements

src/landing/Landing.js, src/landing/Landing.present.js, src/project/list/ProjectList.present.js
* Center content of anonymous landing page 
* Use two-column layout for logged-in landing page
Fix #383, Fix #398
=> Improvements to landing page

src/api-client/project.js, src/project/Project.js, src/project/Project.state.js, src/project/filestreeview/FilesTreeView.js
I implemented lazy loading for the file tree. 
1) The level 0 will be downladed
2) With each click on a folder the following level of the sub-tree will ve loaded in the folder
==> in case a link is sent with a file open all the subtrees to reach the selected files will be loaded too.
=> Files tree view with lazy loading

src/notebooks/Notebooks.present.js
=> style: correct capitalization of JupyterLab

package-lock.json, package.json, src/api-client/project.js, src/project/new/ProjectNew.container.js, src/project/new/ProjectNew.present.js
New dropdown that gives the user the option of choosing a template when creating a new project.
=> Feat: templates dropdown on project creation

CHANGELOG.md
Edit the changelog to reflect the changes introduced in 0.5.1.
=> chore(release): update changelog and chart version

CHANGELOG.md, helm-chart/renku-ui/Chart.yaml
Update CHANGELOG and version in Chart.yaml
=> Release 0.5.2

src/api-client/project.js, src/project/new/ProjectNew.present.js
A new option was added to the templates dropdown to create an empty project. 
Closes #504
=> feat: added option to create empty project

src/notebooks/Notebooks.state.js
Alternative implementation to fix #513 -- the other solution is #520
When the user stops a notebook, no updates of the notebooks will be considered until the `DELETE notebook` API returns a response.
There are a few marginal corner cases not covered by this simple solution. The most annoying happens when the user stops multiple notebooks and the notebooks list will be updated as soon as the first response comes, potentially turning back to `running` for a few seconds the status of the other stopping notebooks.
=> feat(notebook): improve user feedback when stopping a notebook - alternative

src/file/Lineage.css, src/file/Lineage.present.js
The url is correct now, and minor css improvements (workflow nodes with text in the center and buttons with new styling).
Fixes #546
=> fix(lineage): URL fixed and minor css improvements

src/file/Lineage.css
Style data and code in a way that is more visibly apparent.
=> feat(lineage): style data different from code

helm-chart/renku-ui/Chart.yaml, package.json
Update version to 0.6.4 after 0.6.3 release.
=> chore(release): update version to 0.6.4

CHANGELOG.md
=> chore(release): version 0.6.4

src/api-client/errors.js, src/api-client/graph.js, src/api-client/project.js, src/file/File.present.js
For certain files, there seems to be problems with the request for a notebook server and the request for lineage that causes the UI to either hang when displaying lineage or crash entirely. 
Compare 
https://dev.renku.ch/projects/cramakri/renku-tutorial-flights/files/lineage/notebooks/00-FilterFlights.ipynb
With 
https://sekhar.dev.renku.ch/projects/cramakri/renku-tutorial-flights/files/lineage/notebooks/00-FilterFlights.ipynb
=> fix(lineage): fixed ui crash and hanging load for lineage display

src/notebooks/Notebooks.present.js
Improve text in environment pages as suggested here https://github.com/SwissDataScienceCenter/renku-ui/pull/614#discussion_r325080987
=> refactor(environments): improve text

src/landing/NavBar.js
This PR uses the url provided by the gateway to open the user profile page
=> refactor: contact gateway to get user profile page

src/App.css, src/project/Project.present.js
=> fix: layout of fork and star buttons with larger font sizes

src/api-client/project.js, src/dataset/Dataset.container.js, src/dataset/Dataset.present.js, src/dataset/index.js, src/file/KnowledgeGraphStatus.container.js, src/file/KnowledgeGraphStatus.present.js, src/file/Lineage.present.js, src/file/index.js, src/project/Project.css, src/project/Project.js, src/project/Project.present.js, src/project/Project.state.js, src/project/datasets/DatasetsListView.js, src/utils/Time.js
This feature PR, it groups smaller PRs inside a feature branch
PRs included:
https://github.com/SwissDataScienceCenter/renku-ui/pull/562
https://github.com/SwissDataScienceCenter/renku-ui/pull/555
Closes:
#525
#602
=> feat(datasets): datasets inside projects

package-lock.json, package.json, src/file/File.present.js, src/project/Project.present.js, src/utils/UIComponents.js
Close #653.
Preview available at `https://sekhar.dev.renku.ch/`
Added copy to clipboard button to:
**File View**
**Settings View**
=> Add a copy button for project repository urls

CHANGELOG.md, helm-chart/renku-ui/Chart.yaml, package.json
- set package.json version to 0.7.0
- set chart version to 0.7.0
- create 0.7.0 CHANGELOG
=> chore: prepare 0.7.0 release

helm-chart/renku-ui/values.yaml
Updated template tag to use the latest.
Addresses: https://github.com/SwissDataScienceCenter/renku/issues/693
Depends on: https://github.com/SwissDataScienceCenter/renku-project-template/pull/46
=> chore: update template tag for release

CHANGELOG.md
Updates to Changelog for the 0.7.1 release.
=> chore: prepare 0.7.1 release

helm-chart/renku-ui/Chart.yaml, package.json
Bump version numbers after the 0.7.1 release.
=> Post 0.7.1

src/App.js, src/api-client/dataset.js, src/api-client/index.js, src/dataset/Dataset.present.js, src/dataset/list/DatasetList.container.js, src/dataset/list/DatasetList.present.js, src/dataset/list/DatasetList.state.js, src/dataset/list/index.js, src/landing/NavBar.js, src/project/Project.present.js
Closes #521-datasets-search
Allow the users to search for datasets in the KG.
Testing virginiatest.dev.renku.ch  --> i will deploy again when collaboration tab is merged.
=> feat(dataset): datasets general search

helm-chart/renku-ui/values.yaml, src/api-client/project.js
Wait for SwissDataScienceCenter/renku-project-template#48 to be merged and released first
=> refactor(templates): fix the variable names in templates

src/dataset/Dataset.present.js, src/dataset/list/DatasetList.present.js, src/landing/NavBar.js
Somehow these commits got lost original PR before the merge. This reintroduces these small improvements.
=> dataset search improvements that were lost

src/issue/Issue.js, src/notebooks/Notebooks.present.js, src/utils/UIComponents.js
Fix #680
Can test on https://sekhar.dev.renku.ch/
=> fix: throttle opening of icon links to workaround bug in Chrome

src/dataset/Dataset.present.js
=> feat(dataset): project path is displayed instead of project name in datasets

src/project/Project.present.js
=> fix(collaboration): collaboration doesn't loose active state

CHANGELOG.md
Updates to changelog for the 0.7.2 release.
=> chore: prepare 0.7.2 release

helm-chart/renku-ui/Chart.yaml, package.json
Bump version numbers after the 0.7.2 release.
=> chore: post 0.7.2 version bump

package-lock.json, package.json
Even though npm may ask you do install it, do not include fibers for the moment! It causes problems for notebook rendering
"fibers": "^4.0.2"
=> fix: update a more minimal set of deps

src/App.js, src/api-client/notebook-servers.js, src/api-client/project.js, src/api-client/test-client.js, src/file/File.container.js, src/file/KnowledgeGraphStatus.container.js, src/file/KnowledgeGraphStatus.present.js, src/notebooks/Notebooks.container.js, src/notebooks/Notebooks.state.js, src/project/Project-Route.test.js, src/project/Project.js, src/project/Project.present.js, src/project/Project.state.js
Solve the display side of https://github.com/SwissDataScienceCenter/renku/issues/716
Full support will be in another issue.
Deployed on https://sekhar.dev.renku.ch/ for testing.
=> fix: correctly handle nested groups in the URLs

helm-chart/renku-ui/Chart.yaml, package.json
Bump version number post 0.7.3.
=> Post 0.7.3

src/file/File.container.js
Closes #739 
testing: https://virginia.dev.renku.ch/projects/virginiafriedrich/empty-project/files/blob/rmdtestfile.Rmd
=> feat(fileviewer): with support for rmd display

src/api-client/dataset.js, src/dataset/Dataset.present.js, src/model/Model.js, src/model/RenkuModels.js, src/project/Project-Route.test.js, src/project/Project.js, src/project/Project.present.js, src/project/datasets/edit/DatasetEdit.container.js, src/project/datasets/edit/DatasetEdit.present.js, src/project/datasets/edit/index.js, src/project/datasets/new/DatasetNew.present.js, src/utils/formgenerator/FormGenerator.test.js, src/utils/formgenerator/FormPanel.js, src/utils/formgenerator/fields/FileUploaderInput.js
This is almost ready, i just need to do final testing....
=> feat(dataset): user can add files to an existing dataset

src/api-client/project.js, src/project/list/ProjectList.container.js, src/project/list/ProjectList.present.js, src/project/list/ProjectList.state.js, src/utils/UIComponents.js
Closes #733 
Added a Project Avatar that checks if the project has an avatar and if does it displays the project avatar, in case the project doesn't have an avatar it will try to display the user/group avatar.
Testing... https://datasetstest.dev.renku.ch/ (sorry for the unrelated name :o )
=> feat(projects): deeper search for project avatars

src/file/Lineage.present.js, src/project/Project.js
Navigation fixed. 
Closes #737
=> fix(lineage): navigation fixed

src/issue/Issue.js, src/project/Project.present.js
#741 moved user's data from `this.props.user.<attribute>` to `this.props.user.data.<attribute>` and adds the `this.props.user.logged` property to check if user is logged in or not.
This PR removes some old code testing for `this.props.user.id`
TEST: https://lorenzotest.dev.renku.ch
=> fix(state): remove checks on user id

.github/ISSUE_TEMPLATE/feature_request.md
Some other repos have a template to help people submitting feature requests outline the idea. This creates the feature request template.
=> feat: create feature request template for ui repo

src/notebooks/Notebooks.present.js, src/project/Project.present.js, src/utils/UIComponents.js
I added a link to the gitlab IDE, this is visible to users with developer rights or greater. 
(We could make this link available to all users but i'm not sure if that's what we want)
Docker image for testing: virfried/ui-ide1:latest
I see that i accidentally pushed an extra commit here (for the avatars pr). We can just wait until that PR is merged and then i can rebase against master and squash the commits so that disappears. 
Closes #699
=> feat(projects): link to gitlab IDE

.travis.yml, .travis/travis-deploy.sh, .travis/travis-functions.sh
Resolves #747
Note that the travis CLI did some auto-modifications to .travis-ci.yaml.
=> build: automatically update renku-ui dependency in renku

src/api-client/project.js, src/project/list/ProjectList.present.js
Fixes #726 
Search now returns all groups/projects.
=> fix(projects): search by groups returns correct result

src/contribution/Contribution.present.js, src/issue/Issue.js, src/project/Project.css, src/project/Project.js, src/project/Project.present.js
Closes #690 
Testing: https://virginiatest.dev.renku.ch
The ui looks like this with the change...
=> feat(collaboration): improvements to reach UI consistency inside issues

src/contribution/Contribution.container.js, src/contribution/Contribution.present.js, src/landing/Landing.present.js, src/merge-request/MergeRequest.present.js, src/project/shared/Projects.state.js, src/utils/UIComponents.js
Closes #767 
Fixes:
- When loading, they flash a couple of times (reproduce: go on the Landing page)
- The size of the anonymous icon is smaller than the others (42x48 instead of 52x52) making the flashing more evident and misaligning the text (reproduce: look at project pages with at least an anonymous icon)
- When adding a comment to an issue, the user appears to be anonymous (reproduce: add a comment to any existing issue)
=> fix(avatars): small fixes for avatars

src/landing/Landing.present.js, src/landing/NavBar.js, src/project/new/ProjectNew.present.js, src/utils/UIComponents.js
Just added ids to elements that the automated tests will click, so they are easier to find.
=> refactor: add ids for elements that tests will click

.eslintrc.json, package-lock.json, package.json
Add linting warnings for important ract hook errors
Merge after #783
=> test: add basic linting on react hooks

src/App.css, src/App.js, src/utils/UIComponents.js
Fix #785 
Can test on https://sekhar.dev.renku.ch/
=> Merge loader spinner and bouncer

src/api-client/dataset.js, src/utils/formgenerator/fields/FileUploaderInput.js
Closes #738 
When a user is adding a file to a dataset, she can press on the delete button and the file upload will be stopped and the file will be deleted.
To test you can see the cancelled fetch on the Network tab of the dev tools.
=> feat(dataset): when file is uploading user can delete an stop upload

src/model/RenkuModels.js, src/project/datasets/import/DatasetImport.container.js
Closes #820 
Wording changed on dataset import:
The form looks like this...
The messages are:
- Dataset import will start soon.
- Importing dataset.
- Dataset was imported, you will be redirected soon.
=> fix(dataset): wording improved on dataset import

src/notebooks/Notebooks.present.js, src/notebooks/Notebooks.state.js, src/notebooks/Notebooks.test.js
Branch and commit in the environments table rows are now links pointing to the repository
counterparts.
I can't build a docker image right now due to a strange network error :man_shrugging: 
Testing this requires the latest version of `renku-notebooks-0.7.0-67b955b`
fix #493
=> feat(environments): add link to repository branch and commit

src/utils/HelperFunctions.js, src/utils/Utils.test.js
Improve support for markdown files preview.
Here is an example: https://lorenzotest.dev.renku.ch/projects/lorenzo.cavazzi.tech/new-markdown
Compare with https://dev.renku.ch/projects/lorenzo.cavazzi.tech/new-markdown
=> feat: add options to properly convert markdown files

src/dataset/Dataset.present.js
Closes #824 
(More info on the issue)
=> fix(dataset): doi and source are display only when needed

src/landing/NavBar.css, src/landing/NavBar.js
Closes #858 
Fixed the dataset and new issue links.
The background changes on hoover.
=> fix(menu): links are working now

src/notebooks/Notebooks.present.js, src/utils/Time.js, src/utils/Utils.test.js
I can't provide a docker image for testing right now (`dockerd` not working on my machine :roll_eyes: ) 
fix #842
=> feat(environments): show start datetime

src/dataset/Dataset.present.js, src/utils/FileExplorer.js
Closes #859 
(Changes of this pr are described in the issue)
=> fix(datasets): datasets folders are displayed correctly and open

src/landing/NavBar.css, src/landing/NavBar.js
Closes #868 
Description on the issue.
I made all links "Link" instead of RenkuNavLink.
I also deleted some unused css in NavBar.css because is not needed now.
Test: https://virginiatest.dev.renku.ch
=> fix(topmenu): The menues look the same now

helm-chart/renku-ui/values.yaml
~preview: https://lorenzo.dev.renku.ch/~
=> chore: bump template version

src/model/RenkuModels.js
Closes #875 
Label changed from this: "Dataverse or Zenodo dataset URL or DOI:"
To:
=> feat(datasets): label changed

src/help/Help.present.js, src/landing/NavBar.js, src/utils/UIComponents.js
* Rename 'Discourse' to 'Forum'
* Add link to Forum in FooterNavbar
* Add Help Menu
Work towards #607 
Test deployment on https://sekhar.dev.renku.ch/
=> Help improvements

src/help/Help.present.js, src/landing/NavBar.js, src/utils/UIComponents.js
Add links to the following GitLab URLs:
- User Profile
- User Settings
- GitLab Home
Can be tested at https://sekhar.dev.renku.ch/
Fix #867
=> Add links to GitLab

src/api-client/project.js, src/dataset/Dataset.present.js, src/file/KnowledgeGraphStatus.container.js, src/project/Project.js, src/project/Project.present.js, src/project/datasets/DatasetsListView.js, src/project/datasets/edit/DatasetEdit.present.js, src/project/datasets/import/DatasetImport.container.js, src/project/datasets/import/DatasetImport.present.js, src/project/datasets/new/DatasetNew.container.js, src/project/datasets/new/DatasetNew.present.js
Closes #862 
Testing: https://virginiatest.dev.renku.ch
Dataset creation and import are now unified:
=> feat(datasets): dataset creation and import unified

helm-chart/renku-ui/values.yaml
Sample project on 0.1.11: https://lorenzotest.dev.renku.ch/projects/lorenzo.cavazzi.tech/0-1-11-new-test
=> chore: bump templates version to 0.1.11

src/project/Project.present.js
Closes #954 
The space after the dataset create/import was too small, i added some padding to make it look better.
=> fix(dataset): the space after the dataset create/import buttons is now bigger

src/collaboration/issue/Issue.js, src/collaboration/lists/CollaborationList.container.js, src/collaboration/lists/MergeRequestList.present.js, src/collaboration/merge-request/MergeRequest.container.js, src/collaboration/merge-request/MergeRequest.present.js, src/project/Project.present.js, src/utils/UIComponents.js
Closes #891.
Partial work on #854.
I wonder if we should change the buttons for going to gitlab and closing the issue, they could be a bit bigger and have text so users know a bit better what the button does, i don't thing they are so self - explanatory.
=> refactor(collaboration): issues and merge requests have now small visual improvements

src/notebooks/Notebooks.present.js
=> Fix display of server options for projectOptions that are not enums

CHANGELOG.md
Just update the CHANGELOG. Changes to the package and chart version are in a branch.
=> chore: 0.10.3 changelog

src/api-client/dataset.js, src/project/datasets/new/DatasetNew.container.js
Closes #984 
Dataset short_name changed to name in renku core-service, ui was adapted to those changes.
=> chore: dataset short name renamed to name

src/project/Project.present.js
Changes look like this....
I'm not sure where to send the user with the more about datasets link, i'm not sure there is specific datasets documentation.
Closes #971
=> feat(dataset): with message explaining what create and import operation do

src/utils/formgenerator/FormGenerator.test.js, src/utils/formgenerator/fields/FileUploaderInput.js
I added a new message to give users a hint about what happens with each file size...
Closes #973
=> fix(datasets): new message for file upload limits

src/dataset/Dataset.present.js, src/dataset/addtoproject/DatasetAdd.container.js, src/dataset/addtoproject/DatasetAdd.present.js
When importing a dataset if the project you want to import the dataset to needs to be migrated you will see a warning message...
Testing available: https://virginiatest.dev.renku.ch/
In order to test this, you should try to import a dataset into a project that needs to be migrated using the add to project button. 
Closes #964
=> feat(dataset): add dataset to project active and with migration check

.travis.yml, .travis/travis-deploy.sh
=> ci: pin docker version

src/model/RenkuModels.js, src/project/filestreeview/FilesTreeView.js, src/project/list/ProjectList.present.js, src/utils/formgenerator/FormGenerator.test.js
Fix misspelled word "empty" -- apparently a very common typo :sweat_smile: 
fix #1032
=> style: fix typos

CHANGELOG.md
Update CHANGELOG for the 0.10.5 release
=> chore: 0.10.5 changelog

CHANGELOG.md
Update CHANGELOG for the 0.11.0 release
=> chore: 0.11.0 changelog

package-lock.json, package.json
I updated the ckeditor to the latest version.
https://ckeditor.com/blog/
They did several improvements, the markdown features are working MUCH better now and they have also some new features.
- Some text has autoformatting on writing like headings, bold, italics, code (you can type ** in the editor and they will recognize that you are writing with format) --> this doesn't work for image inserts for now, maybe we can do some configuration somewhere for this to work
- They improved the markdown processor that they are using --> before I had to do some fixes in their editor because some things where broken and I can now delete this fixes I did
- Same as on top for the markdown code features (they are still missing some stuff but they are better)
- We can insert images by copy/pasting and …
=> Update of the ckeditor and added features to the editor

client/src/api-client/test-client.js, client/src/dataset/Dataset.container.js, client/src/dataset/Datasets.test.js, client/src/project/datasets/Datasets.test.js, client/src/project/datasets/ProjectDatasets.test.js
Closes #1090 
Closes #1096 --> i fixed something that the unit tests detected that was actually a bug
=> test: adds tests for dataset features

client/src/file/File.container.js, client/src/file/File.present.js, client/src/file/Lineage.container.js, client/src/file/Lineage.present.js, client/src/project/Project.js
Download button added to the nav bar of the file...
I also did some cosmetic changes and added the file size
This is how it looked before...
Closes #1133 
Closes #974 
Addresses the first part of #1083
=> feat: added download button to top bar and file size

client/src/api-client/dataset.js, client/src/utils/formgenerator/fields/FileUploaderInput.js
Added progress bar for file upload...
Closes #972
=> feat: progress bar for file upload

client/src/file/File.container.js, client/src/file/File.present.js, client/src/file/FileAndLineageComponents.js, client/src/file/Lineage.present.js, client/src/project/Project.css, client/src/project/Project.js, client/src/project/Project.present.js, client/src/project/filestreeview/FilesTreeView.js, client/src/project/filestreeview/treeviewstyle.css
File/Lineage view bar looks like this now...
It's blocked by an issue that needs to be confirmed to be merged since some changes in that issue also affect the file view.
I might need to do final changes after we merge that issue into this one.
Closes #864
=> feat: improvement in file and lineage view bar

client/src/project/status/ProjectVersionStatus.present.js, client/src/utils/formgenerator/FormPanel.js
This is actually inside the project form.
Fixes also problem in template up to date message...
Closes #1172
=> fix: error message for form panel is now correct

client/src/file/File.container.js
=> chore: add yaml to previewable file extensions

.github/workflows/acceptance-tests.yml
Run the acceptance tests when deploying a dedicated environment.
/deploy
re #1165
=> ci: run acceptance tests after deploy

CHANGELOG.md
Update changelog for 0.11.4 release.
=> chore: 0.11.4 CHANGELOG

.github/workflows/test-and-ci.yml
=> ci: update renku only on new tags

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui-server/Chart.yaml, helm-chart/renku-ui/Chart.yaml, server/package-lock.json, server/package.json
=> Release 0.11.7

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui-server/Chart.yaml, helm-chart/renku-ui/Chart.yaml, server/package-lock.json, server/package.json
=> Release 0.11.8

chartpress.yaml, server/src/routes/index.ts
Minor changes to the UI server
- Tag the UI and UI server consistently to simplify updating the values file in the main renku repository
- Add a route handler for testing ingress
=> Minor adjustments for ui server

client/src/App.js, client/src/project/list/ProjectList.present.js, client/src/project/new/Project.style.css, client/src/styles/bootstrap_ext/_button.scss, client/src/styles/bootstrap_ext/_underline_pill_nav.scss, client/src/styles/components/_renku_search_bar.scss, client/src/styles/fonts/_fonts.scss, client/src/styles/icons/icons.scss, client/src/styles/index.scss
This PR addresses ONLY the search bar
Before:
After:
Collapsed Before:
Collapsed After:
/deploy
=> feat(design): redesign of projects search bar

client/src/project/Project.present.js
=> feat: show clone command first on project settings

client/public/index.html, client/src/App.css, client/src/landing/NavBar.js, client/src/styles/bootstrap_ext/_nav_bar.scss, client/src/styles/components/_renku_general.scss
Redesign of footer, this was not in the documents that luca gave us so i did something I think looks good. For now we will need to have a footer, in the future we could consider removing it if we wanted to.
/deploy
=> feat(design): redesign of footer

client/src/dataset/list/DatasetList.container.js, client/src/dataset/list/DatasetList.present.js, client/src/project/Project.css, client/src/styles/components/_renku_search.scss
New datasets search page...
/deploy
=> feat(design): dataset search redesigned

client/src/collaboration/issue/Issue.js
Thank you @olevski for finding this!
A recent update in one of our libraries had this side effect. This PR has a temporary solution, but the proper fix will happen in #624
/deploy
fix #1293
=> fix: prevent overwriting local store in issues pages

client/src/notebooks/Notebooks.present.js, client/src/styles/bootstrap/_custom_bootstrap_variables.scss, client/src/styles/components/_renku_general.scss, client/src/styles/components/_renku_search.scss, client/src/utils/UIComponents.js
Redesign of interactive environments
Normal:
Compact:
Inside project: (might be adjusted/reviewed in the future)
/deploy
=> feat: redesign of environments

client/public/index.html, client/run-telepresence.sh, client/src/styles/bootstrap_ext/_button.scss, client/src/styles/fonts/_fonts.scss, server/run-telepresence.sh
- changes to run-telepresence for macOS 11 (Big Sur)
- only one body element in index.html
- fix font description
- refactoring of button.scss
=> New design minor fixes

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui-server/Chart.yaml, helm-chart/renku-ui/Chart.yaml, server/package-lock.json, server/package.json
=> build: release 0.11.10

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui-server/Chart.yaml, helm-chart/renku-ui/Chart.yaml, server/package-lock.json, server/package.json
=> build: release 0.11.11

client/src/dataset/Dataset.present.js, client/src/project/Project.present.js, client/src/project/datasets/DatasetsListView.js, client/src/styles/bootstrap_ext/_button.scss, client/src/styles/components/_file_uploader.scss, client/src/styles/components/_input_tag.scss, client/src/styles/icons/icons.scss, client/src/styles/index.scss, client/src/utils/UIComponents.js, client/src/utils/formgenerator/FormGenerator.css, client/src/utils/formgenerator/FormGenerator.present.js, client/src/utils/formgenerator/fields/CKEditorTextArea.js, client/src/utils/formgenerator/fields/CreatorsInput.js, client/src/utils/formgenerator/fields/FileUploaderInput.js, client/src/utils/formgenerator/fields/KeywordsInput.js, client/src/utils/formgenerator/fields/TextInput.js
Redesign of datsets inside projects
/deploy
=> feat(design): redesign of datasets inside projects

.github/workflows/acceptance-tests.yml, .github/workflows/test-and-ci.yml
=> chore: update workflow cleanup action reference

client/src/file/File.present.js, client/src/notebooks/Notebooks.test.js, client/src/utils/formgenerator/fields/ImageInput.js
Issues test still need to be reviewed, the collaboration tab should be merged before fixing this tests.
/deploy
=> fix: ui client tests fixes and warning fixes

client/src/collaboration/lists/IssueList.present.js, client/src/collaboration/lists/MergeRequestList.present.js, client/src/collaboration/merge-request/MergeRequest.present.js, client/src/notebooks/Notebooks.css, client/src/project/Project.present.js
=> feat(design): collaboration tab redesign

client/src/dataset/Dataset.present.js, client/src/file/File.present.js, client/src/landing/AnonymousHome.js, client/src/landing/NavBar.js, client/src/project/Project.present.js, client/src/project/shared/ProjectTag.container.js, client/src/utils/formgenerator/fields/CKEditorTextArea.js
/deploy renku=ui-design-test-fix
=> fix acceptance tests for ui-design

client/src/App.js, client/src/styleguide/ButtonsGuide.js, client/src/styleguide/ColorsGuide.js, client/src/styleguide/FormsGuide.js, client/src/styleguide/ListsGuide.js, client/src/styleguide/StyleGuide.js, client/src/styleguide/index.js, client/src/styles/bootstrap/_custom_bootstrap_variables.scss, client/src/styles/components/_renku_styleguide.scss, client/src/styles/index.scss, client/src/utils/UIComponents.js
Implement a style guide for the new Renku UI.
Fix #1322.
The style guide can be accessed under https://renku-ci-ui-1343.dev.renku.ch/style-guide
/deploy
=> Implement a style guide

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui-server/Chart.yaml, helm-chart/renku-ui/Chart.yaml, server/package-lock.json, server/package.json
Prepare a new release that includes a fix to #1368.
=> build: release 0.11.12

client/src/project/Project.present.js, client/src/styles/components/_project_display.scss, client/src/styles/index.scss
The project header needed some spacing/improvements and was not very responsive. I decided to build a flex grid to place items and it's now responsive.
When no description is set...
We have an issue in this case when it shrinks... 
I thought we can add a button like this... but saying add a description if there is no description
I could explore adding more less pace, switching the order of items when it shrinks, changing the weight/style of the item fonts if we wanted to as well.
=> fix(project): project header improved and responsive

client/src/App.css, client/src/collaboration/lists/IssueList.present.js, client/src/collaboration/lists/MergeRequestList.present.js, client/src/collaboration/merge-request/MergeRequest.present.js, client/src/dataset/list/DatasetList.present.js, client/src/help/Help.present.js, client/src/namespace/Namespace.present.js, client/src/notebooks/Notebooks.present.js, client/src/privacy/Privacy.container.js, client/src/project/Project.present.js, client/src/project/datasets/DatasetsListView.js, client/src/project/datasets/delete/DeleteDataset.present.js, client/src/project/new/ProjectNew.present.js, client/src/project/overview/ProjectOverview.present.js, client/src/styles/bootstrap/_custom_bootstrap.scss, client/src/utils/Markdown.js, client/src/utils/UIComponents.js, client/src/utils/formgenerator/fields/FileUploaderInput.js, helm-chart/renku-ui/values.yaml
On firefox, any page with empty content before the footer results in an extra scrollbar added to the right (see the screenshot below).
This change should fix it without having any negative impact on chrome.
=> refactor: fix the extra scrollbar on firefox

client/src/landing/NavBar.js, client/src/project/Project.present.js, client/src/project/new/Project.style.css, client/src/project/shared/ProjectAvatar.container.js, client/src/styles/bootstrap_ext/_nav_bar.scss, client/src/utils/UIComponents.js, client/src/utils/quicknav/QuickNav.present.js, client/src/utils/quicknav/QuickNav.style.css
Fixes to header and footer
- Unselected text is now grey and selected is white (I applied a fix since the selected was only showing when the user was in "your projects" but not in starred or all projects.
- Added spaces as luca asked
- Applied style to footer
The search bar in the header has been cleaned up, unfortunately, I couldn't change the style of the blue button (I will try harder but I don't want to use too much time on that now)
Todo, change order when small so that projects, environments and datasets are all in the same column
=> fix: minor ui fixes to header and footer

client/src/collaboration/lists/IssueList.present.js, client/src/collaboration/lists/MergeRequestList.present.js, client/src/dataset/list/DatasetList.present.js, client/src/project/datasets/DatasetsListView.js, client/src/project/list/ProjectList.present.js, client/src/styles/icons/icons.scss, client/src/utils/HelperFunctions.js, client/src/utils/List.js
=> feat(design): use of colours to identify entities

client/src/file/File.container.js
=> feat: add xml files preview

.github/workflows/acceptance-tests.yml, .github/workflows/test-and-ci.yml
re #SwissDataScienceCenter/renku#2179
=> ci: switch to renku-actions repository

client/src/notebooks/Notebooks.container.js, client/src/notebooks/Notebooks.present.js
To test, run try to use the start button on projects where the image is still building or the image build failed.
These projects can help:
* https://renku-ci-ui-1415.dev.renku.ch/projects/renku-qa/slow-build takes 10 minutes to build the Dockerfile
* https://renku-ci-ui-1415.dev.renku.ch/projects/renku-qa/broken-build has a problem with building the Dockerfile
Fix #1413
=> fix: do not autostart sessions if no image is available (#1413)

client/src/file/Lineage.css, client/src/project/datasets/DatasetsListView.js, client/src/project/datasets/ProjectDatasets.test.js, client/src/styleguide/ColorsGuide.js, client/src/utils/UIComponents.js
* feat: switch to tile display for project datasets
* feat: use new color scheme for lineage view
Fix #1402
=> Minor UI fixes

client/src/notebooks/Notebooks.present.js, client/src/project/Project.present.js, client/src/project/filestreeview/FilesTreeView.js, client/src/styleguide/ButtonsGuide.js, client/src/styles/bootstrap/_custom_bootstrap_variables.scss, client/src/styles/bootstrap_ext/_button.scss
Fix #1357
**Contents Selected**
**Hover over Lineage**
**Add Dataset**
**Style Guide**
**Notebook Launch**
/deploy
=> feat: make apearance of switch state clearer

client/src/landing/Landing.present.js
=> feat: add banner advertising new version to logged-in users (#1384)

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui-server/Chart.yaml, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
=> build: release 0.11.14

.github/workflows/acceptance-tests.yml, .github/workflows/test-and-ci.yml
=> chore: update CI API endpoint and renku-action ref

client/src/App.css, client/src/landing/NavBar.js, client/src/landing/logo-symbol.svg, client/src/styles/bootstrap_ext/_nav_bar.scss, client/src/utils/quicknav/QuickNav.present.js, client/src/utils/quicknav/QuickNav.style.css
=> Header takes up less vertical space

client/Dockerfile
Bumps the base image for the client. 
closes #1435 
=> chore: update base image

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui-server/Chart.yaml, helm-chart/renku-ui/Chart.yaml, server/package-lock.json, server/package.json
=> build: release 1.0.0-beta5

client/src/landing/TransitionalHome.js
=> Initial 1.0.0 home page

client/src/api-client/dataset.js, client/src/dataset/Dataset.present.js, client/src/dataset/DatasetFunctions.js, client/src/model/Model.js, client/src/model/RenkuModels.js, client/src/project/Project.state.js, client/src/project/datasets/DatasetsListView.js, client/src/project/datasets/change/DatasetChange.container.js
Inside form
Edit mode (for now it's non edit because something is missing in the backend)
Dataset inside project
Project List
Closes #1142
=> feat(dataset): ui to add and display dataset marquee image in projects 

client/package-lock.json, client/package.json
=> Consolidate synk dependency updates

client/package-lock.json, client/package.json
=> Consolidate several snyk updates

client/.eslintrc.json, client/src/notebooks/Notebooks.present.js
Follow the instructions in #1465 check that this works now.
Fix #1465
=> Allow popups on session iframes

client/src/api-client/pipeline.js, client/src/api-client/project.js, client/src/api-client/repository.js, client/src/collaboration/issue/Issue.js, client/src/contribution/Contribution.present.js, client/src/dataset/Dataset.present.js, client/src/file/File.container.js, client/src/file/Lineage.container.js, client/src/file/Notebook.js, client/src/model/RenkuModels.js, client/src/notebooks/Notebooks.container.js, client/src/notebooks/Notebooks.state.js, client/src/project/Project.js, client/src/project/Project.present.js, client/src/project/Project.state.js, client/src/utils/Markdown.js
=> fix: non master default branches handling

client/package-lock.json, client/package.json
Bundling several Snyk dependency updates.
=> Bundling several Snyk dependency updates

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui-server/Chart.yaml, helm-chart/renku-ui/Chart.yaml, server/package-lock.json, server/package.json
=> Release 1.0.0

.github/workflows/acceptance-tests.yml, .github/workflows/test-and-ci.yml, client/src/project/shared/Projects.state.js
Titles were missing in the "Your Projects" section of the landing page. 
Now it looks like this:
/deploy
=> fix: show titles in landing page Your Projects section

.github/workflows/acceptance-tests.yml, helm-chart/renku-ui/templates/ingress.yaml
=> charts: update ingress apiVersion

helm-chart/renku-ui-server/Chart.yaml
=> fix(chart): typo in UI server chart name

client/src/model/Model.test.js
Added some tests for the model.
=> test: added some model tests

client/src/landing/Landing.js, client/src/landing/Landing.present.js, client/src/model/RenkuModels.js, client/src/project/shared/Projects.state.js
Speed up loading of landing page by fetching less information.
/deploy renku=ui1337-uiserver-values
=> feat: improve performance of landing page (#1529)

server/package-lock.json, server/package.json
Fix the vulnerability on the `ansi-regex` library
/deploy renku=ui1337-uiserver-values
=> build(server): fix ansi-regex vulnerability

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui-server/Chart.yaml, helm-chart/renku-ui-server/values.yaml, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
=> build: release 1.1.0

.github/workflows/test-and-ci.yml, helm-chart/minikube-values.yaml, helm-chart/renku-ui-server/requirements.lock, helm-chart/renku-ui-server/templates/_helpers.tpl
=> Fix error on helm -- missing templates

client/src/notebooks/SessionCheatSheet.js
Update renku cheatsheet for sessions for renku-python 1.0.0
Closes #1558 
(Changes highlighted in red)
/deploy renku=448c938d4d4a4b263857fba8ff2d402f72ad9fba
=> feat: Add --name in Running and Tracking Commands Renku Cheat Sheet

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui-server/Chart.yaml, helm-chart/renku-ui-server/values.yaml, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
=> build: release 1.2.0

client/src/App.js, client/src/file/KnowledgeGraphStatus.container.js, client/src/index.js, client/src/model/RenkuModels.js, client/src/model/RenkuModels.test.js, client/src/notebooks/Notebooks.container.js, client/src/notebooks/Notebooks.present.js, client/src/notebooks/Notebooks.test.js, client/src/project/Project.js, client/src/project/Project.present.js, client/src/project/Project.state.js, client/src/project/Project.test.js, client/src/project/datasets/DatasetsListView.js, client/src/project/overview/ProjectOverview.test.js, client/src/project/settings/ProjectSettings.present.js, client/src/project/settings/ProjectSettings.test.js, client/src/project/shared/ProjectTag.container.js, client/src/utils/EnhancedState.js, client/src/utils/UIComponents.js, client/src/utils/formgenerator/FormGenerator.container.js
wip
Fix #1183
/deploy renku=448c938d4d4a4b263857fba8ff2d402f72ad9fba
=> Hoist project state to global model

client/src/utils/quicknav/QuickNav.container.js, client/src/utils/quicknav/QuickNav.present.js
Execute the search query or go to the selected suggestion by pressing the Enter key in the QuickNavPresent component
Closes #1576 
Closes #1575 
/deploy
=> feat: Pressing Enter on project search bar (#1576)

client/src/notebooks/Notebooks.container.js, client/src/notebooks/Notebooks.present.js, client/src/notebooks/Notebooks.state.js, client/src/notebooks/Notebooks.test.js
- Added status stopping to control when displaying the option to stop the session.
- Added display message when in the process of stopping a session.
Closes #787 
/deploy
=> feat: Allow to stop the session even if it is not fully started

client/src/notebooks/Notebooks.container.js, client/src/notebooks/Notebooks.present.js, client/src/notebooks/Notebooks.state.js, client/src/notebooks/Notebooks.test.js, client/src/project/Project.js, client/src/project/Project.test.js
- Added button to create a share link for sessions.
- Added handler when the branch name or commit key is not valid or incomplete
Closes #1596
/deploy renku=ui1608-tests-sessions
=> feat: Add session share link with more options

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui-server/Chart.yaml, helm-chart/renku-ui-server/values.yaml, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
=> chore: update changelog and version

chartpress.yaml, e2e/cypress/support/authentication/gui_commands.ts
Minor fix on e2e tests to support login
/deploy renku=1.0-next renku-graph=cli-v1 renku-core=v1.0.1
=> tests(e2e): fix login and add e2e folder to chartpress

client/src/project/status/RenkuVersionStatus.present.js
Minor refactor for the acceptance tests
/deploy renku=0000-project-version renku-graph=cli-v1 renku-core=v1.0.1
=> refactor(client): add id to project version element

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui-server/Chart.yaml, helm-chart/renku-ui-server/values.yaml, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Release with bugfixes and new features
/deploy
=> Release 1.3.0

client/src/project/status/RenkuVersionStatus.present.js
=> refactor(client): add project version id

client/src/dataset/Dataset.present.js, client/src/utils/UIComponents.js
/deploy renku=1.0-next renku-graph=cli-v1 renku-core=0000-disable-migration-tmp
=> fix(client): inherit classes from custom alerts

client/package-lock.json, server/package-lock.json
Close #1640 #1639
/deploy renku=1.0-next renku-graph=cli-v1 renku-core=0000-disbale-check-migration-optimization
=> bump follow-redirects to address security warnings

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui-server/Chart.yaml, helm-chart/renku-ui-server/values.yaml, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Changes to support Renku-python 1.0.0
/deploy renku=1.0-next renku-graph=2.0.0 renku-core=v1.0.4
=> RC1 for release 2.0.0

client/src/utils/components/markdown/RenkuMarkdownWithPathTranslation.js
Look at this project 
https://renku-ci-ui-1673.dev.renku.ch/projects/renku-qa/relative-links
Check that the images and links that should work do, and those that should not do not.
Do the same when viewing the README in the file view:
https://renku-ci-ui-1673.dev.renku.ch/projects/renku-qa/relative-links/files/blob/README.md
And here is an example in a subfolder.
https://renku-ci-ui-1673.dev.renku.ch/projects/renku-qa/relative-links/files/blob/subfolder/README.md
Fix #1655 
/deploy renku=1.0-next
=> Fix problems with relative links

client/src/utils/helpers/sentry/Sentry.js, client/src/utils/helpers/sentry/Sentry.test.js, helm-chart/renku-ui-server/templates/deployment.yaml, helm-chart/renku-ui-server/values.yaml, server/package-lock.json, server/package.json, server/run-telepresence.sh, server/src/authentication/index.ts, server/src/authentication/routes.ts, server/src/config.ts, server/src/index.ts, server/src/routes/apis.ts, server/src/utils/apiError.ts, server/src/utils/baseError.ts, server/src/utils/errorHandler.ts, server/src/utils/errorHandlerMiddleware.ts, server/src/utils/index.ts, server/src/utils/middlewares/errorHandlerMiddleware.ts, server/src/utils/middlewares/requestHandlerMiddleware.ts, server/src/utils/sentry/sentry.ts, server/tests/utils/index.test.ts
* This PR adds an error handler middleware for exceptions,  unhandled rejection, and uncaught Exception in server-UI.
* Enabled Sentry for error and performance
in server folder
```
SENTRY=1 ./run-telepresence.sh 
```
Some links throw an error:
https://renku-ci-ui-1658.dev.renku.ch/ui-server/auth/callback?session_state=5095cdff-87c5-4ab5-8d24-10637f318df1&code=ed9941e1-c76c-41c4-926e-f009753e1a97.5095cdff-87c5-4ab5-8d24-10637f318df1.0b088351-34f4-4a84-a043-8f855bc8ca36
https://renku-ci-ui-1658.dev.renku.ch/ui-server/api/debug-sentry
/deploy extra-values=uiserver.sentry.enabled=true,uiserver.sentry.debugMode=true,uiserver.sentry.namespace=renku-ci-ui-1658,uiserver.sentry.url=https://14558ba28035458ba9c7d206b7a48cb5@sentry.dev.renku.ch/4,uiserver.sentry.sampleRate=1
=> 1523 error handling UI server

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui-server/Chart.yaml, helm-chart/renku-ui-server/values.yaml, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Changes for release 2.0.0
/deploy
=> Release 2.0.0

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui-server/Chart.yaml, helm-chart/renku-ui-server/values.yaml, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
=> Release 2.0.1

.github/workflows/test-and-ci.yml
Change GitHub action to run `helm lint` on every PR.
=> lint chart on every PR

.github/workflows/test-and-ci.yml
=> fix problems building images

client/run-telepresence.sh, helm-chart/renku-ui-server/templates/deployment.yaml, helm-chart/renku-ui-server/values.yaml, helm-chart/renku-ui/templates/deployment-template.yaml, helm-chart/renku-ui/values.yaml
Align sentry values to the other renku deployment
Reference: https://swiss-data-science.slack.com/archives/G67N59QL8/p1643901194490749
_Temporarily excluded due to errors on deployment_
extra-values
ui.sentry.enabled=true,ui.sentry.dsn=https://4c715ff0b37642618a8b2a048b4da4fd@sentry.dev.renku.ch/3,ui.sentry.environment=renku-ui-sentry-update,uiserver.sentry.enabled=true,uiserver.sentry.dsn=https://14558ba28035458ba9c7d206b7a48cb5@sentry.dev.renku.ch/4,uiserver.sentry.environment=renku-uiserver-sentry-update #persist
=> build: update sentry values

README.rst, client/src/file/KnowledgeGraphStatus.present.js, client/src/notebooks/NotebookStart.present.js, client/src/notebooks/SessionCheatSheet.js, client/src/project/Project.present.js, client/src/project/new/ProjectNew.present.js, client/src/project/settings/ProjectSettings.present.js
=> style: fix doc links

client/public/renku-badge.svg, client/src/notebooks/NotebookStart.present.js
Add Renku badged for start project session
=> feat(client): add renku badge (#1678)

client/src/project/Project.present.js, e2e/cypress/fixtures/datasets/dataset-list-error.json, e2e/cypress/integration/local/projectDatasets.spec.ts
This PR add test when core service return an error when load the dataset list
Closes #1654
/deploy renku=000-acceptance-tests #persist
=> test(client): error loading datasets

client/src/file/KnowledgeGraphStatus.present.js, client/src/help/Help.present.js, client/src/landing/AnonymousHome.js, client/src/landing/Landing.present.js, client/src/landing/NavBar.js, client/src/notebooks/NotebookStart.present.js, client/src/notebooks/Notebooks.present.js, client/src/notebooks/SessionCheatSheet.js, client/src/project/Project.present.js, client/src/project/new/ProjectNew.present.js, client/src/project/settings/ProjectSettings.present.js, client/src/project/status/MigrationUtils.js, client/src/project/status/RenkuVersionStatus.present.js, client/src/project/status/TemplateVersionStatus.present.js, client/src/utils/constants/Docs.js
Further I added a dictionary for common links.
See #1700 for more information.
=> feat: move documentation links to utility class

client/src/api-client/project.js, client/src/dataset/Dataset.container.js, client/src/dataset/Dataset.present.js, client/src/notebooks/NotebookStart.present.js, client/src/notebooks/Notebooks.container.js, client/src/project/Project.js, client/src/project/Project.present.js, client/src/project/Project.state.js, client/src/project/Project.test.js, client/src/project/datasets/DatasetsListView.js, client/src/project/overview/ProjectOverview.container.js, client/src/project/overview/index.js, client/src/project/settings/ProjectSettings.container.js, client/src/project/settings/ProjectSettings.present.js, client/src/project/status/ProjectVersionStatus.present.js, client/src/project/status/RenkuVersionStatus.present.js, client/src/project/status/TemplateVersionStatus.present.js, e2e/cypress/integration/local/project.spec.ts, e2e/cypress/integration/local/projectDatasets.spec.ts, e2e/cypress/integration/local/session.spec.ts, e2e/cypress/support/renkulab-fixtures/projects.ts
The easiest way to test is to run in telepresence and change the implementation of `CoreServiceProjectMixin` in `Project.state.js`.
```
const CoreServiceProjectMixin = {
callCount: 0,
async fetchProjectLockStatus() {
const client = this.client;
const gitUrl = this.get("metadata.httpUrl");
@@ -50,8 +51,14 @@ const CoreServiceProjectMixin = {
this.set("lockStatus.error", lockStatus.error.reason);
return lockStatus.error.reason;
}
// this.set("lockStatus", lockStatus.data.result);
// return lockStatus.data.result;
// TESTING -- DELETE
const locked = CoreServiceProjectMixin.callCount < 4;
const result = { locked };
this.set("lockStatus", result);
CoreServiceProjectMixin.callCount = CoreServiceProjectMixin.callCount + 1;
return result;
},
};
```
The `lockStatus` is updated when the user …
=> Prevent changes to a project while the core-service is modifying it.

client/.eslintrc.json, client/src/file/KnowledgeGraphStatus.present.js, client/src/help/Help.present.js, client/src/landing/AnonymousHome.js, client/src/landing/Landing.present.js, client/src/landing/NavBar.js, client/src/notebooks/NotebookStart.present.js, client/src/notebooks/Notebooks.present.js, client/src/notebooks/SessionCheatSheet.js, client/src/project/Project.present.js, client/src/project/new/ProjectNew.present.js, client/src/project/settings/ProjectSettings.present.js, client/src/project/status/MigrationUtils.js, client/src/project/status/RenkuVersionStatus.present.js, client/src/project/status/TemplateVersionStatus.present.js, client/src/utils/constants/Docs.js
Merge the improvement contributed in  #1724 into the main line of development
=> refactor: better structure links to documentation

.github/workflows/test-and-ci.yml, CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui-server/Chart.yaml, helm-chart/renku-ui-server/values.yaml, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Changelog and version updates for release 2.1.0
/deploy renku=000-acceptance-tests
=> build: release 2.1.0

client/src/project/status/TemplateVersionStatus.present.js
Fix a bug with the update project button
=> fix: inherit function to update project

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui-server/Chart.yaml, helm-chart/renku-ui-server/values.yaml, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
=> build: release 2.1.1

CHANGELOG.md, client/package-lock.json, client/package.json, client/src/api-client/index.js, client/src/api-client/notebook-servers.js, client/src/notebooks/Notebooks.state.js, helm-chart/renku-ui-server/Chart.yaml, helm-chart/renku-ui-server/values.yaml, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
**sessions**
* fix problems starting projects with pinned images ( [#1769](https://github.com/SwissDataScienceCenter/renku-ui/issues/1769), [#1767](https://github.com/SwissDataScienceCenter/renku-ui/issues/1767))
/deploy
=> Release 2.1.2

client/package-lock.json, client/package.json, client/src/dataset/addtoproject/DatasetAdd.present.js, client/src/dataset/addtoproject/addDatasetNewProject.js, client/src/index.js, client/src/landing/Landing.js, client/src/landing/NabBarWarnings.js, client/src/model/Model.js, client/src/notebooks/Notebooks.container.js, client/src/notifications/Notifications.container.js, client/src/project/Project.js, client/src/project/new/ProjectNew.container.js, client/src/project/settings/ProjectSettings.container.js, client/src/statuspage/Statuspage.container.js, client/src/utils/components/formgenerator/FormGenerator.container.js, client/src/utils/helpers/EnhancedState.js
The first step of this work is to use redux toolkit.
/deploy renku-core=develop renku=tests-rp-version #persist
=> Search UI preparation: introduce redux-toolkit

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui-server/Chart.yaml, helm-chart/renku-ui-server/values.yaml, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Changelog update and version bumps.
/deploy renku=auto-update/renku-core-1.2.1 #persist
=> build: release 2.2.0

client/src/project/new/ProjectNew.present.js, client/src/project/new/ProjectNew.state.js, client/src/project/new/components/Namespaces.js, client/src/project/new/components/TemplateSource.tsx, client/src/project/new/components/UserTemplate.js, e2e/cypress/fixtures/namespaces.json, e2e/cypress/fixtures/projects/namespace-128.json, e2e/cypress/fixtures/projects/namespace-129.json, e2e/cypress/integration/local/newProject.spec.ts, e2e/cypress/support/renkulab-fixtures/fixtures.ts, e2e/cypress/support/renkulab-fixtures/projects.ts
This PR contains the e2e tests for the create a project form.
/deploy renku-core=develop renku=tests-new-project-form-changes #persist
=> test(e2e): add tests for form to create a new project

e2e/cypress/support/projects/gui_commands.ts
Fix an issue with scrolling on Firefox tests when launching them interactively.
/deploy
=> test(e2e): fix firefox scrolling issue

client/package-lock.json, client/package.json, client/src/dataset/addtoproject/DatasetAdd.present.js, client/src/dataset/addtoproject/addDatasetExistingProject.js, client/src/dataset/list/DatasetList.present.js, client/src/file/File.present.js, client/src/project/list/ProjectList.present.js, client/src/project/new/components/Namespaces.js, client/src/project/new/components/ShareLinkModal.js, client/src/project/new/components/Template.js, client/src/project/new/components/TemplateVariables.js, client/src/project/new/components/UserTemplate.js, client/src/utils/components/Logs.js, client/src/utils/ts-wrappers.js
Switch to use latest Reactstrap version ^9.0.1
/deploy renku=reactstrap-test-fixes #persist
=> build(client): update reactstrap

client/src/utils/components/authorFilter/AuthorFilter.tsx, client/src/utils/components/entitySearchFilter/EntitySearchFilter.tsx, client/src/utils/components/quicknav/QuickNav.present.js, client/src/utils/components/sortingEntities/SortingEntities.tsx, client/src/utils/components/typeEntityFilter/TypeEntityFilter.tsx, client/src/utils/components/visibilityFilter/VisibilityFilter.tsx
PR to fix error in reactstrap dependencies due rebase the master branch
/deploy renku=1811-main-menu-changes #persist
=> fix: reactstrap component updates

client/package-lock.json, client/package.json, client/src/notebooks/Notebooks.present.js, client/src/styles/bootstrap/_custom_bootstrap.scss, client/src/styles/bootstrap/_custom_bootstrap_variables.scss, client/src/styles/index.scss, client/src/utils/components/Icon.js, client/src/utils/components/formgenerator/fields/FileUploaderInput.js
Correct the CSS generation and fix minor styling problems identified in #1823 
/deploy renku=1811-main-menu-changes #persist
=> Fix CSS and other styling problems post 1823

client/src/model/RenkuModels.js, client/src/project/datasets/change/DatasetChange.container.js, client/src/styles/bootstrap/_custom_bootstrap_variables.scss, client/src/utils/components/formgenerator/fields/ImageInput.js
PR to update the component to load dataset image.
For testing use the Add dataset form.
Closes #1828 
/deploy renku=000-tests-ui-2_0-next #persist
=> feat: update ux dataset image component

client/src/features/kg-search/index.ts, client/src/features/kg-search/kg-search-api.ts, client/src/features/kg-search/kg-search.d.ts, client/src/styleguide/SearchGuide.tsx, client/src/styleguide/StyleGuide.js, client/src/utils/helpers/EnhancedState.js
Set up initial RTK-Query-based hook for getting data for the entity search.
You can see how the query in action on https://renku-ci-ui-1780.dev.renku.ch/style-guide/search
/deploy renku=000-tests-ui-2_0-next #persist
=> Use react-toolkit query for search

client/src/notebooks/NotebookStart.present.js
re SwissDataScienceCenter/renku#2550
/deploy #persist #notest
=> chore(client): update link to pinned images docs

.github/workflows/github-project.yml
PRs should be automatically added to the UI project when opened.
=> build: auto-add opened PRs to the UI project

client/public/index.html
* Changed title
* Added meta tags
Note -- the Confluence page referenced in the issue states that the description metadata should be "Max 165 characters." The content that was specified is 180 chars.
Fix #1848
/deploy renku=000-tests-ui-2_3_1 #persist
=> style: changes to index.html to improve SEO (#1848)

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui-server/Chart.yaml, helm-chart/renku-ui-server/values.yaml, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
=> build: release 2.4.0

client/public/ads.txt
=> minor: add ads.txt file (#1909)

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui-server/Chart.yaml, helm-chart/renku-ui-server/values.yaml, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Some minor bug fixes
/deploy renku-notebooks=master #persist
=> build: release 2.4.1

client/src/landing/AnonymousHome.js
Fix #1933
Clicking "Learn more" takes you to the "Renku Features" section.
/deploy renku=tests-ui-2.5.0 #persist
=> Fix learn more link

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui-server/Chart.yaml, helm-chart/renku-ui-server/values.yaml, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
New version of the UI
/deploy renku-core=develop renku=tests-ui-2.5.0 #persist
=> build: release 2.5.0

client/.eslintrc.json, client/src/landing/AnonymousHome.js, client/src/landing/NavBar.css, client/src/utils/components/ExternalLinks.js
PR to include social media link in landing page.
/deploy  #persist
=> feat: include social media links in landing page

client/src/project/status/RenkuVersionStatus.present.js, client/src/project/status/TemplateVersionStatus.present.js
update readthedocs links
/deploy renku=000-ui-server-chart #persist
fix #1967
=> chore(client): update readthedocs links

client/src/project/Project.js, client/src/project/Project.present.js, e2e/cypress/integration/local/addDatasetToProject.spec.ts
This PR is to fix acceptance tests DatasetUploadSpec.
/deploy renku=000-ui-server-chart #persist
=> fix: aceptance test when upload a dataset

client/run-telepresence.sh, helm-chart/renku-ui/templates/ui-client-deployment-template.yaml, helm-chart/renku-ui/templates/ui-server-deployment.yaml, helm-chart/renku-ui/values.yaml, server/README.md, server/run-telepresence.sh
A second attempt to set up telepresence 2, replacing #1799.
Telepresence (2) works for the client, but the server seems to encountering this issue: https://github.com/telepresenceio/telepresence/issues/2654
=> telepresence 2 take 2

client/package-lock.json, client/src/features/kgSearch/KgSearchApi.ts, client/src/features/kgSearch/KgSearchPage.tsx, client/src/features/kgSearch/KgSearchSlice.ts, client/src/landing/AnonymousHome.js, client/src/landing/NavBar.css, client/src/landing/NavBar.js, client/src/styles/components/_renku_search.scss, client/src/utils/components/authorFilter/AuthorFilter.tsx, client/src/utils/components/dateFilter/DateFilter.tsx, client/src/utils/components/entitySearchFilter/EntitySearchFilter.tsx, client/src/utils/components/quicknav/QuickNav.container.js, client/src/utils/components/quicknav/QuickNav.present.js, client/src/utils/components/quicknav/QuickNav.style.css, client/src/utils/components/typeEntityFilter/TypeEntityFilter.tsx, client/src/utils/components/visibilityFilter/VisibilityFilter.tsx, client/src/utils/helpers/Time.js
PR to add date filter in kg-search form
Closes #1936 
=> feat: Add kg search dates filter

e2e/cypress/support/datasets/gui_commands.ts
GitHub keeps showing a warning on this file in every PR. This should fix the problem.
=> minor: fix annoying warning

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
=> build: release 2.7.0

client/package-lock.json, client/package.json, client/src/utils/components/formgenerator/FormGenerator.css, client/src/utils/components/formgenerator/fields/CKEditorTextArea.js
This PR upgrade ckeditor-react to ^5.0.2 and add the new form styles.
Fix #1862 
=> feat: upgrade ckeditor5 (#1862)

client/package-lock.json, client/package.json, client/src/dataset/addtoproject/DatasetAdd.present.js, client/src/dataset/addtoproject/addDatasetNewProject.js, client/src/index.js, client/src/landing/Landing.js, client/src/landing/NabBarWarnings.js, client/src/model/Model.js, client/src/notebooks/Notebooks.container.js, client/src/notifications/Notifications.container.js, client/src/project/Project.js, client/src/project/new/ProjectNew.container.js, client/src/project/settings/ProjectSettings.container.js, client/src/statuspage/Statuspage.container.js, client/src/utils/components/formgenerator/FormGenerator.container.js, client/src/utils/helpers/EnhancedState.js
Internal changes necessary to support redux-toolkit.
=> build: changes to support redux-toolkit use

server/src/websocket/index.ts
This PR fixes a couple of auth-relate issues
- Prevent unnecessary errors for anonymous users.
- Send an error message when session cookies are missing (unlikely to happen in the UI, but possible when using an external tool like  Postman).
/deploy renku-gateway=master #persist
=> fix(server): handle websocket auth exceptions

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Release version 2.8.0
/deploy renku=ui-tests-2.8.0 renku-gateway=master #persist
=> build: release 2.8.0

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Release with Coteries styling.
/deploy renku=1978-styles-cards-projects-and-datasets #persist
=> build: release 2.8.1

server/src/routes/apis.ts
fixes #2030 
Someone should take a closer look to make sure we do not need any other changes.
/deploy renku=1978-styles-cards-projects-and-datasets renku-gateway=master #persist
=> fix(server): anonymous id set to fixed value

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Fixes around session ids for anonymous users.
=> build: release 2.8.2

client/src/api-client/project.js
=> feat: add timeout for core to release project lock (#1982)

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
=> build: release 2.9.0

helm-chart/renku-ui/templates/ui-server-deployment.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json, server/src/config.ts, server/src/routes/apis.ts, server/src/utils/index.ts
Hello friends :)
Hopefully this is acceptable. We need it so that we can start to implement sticky sessions in the core service.
closes https://github.com/SwissDataScienceCenter/renku-ui/issues/2018
=> feat(server): keep some cookies when proxying

client/package-lock.json, client/package.json, client/src/utils/components/notebook/index.tsx
PR that update @nteract/commutable library and change NotebookRender component as functional component.
This error appears when opening the project https://renkulab.io/projects/renku-insights/session-load-times/files/blob/notebooks/CaseStudy.ipynb
=> fix: load preview notebook

client/src/project/Project.js, client/src/project/Project.present.js, client/src/styles/components/_renku_tree.scss, client/src/utils/components/Tree.tsx, client/src/utils/components/entities/Executions.tsx, client/src/utils/components/entityHeader/EntityHeader.tsx, client/src/utils/ts-wrappers.js, client/src/workflows/Workflows.container.tsx, client/src/workflows/Workflows.present.tsx, client/src/workflows/Workflows.state.ts, client/src/workflows/index.ts
This prototype includes a fully working workflow browser and a first draft of the workflow details page.
Mind that the details components will be simplified and streamlined.
**What should be tested**
Using a couple of projects, we should verify that:
- The workflows browser works well, including the filters and the ordering
- The information should be consistent and up-to-date: this means the details components on the right are always in sync with the browser
renku-python reference: https://github.com/SwissDataScienceCenter/renku-python/pull/3135 
/deploy renku-core=workflow-ui-feature-branch #persist extra-values=core.sentry.dsn=https://0cc02f3a02d3474d9f7e90915873ab4d@sentry.dev.renku.ch/2,core.sentry.environment=renku-dev,core.sentry.enabled=true
=> Shape Up #1 - Third prototype: workflow browser with workflow details

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Release 2.10.0
Fix #2073 
/deploy  renku-notebooks=master #persist
=> build: release 2.10.0 #2073

helm-chart/renku-ui/templates/ui-client-deployment-template.yaml, helm-chart/renku-ui/templates/ui-server-deployment.yaml
addresses https://github.com/SwissDataScienceCenter/renku/issues/2683 for the UI server and client
=> chore: prevent service account from being automounted

helm-chart/renku-ui/templates/ui-client-deployment-template.yaml, helm-chart/renku-ui/templates/ui-server-deployment.yaml, helm-chart/renku-ui/values.yaml
Goes with https://github.com/SwissDataScienceCenter/renku/pull/2743
=> chore: make service account token mounting configurable

client/src/model/RenkuModels.js, client/src/styles/components/_renku_tree.scss, client/src/utils/Utils.test.js, client/src/utils/components/Tree.tsx, client/src/utils/components/entities/Children.tsx, client/src/utils/components/entities/Creators.tsx, client/src/utils/components/entities/Duration.tsx, client/src/utils/components/entities/Executions.tsx, client/src/utils/helpers/Time.js, client/src/utils/ts-wrappers.js, client/src/workflows/Workflows.container.tsx, client/src/workflows/Workflows.present.tsx, client/src/workflows/Workflows.state.ts
_work in progress, more info soon_
renku-python reference: https://github.com/SwissDataScienceCenter/renku-python/pull/3135
=> Shape Up #1 - Fourth prototype: workflow metadata and visualizer

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Release 2.10.1
Fix https://github.com/SwissDataScienceCenter/renku-ui/issues/2084
=> build: release 2.10.1

client/src/model/RenkuModels.js, client/src/styles/components/_renku_tree.scss, client/src/utils/components/Tree.tsx, client/src/utils/helpers/url/Url.js, client/src/workflows/Workflows.container.tsx, client/src/workflows/Workflows.present.tsx, client/src/workflows/Workflows.state.ts
Prototype 5 - workflow details visualizer
_Work in progress -- more info coming soon_
=> Shape Up #1 - Fifth prototype part1: workflow visualizer

client/src/styles/bootstrap/_custom_bootstrap_variables.scss, client/src/styles/components/_renku_cards.scss, client/src/styles/components/_renku_form.scss, client/src/styles/components/_renku_tree.scss, client/src/styles/icons/icons.scss, client/src/utils/components/Tree.tsx, client/src/utils/components/entities/Children.tsx, client/src/utils/components/entities/Creators.tsx, client/src/utils/components/entities/Entities.css, client/src/utils/components/entities/Slug.tsx, client/src/utils/components/entityHeader/EntityHeader.tsx, client/src/utils/ts-wrappers.js, client/src/workflows/Workflows.present.tsx, client/src/workflows/Workflows.scss
This PR is to apply design in workflows.
It includes also:
- Display in multiple lines when the slug or project title in the entity card exceeds the width of the card for mobiles.
- Fix show the right arrow-indicator when expand a row in a nested row
=> Shape Up #1 - Apply Design

client/src/utils/components/Tree.tsx, client/src/workflows/Workflows.container.tsx, client/src/workflows/Workflows.present.tsx
This PR includes the following:
- automatically select the first input or mapping on composite workflow (when available)
* any workflow is ok for testing
- visualize links on composite workflows
* example: https://renku-ci-ui-2093.dev.renku.ch/projects/workflows-pet-projects/workflows-parameters/workflows/952c938055a041168f6e795ae33b0d22
- improve auto-scroll behavior when workflow details become available
* any project with workflow is ok for testing -- compare with an older version like https://renku-ci-ui-2038.dev.renku.ch
- (fix) visualize outdated workflows
* example: https://renku-ci-ui-2093.dev.renku.ch/projects/workflows-pet-projects/nested-workflows/workflows/998ff6b7853d4889bbec55dfb31b4ba6
=> Shape Up #1 - Fifth prototype fixes

client/src/utils/components/entities/Description.tsx
=> style: fix typo in the project description CTA

client/src/notebooks/components/SessionFullScreen.tsx, client/src/notebooks/components/StartSessionProgressBar.tsx
Closes #2095 
/deploy extra-values=notebooks.amalthea.resourceUsageCheck.enabled=true #persist
=> fix: ui state tracking the session status (#2095)

client/src/styles/components/_renku_tree.scss, client/src/utils/components/ExternalLinks.js, client/src/utils/components/InformativeIcon.tsx, client/src/utils/components/Tree.tsx, client/src/workflows/Workflows.present.tsx, client/src/workflows/Workflows.scss
PR to apply design to workflows details (steps, links, mappings, outputs, inputs and parameters).
=> Shapeup workflows design v2

client/src/workflows/Workflows.present.tsx
This PR is for modifying the tooltip texts in the workflow view.
=> feat(client): update tooltip texts

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
=> build: release 2.11.1

.github/workflows/acceptance-tests.yml
PR to upload cypress artifacts.
=> feat: upload artifact cypress

server/Dockerfile
=> build: update server node version to 18.12

client/src/features/kgSearch/KgSearchSlice.ts, client/src/utils/components/authorFilter/AuthorFilter.tsx, client/src/utils/components/typeEntityFilter/TypeEntityFilter.tsx, server/src/websocket/index.ts
PR to add kg-search improvements.
Closes #2127 
=> feat: Kg search improvements (#2127)

client/src/project/Project.present.js, client/src/project/new/ProjectNew.container.js, e2e/cypress/integration/local/project.spec.ts
=> fix(client): prevent resetting user inputs on the Fork component

client/.eslintrc.json, client/src/notebooks/Notebooks.css, client/src/notebooks/Notebooks.present.js, client/src/notebooks/Notebooks.state.js, client/src/notebooks/components/ResourcesSessionModal.tsx, client/src/notebooks/components/SessionModal.css, client/src/utils/components/Logs.css, client/src/utils/components/Logs.tsx, client/src/utils/helpers/HelperFunctions.js, e2e/cypress/integration/local/session.spec.ts
Fix #2139 
/deploy renku-notebooks=fix-logs-maxlines-parameter #persist
=> Unify session log styling

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
The post-sprint release of the UI
=> build: release 2.13.0

client/src/features/inactiveKgProjects/InactiveKgProjects.tsx, client/src/features/inactiveKgProjects/components/ActivationProgress.tsx, client/src/features/projects/ProjectKgApi.ts, server/src/api-client/index.ts, server/src/config.ts, server/src/utils/asyncSemaphore.ts, server/src/websocket/handlers/activationKgStatus.ts, server/src/websocket/index.ts
PR to solve error when fetch activation status.
=> 000 fix fetch activation status

client/src/websocket/index.ts
PR to resume kg activation in progress when websocket is available again.
=> 000 fetch kg status after drop websocket

client/.eslintrc.json, client/package.json, server/package.json, tests/package.json
Fix linting
/deploy #persist #notest
=> test: fail tests on linting warnings

client/package-lock.json, client/package.json, server/package-lock.json, server/package.json, tests/package-lock.json
Includes the dependencies updates from #2178 #2186 #2191 #2193 #2194
/deploy #persist #notest
=> build: update various dependencies

.github/workflows/acceptance-tests.yml
/deploy #persist #notest #cypress
=> Integrate test-renku-cypress action

client/src/notebooks/Notebooks.present.js, tests/cypress/e2e/local/session.spec.ts, tests/cypress/fixtures/sessions/sessionError.json, tests/cypress/support/renkulab-fixtures/sessions.ts
PR to add stop button by default when session fails.
Closes #1892 
=> feat: add stop session button by default when session fails (#1892)

client/src/project/new/Project.style.css, client/src/project/new/ProjectNew.present.js
PR to fix layout when create a new project
closes #2077 
=> fix: adjust layout on creation a new project

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
=> build: release 2.14.0

server/package-lock.json, server/package.json
This includes running `npm audit fix` and the following upgrades from snyk: #2218 #2219 #2220 #2221 #2222
=> build(server): upgrade packages

client/src/features/inactiveKgProjects/InactiveKgProjects.tsx, client/src/features/inactiveKgProjects/InactiveKgProjectsApi.ts, client/src/features/inactiveKgProjects/inactiveKgProjects.css, client/src/features/kgSearch/KgSearchApi.ts, client/src/features/kgSearch/KgSearchPage.tsx, client/src/landing/Landing.present.js, client/src/utils/components/searchResultsContent/SearchResultsContent.tsx, client/src/utils/components/sortingEntities/SortingEntities.tsx, client/src/utils/customHooks/UseGetInactiveProjects.ts
PR to test changes in kg-search repo. v2
/deploy renku-graph=development #persist
=> fix: load all inactive projects in kg

client/package-lock.json, server/package-lock.json, server/package.json
This includes #2232 #2234 #2235 #2236 
=> build(server): update dependecies

client/src/dataset/Dataset.present.js, client/src/dataset/DatasetFunctions.js, client/src/dataset/Datasets.test.js, client/src/dataset/list/DatasetList.present.js, client/src/landing/Landing.present.js, client/src/notebooks/components/AboutSessionModal.tsx, client/src/notebooks/components/Session.d.ts, client/src/project/Project.present.js, client/src/project/datasets/DatasetsListView.js, client/src/project/list/ProjectList.present.js, client/src/styles/components/_renku_cards.scss, client/src/utils/components/List.js, client/src/utils/components/entities/Buttons.tsx, client/src/utils/components/entities/Creators.tsx, client/src/utils/components/entities/Description.tsx, client/src/utils/components/entities/Entities.css, client/src/utils/components/entities/Label.tsx, client/src/utils/components/entities/LinkedEntitiesByItemType.tsx, client/src/utils/components/entities/Slug.tsx, client/src/utils/components/entities/Tags.tsx, client/src/utils/components/entities/VisibilityIcon.tsx, client/src/utils/components/entityHeader/EntityHeader.scss, client/src/utils/components/entityHeader/EntityHeader.tsx, client/src/utils/ts-wrappers.js
PR to add new entity header styles and restore entity images.
0349b088.png)
Closes #2179 
=> feat: restore projects and datasets images (#2179)

.github/workflows/test-and-ci.yml, client/src/App.js, client/src/api-client/instance.js, client/src/api-client/test-client.js, client/src/dataset/addtoproject/addDatasetNewProject.js, client/src/features/projects/ProjectApi.ts, client/src/project/new/ProjectFork.test.js, client/src/project/new/ProjectNew.container.js, client/src/project/new/ProjectNew.present.js, client/src/project/new/ProjectNew.state.js, client/src/project/new/ProjectNew.test.js, client/src/project/new/components/SubmitFormButton.tsx, client/src/project/new/components/UserTemplate.js, client/src/project/shared/Projects.state.js, client/src/utils/customHooks/UseGetNamespaces.ts, client/src/utils/customHooks/UseGetProjects.ts, tests/cypress/support/renkulab-fixtures/fixtures.ts
PR to fetch namespaces owned only for fork and create projects.
Pending:
/deploy #persist #cypress renku=renku-ui-2.15.0-tests
closes #2027
=> feat: get namespaces owned only when fork a project

client/src/project/Project.js
Refactoring to prevent the projects page from re-rendering all the time.
Fix #2215
/deploy #persist #cypress renku=renku-ui-2.15.0-tests
=> Reduce re-rendering

client/package-lock.json, client/package.json
The update to storybook breaks telepresence.
/deploy #cypress #persist
=> Revert  2c8d5f4

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Release with some minor fixes and refactorings.
/deploy #persist #cypress renku=renku-ui-2.15.0-tests
=> build: release 2.15.0

client/src/file/KnowledgeGraphStatus.present.js, client/src/notebooks/components/AboutSessionModal.tsx, client/src/notebooks/components/SessionCheatSheet.tsx, client/src/project/new/components/UserTemplate.js, client/src/project/settings/ProjectSettings.present.js, client/src/styles/bootstrap_ext/_button.scss, client/src/utils/components/ExternalLinks.js, client/src/utils/constants/Docs.js, client/src/workflows/Workflows.present.tsx, helm-chart/renku-ui/values.yaml
* adjust style for external links
* fix broken links to documentation
* use stable branch for documentation URLs
/deploy renku=000-cypres-tests-new-search #persist #cypress
=> fix(client): update documentation links and adjust style

client/package-lock.json, client/package.json, client/public/static/public/theme.css, client/src/styles/bootstrap_ext/_button.scss, client/src/styles/bootstrap_ext/_nav_bar.scss, client/src/utils/components/entityHeader/EntityHeader.scss, server/package-lock.json, server/package.json, tests/cypress/e2e/local/session.spec.ts
Upgrades to
* bootstrap
* reactstrap
* dompurify
/deploy #persist #cypress renku=000-cypres-tests-new-search
=> Bundle together multiple dependency updates

client/src/notebooks/ObjectStoresConfig.present.js, client/src/notebooks/ObjectStoresConfig.scss, client/src/notebooks/ObjectStoresConfig.test.js, tests/cypress/e2e/local/newSession.spec.ts
* The endpoint must be a valid URL
* The bucket name must be at least 3 characters, contain only lowercase characters, numbers, '.', or '-', and must start and end with a letter or number
Fix #2210
/deploy #persist #cypress renku=000-cypres-tests-new-search
=> Validate object store inputs

client/package-lock.json, client/package.json, client/src/authentication/Authentication.test.js, client/src/file/FilePreview.tsx, client/src/namespace/Namespace.present.js, client/src/notebooks/Notebooks.test.js, client/src/notifications/Notifications.test.js, client/src/project/Project.test.js, client/src/project/ProjectSuggestActions.test.js, client/src/project/new/ProjectNew.test.js, client/src/setupTests.js, client/src/statuspage/Statuspage.present.js
PR to eliminate console errors and warning in unit tests.
Close #2228 
/deploy renku=000-cypres-tests-new-search #cypress #persist
=> test: eliminate console errors and warnings in unit tests (#2228)

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Release 3.0.0
/deploy #persist #cypress renku=000-cypres-tests-new-search
=> build: release 3.0.0

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Release 3.2.0
/deploy #persist #cypress renku=renku-ui-3.2.0-tests
=> build: release 3.2.0

.github/workflows/test-and-ci.yml, README.md, client/src/Maintenance.test.js, client/src/file/File.test.js, client/src/model/Model.test.js, client/src/notebooks/Notebooks.test.js, client/src/notifications/Notifications.test.js, client/src/privacy/Privacy.test.js, client/src/project/Project.test.js, client/src/project/datasets/ProjectDatasets.test.js, client/src/project/new/ProjectNew.container.js, client/src/project/new/ProjectNew.test.js, client/src/project/overview/ProjectOverview.test.js, client/src/statuspage/Statuspage.test.js, client/src/utils/Utils.test.js
Remove console errors from the unit tests
/deploy #persist #cypress renku=renku-ui-3.2.0-tests
=> Fix errors in tests

server/package-lock.json, tests/package-lock.json
Dependencies updates.
Supersedes #2352
/deploy #persist #cypress renku=auto-update/renku-ui-3.2.0
=> Dependencies updates

server/src/utils/middlewares/lastProjectsMiddleware.ts
=> Do not remember projects that are just ids (#2316)

client/package-lock.json, client/package.json, client/src/project/Project.css, client/src/project/filestreeview/FilesTreeView.js, client/src/project/filestreeview/treeviewstyle.css, tests/cypress/e2e/local/project.spec.ts
Make either file tree or file content sticky as needed
Replacement for #2406
Fix #2336 
=> File scrolling fixes (replacement for 2406)

client/src/notebooks/Notebooks.present.js, client/src/notebooks/components/Session.d.ts, client/src/notebooks/components/SessionListStatus.tsx, client/src/utils/components/list/ListBarSessions.tsx, tests/cypress/fixtures/sessions/sessionError.json
=> feat: improve display of session error information (#2396)

client/package-lock.json, client/package.json
=> Group snyk updates 20230308

client/package-lock.json, client/package.json
=> Group snyk updates 20230315

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
/deploy #persist #cypress #renku=renku-ui-3.4.0-tests
=> build: release 3.4.0

CHANGELOG.md, client/package-lock.json, client/package.json, client/src/components/Logs.tsx, client/src/components/ssh/ssh.tsx, client/src/features/session/components/SessionButtons.tsx, client/src/notebooks/NotebookStart.present.js, client/src/notebooks/Notebooks.container.js, client/src/notebooks/Notebooks.present.js, client/src/notebooks/Notebooks.state.js, client/src/notebooks/Notebooks.test.js, client/src/utils/helpers/SessionFunctions.ts, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
This includes a few minor fixes:
- (urgent) fix the URL to running sessions on the dashboard
- update ssh message
- prepare a bugfix release
=> Fix dashboard links to sessions and update ssh message

client/src/dataset/DatasetFunctions.js, client/src/features/project/Project.d.ts, client/src/features/project/ProjectKnowledgeGraphStatus.tsx, client/src/features/project/dataset/ProjectDatasetImport.tsx, client/src/features/project/dataset/ProjectDatasetNewEdit.tsx, client/src/features/project/dataset/ProjectDatasetShow.tsx, client/src/features/project/dataset/ProjectDatasetsListView.tsx, client/src/features/project/dataset/ProjectDatasetsView.tsx, client/src/features/project/file.tsx, client/src/features/project/index.ts, client/src/file/Lineage.container.js, client/src/project/Project.js, client/src/project/Project.present.js, client/src/project/datasets/ProjectDatasets.test.js, client/src/project/overview/ProjectOverview.container.js, client/src/utils/helpers/url/Url.js
The is preparation for further work on #2415. 
/deploy #persist #cypress renku=renku-ui-3.4.1-tests
=> Stop passing components as properties in the Project view

client/.eslintrc.json, client/src/dataset/Dataset.present.js, client/src/features/project/Project.d.ts, client/src/features/project/dataset/ProjectDatasetShow.tsx, client/src/features/project/dataset/ProjectDatasetsListView.tsx, client/src/features/project/projectCoreApi.ts, client/src/utils/helpers/EnhancedState.js
Use RTK-Query to retrieve dataset information.
Implements parts of #2415
/deploy #persist #cypress renku=renku-ui-3.4.1-tests
=> Query for datasets using RTK-Query

client/src/utils/helpers/Time.js
Hello, as per your request, I have conserved the ISO format and also made an improvement by updating the toIsoString(inputDate,type) method from the Time class to include a new type called "datetime-timezone".
=> Show timezone when showing times

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
=> build: release 3.4.2

client/src/project/status/TemplateVersionStatus.present.js
=> fix(client): update broken documentation link

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
=> build: release 3.4.3

client/package-lock.json, client/package.json
Group Snyk updates
/deploy #persist #cypress renku=leafty/update-tests-renku-ui-2495
=> Group snyk updates 2023-05-10

tests/cypress/e2e/newDataset.spec.ts, tests/cypress/fixtures/datasets/create-dataset-title-error.json
Added tests for creating datasets with the following problems:
* empty title
* invalid title
Extended test for creating datasets with the following problems:
* file failed to upload
=> tests: added addition dataset creation tests

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Release 3.5.0
/deploy #persist #cypress renku=leafty/update-tests-renku-ui-2495
=> build: release 3.5.0

client/src/notebooks/components/SessionClassOption.module.scss, client/src/notebooks/components/SessionClassOption.tsx, client/src/notebooks/components/SessionStorageOption.tsx
Updated the session class selector styling:
Also, on error display this message:
=> Update the session class selector styles

client/src/components/FileExplorer.tsx, client/src/components/formgenerator/fields/FileUploaderInput.js, client/src/dataset/Dataset.present.js
Fix #1270
/deploy renku-core=develop renku=2315ui-project-status #persist #notest #cypress
=> Dataset file explorer to link to file contents (not file lineage)

client/src/file/Lineage.container.js
Ensure that the URL remains correct when navigating from lineage view to contents view.
Fix #2571 
/deploy renku-core=develop renku=2315ui-project-status #persist #notest #cypress
=> Fix navigating from lineage to contents

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Release 3.6.0
/deploy renku-core=develop renku=2315ui-project-status #persist #cypress
=> build: release 3.6.0

.github/workflows/test-and-ci.yml
=> fix(ci/cd): fix the test action self-cancelling on master

client/src/dataset/Dataset.present.js, client/src/features/project/dataset/ProjectDatasetShow.tsx, client/src/features/project/dataset/ProjectDatasetsView.tsx, client/src/project/datasets/delete/DeleteDataset.present.js, tests/cypress/e2e/projectDatasets.spec.ts, tests/cypress/support/renkulab-fixtures/datasets.ts
Deleting a dataset was broken. This should fix that feature again.
=> fix: dataset delete is possible again

client/src/features/project/Project.d.ts, client/src/features/project/projectCoreApi.ts, client/src/project/components/ProjectSettingsSessions.module.scss, client/src/project/components/ProjectSettingsSessions.tsx, tests/cypress/e2e/project.spec.ts
Remove the session class selector and add input for existing settings.
=> feat(client): update session project settings for resource pools

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
=> build: release 3.7.0

client/run-telepresence.sh
Since we set up a dashboard message in the telepresence script, let's explicitly mention we are running telepresence.
=> chore: explicitly mention telepresence is running

client/src/features/project/dataset/ProjectDatasetsView.tsx, client/src/features/project/useProjectCoreSupport.ts, tests/cypress/e2e/projectDatasets.spec.ts, tests/cypress/fixtures/errors/core-error-2200.json, tests/cypress/support/renkulab-fixtures/projects.ts
The date list page now displays the backend error if one occurs when trying to determine project support status.
=> feat: surface backend error message on dataset list page

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Release 3.8.0
/deploy #persist #cypress renku=core-svc-horizontal-scaling renku-core=v2.6.0 extra-values=global.renku.cli_version=2.6.0rc1 renku-gateway=master
=> build: release 3.8.0

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Release 3.8.1
/deploy #persist #cypress renku=core-svc-horizontal-scaling renku-core=v2.6.0 extra-values=global.renku.cli_version=2.6.0rc1 renku-gateway=master
=> Release 3.8.1

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Release 3.9.0
/deploy #persist #cypress  renku=crac-service-helm-chart
=> build: release 3.9.0

client/src/features/project/dataset/ProjectDatasetsListView.tsx
PR to include sort by title in project's datasets list.
Before:
After:
Closes #1514 
=> feat: Sort project's datasets by title in ascending order (#1514)

helm-chart/renku-ui/templates/ui-server-deployment.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json, server/src/config.ts, server/src/index.ts, server/src/utils/prometheus/prometheus.ts
=> build(server): set up prometheus metrics

server/src/authentication/index.ts, server/src/utils/middlewares/lastProjectsMiddleware.ts, server/src/utils/middlewares/lastSearchQueriesMiddleware.ts
Check return values from redis and log errors when appropriate.
Fix #2610
/deploy #persist renku=renku-ui/3.11-acceptance-tests
=> Log redis failures during operations 

client/package-lock.json, client/package.json, tests/package-lock.json
/deploy #persist renku=renku-ui/3.11-acceptance-tests
=> chore: snyk updated 2023-08-10

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Release 3.11.0
/deploy #persist renku=renku-ui/3.11-acceptance-tests
=> Release 3.11.0

client/src/components/list/ListBarSessions.tsx, client/src/features/session/components/status/SessionHibernationStatusDetails.tsx, client/src/features/session/components/status/SessionStatusText.tsx, tests/cypress/e2e/dashboard.spec.ts
=> Update the status text when the session is paused

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
=> build: release 3.12.0

server/src/utils/index.ts, server/src/websocket/handlers/sessions.ts
This fixes the backend filtering for sessions
=> fix(server): filter warning messages from sessions

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Release bug fix version 3.12.2
=> build: release 3.12.2

.github/workflows/acceptance-tests.yml
Use the new Cypress acceptance tests.
/deploy #persist #notest #cypress
re: SwissDataScienceCenter/renku#3232
=> ci: run the new Cypress acceptance tests

client/.storybook/preview.tsx, client/src/features/dashboard/Dashboard.tsx, client/src/features/dashboard/components/DashboardMessage.stories.tsx, client/src/features/dashboard/components/DashboardMessage.tsx
URL: https://renku-ci-ui-2798.dev.renku.ch/storybook/?path=/docs/components-dashboardmessage--docs
=> feat(client): add stories for the dashboard message

client/src/components/authorFilter/AuthorFilter.stories.tsx, client/src/components/buttons/ButtonWithMenu.stories.tsx, client/src/components/buttons/RoundButtonGroup.stories.tsx, client/src/components/form-field/CreatorsInput.stories.tsx, client/src/components/formlabels/FormLabels.stories.tsx, client/src/components/list/ListBar.stories.tsx, client/src/components/list/ListCard.stories.tsx, client/src/components/loginAlert/LoginAlert.stories.tsx, client/src/components/markdown/RenkuMarkdown.stories.tsx, client/src/components/progress/Progress.stories.tsx, client/src/components/progress/ProgressSteps.stories.tsx, client/src/components/sortingEntities/SortingEntities.stories.tsx, client/src/components/templateSelector/TemplateSelector.stories.tsx, client/src/components/typeEntityFilter/TypeEntityFilter.stories.tsx, client/src/components/visibility/Visibility.stories.tsx, client/src/components/visibilityFilter/VisibilityFilter.stories.tsx
PR to update the format of the stories and include more readable selectors to manage the stories.
=> feat(storybook): Upgrade to CSF 3 and Improved story selectors (#2756)

server/package-lock.json, server/package.json, server/src/index.ts, server/src/utils/sentry/sentry.ts, server/src/websocket/index.ts
See: #2813.
Event example: https://sentry.dev.renku.ch/organizations/sentry/discover/renku-uiserver:35bbb09ace5b451aa03a33317d96034f/
/deploy
=> chore(server): add more Sentry logging to the WebSocket server

tests/cypress/e2e/newDataset.spec.ts
Small change to make one of the newDataset tests less flaky.
=> tests: make newDataset test less flaky

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Release 3.13.0 including persistent sessions
/deploy renku=ui2686-update-tests renku-notebooks=1.19.0 extra-values=notebooks.userSessionPersistentVolumes.enabled=true
=> build: release 3.13.0

client/src/features/dashboard/components/InactiveKgProjects.tsx
Only request 10 projects on the dashboard to more quickly notify the user that there are projects that need indexing.
But, if a more complete list is known, show that.
/deploy
=> feat: speed up non-indexed project warning (#2774)

README.md
=> chore: fix the badge on the readme

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
=> build: release 3.13.1

.github/workflows/test-and-ci.yml, client/package-lock.json, server/jest.config.js, server/package-lock.json, server/package.json, server/tests/websocket/index.test.ts
Updates the CI/CD workflow file and some dependencies.
Supersedes:
- #2851 
- #2852
=> chore(build): update CI/CD build and dependencies

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
=> build: release 3.14.0

tests/cypress/e2e/home.spec.ts, tests/cypress/e2e/maintenance.spec.ts, tests/cypress/support/renkulab-fixtures/global.ts, tests/cypress/support/renkulab-fixtures/user.ts
=> tests: add tests for slow and error responses from user and statuspage

client/src/statuspage/StatuspageAPI.js, tests/cypress/support/renkulab-fixtures/global.ts
Handle a bad response from the statuspage API
=> fix: correctly handle statuspage down

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
=> build: release 3.15.1

client/src/features/project/components/AddCloudStorageButton.tsx, client/src/features/project/components/ProjectSettingsCloudStorage.tsx, client/src/features/project/projectCloudStorage.constants.ts, client/src/features/session/components/options/SessionCloudStorageOption.tsx, client/src/utils/helpers/RtkQueryErrorsContext.tsx, tests/cypress.config.ts, tests/cypress/e2e/newSession.spec.ts, tests/cypress/e2e/projectSettings.spec.ts
Enable Read-Write mode by default, leaving the possibility to limit the access to "read-only"
/deploy
fix #2899
=> feat: enable RW option on cloud storage

client/src/workflows/Workflows.present.tsx
=> chore(client): update the workflows documentation link

client/src/features/dashboard/components/InactiveKgProjects.tsx, client/src/features/inactiveKgProjects/InactiveKgProjects.tsx, client/src/features/inactiveKgProjects/InactiveKgProjectsApi.ts, client/src/features/inactiveKgProjects/components/ActivationProgress.tsx, client/src/features/inactiveKgProjects/components/KgActivationHeader.tsx, client/src/features/inactiveKgProjects/inactiveKgProjects.types.ts, client/src/features/inactiveKgProjects/inactiveKgProjects.utils.ts, client/src/features/inactiveKgProjects/inactiveKgProjectsSlice.ts, client/src/features/inactiveKgProjects/index.ts, client/src/utils/customHooks/UseGetInactiveProjects.ts, client/src/utils/ts-wrappers.js, client/src/websocket/WsMessages.ts, client/src/websocket/handlers/kgActivationStatusHandler.ts, client/src/websocket/index.ts, server/src/websocket/handlers/activationKgStatus.ts
* Correctly update indexing progress and stop polling when indexing has finished
* Minor code refactoring
/deploy extra-values=global.renku.cli_version=2.7.0
=> Correctly update progress of project indexing

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
- Let users pin projects to the dashboard ([#2898](https://github.com/SwissDataScienceCenter/renku-ui/pull/2898), [renku#3325](https://github.com/SwissDataScienceCenter/renku/issues/3325)).
- Change icons in the navbar to use Bootstrap icons ([#2882](https://github.com/SwissDataScienceCenter/renku-ui/pull/2882), [#2763](https://github.com/SwissDataScienceCenter/renku-ui/issues/2763)).
- Handle errors from the getSessions query in the Dashboard ([#2903](https://github.com/SwissDataScienceCenter/renku-ui/pull/2903), [#2873](https://github.com/SwissDataScienceCenter/renku-ui/issues/2873)).
- Adjust dropdown menus with anchors nested in buttons ([#2907](https://github.com/SwissDataScienceCenter/renku-ui/pull/2907)).
- Update the workflows documentation link …
=> build: release 3.16.0

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Redesign landing page ([#2885](https://github.com/SwissDataScienceCenter/renku-ui/issues/2885), [#2890](https://github.com/SwissDataScienceCenter/renku-ui/issues/2890), [#2891](https://github.com/SwissDataScienceCenter/renku-ui/issues/2891), [#2895](https://github.com/SwissDataScienceCenter/renku-ui/issues/2895), [#2896](https://github.com/SwissDataScienceCenter/renku-ui/issues/2896), [#2897](https://github.com/SwissDataScienceCenter/renku-ui/issues/2897), [#2911](https://github.com/SwissDataScienceCenter/renku-ui/issues/2911), [#2912](https://github.com/SwissDataScienceCenter/renku-ui/issues/2912), [#2913](https://github.com/SwissDataScienceCenter/renku-ui/issues/2913), [#2925](https://github.com/SwissDataScienceCenter/renku-ui/issues/2925))
/deploy renku=2891-get-started-section …
=> build: release 3.17.0

client/src/features/versions/versions.api.ts, client/src/features/versions/versions.types.ts, client/src/help/HelpRelease.tsx, client/src/utils/constants/Repositories.ts
See: https://renku-ci-ui-2944.dev.renku.ch/help/release
/deploy
=> chore(client): add data-services version

client/src/features/session/components/options/StartNotebookServerOptions.module.scss
=> fix(client): fix URL session start option

CHANGELOG.md
Ooops, I forgot to add the breaking changes :speak_no_evil:
=> chore: mention the breaking changes

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Bugfix release to restore datasets functionality
/deploy
=> build: release 3.18.1

client/src/features/session/components/StartNewSession.tsx, client/src/features/session/components/options/StartNotebookServerOptions.tsx, tests/cypress/e2e/newSession.spec.ts
If the project is outdated, provide a better explanation and a link to the sessions page.
**Project can be updated with one click**
**Project requires more work to update**
Fix #2983 
/deploy
=> feat: improve feedback when starting sessions on outdated projects

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
=> build: release 3.19.0

client/src/help/Help.present.jsx, client/src/utils/helpers/url/Url.js
Realize a request from @rokroskar 
/deploy
=> feat: remove features section from help

client/src/landing/anonymousHomeNav.tsx, client/src/utils/constants/Docs.js
Fixes #2973.
* Add a link to the [Renku blog](https://blog.renkulab.io)
* Remove link to X (ex-Twitter)
/deploy
=> chore(client): update the footer links

.github/workflows/test-and-ci.yml, client/Dockerfile, client/package-lock.json, client/package.json, server/Dockerfile, server/package-lock.json, server/package.json, server/src/utils/middlewares/uploadFileMiddleware.ts
=> chore: upgrade NodeJs to version 20

client/src/features/project/GitLab.types.ts, client/src/features/project/projectGitLab.api.ts
Remove duplicate pagination type.
/deploy
=> chore(client): remove duplicate pagination type

client/docker-entrypoint.sh
The privacy policy and terms are not being correctly initialized; this fixes the problem.
/deploy renku=ciyer/2954-privacy-policy extra-values=ui.client.privacy.page.enabled=true
=> build: set the privacy statement and terms from configmap

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
=> build: release 3.20.0

client/src/styleguide/StyleGuide.jsx
=> chore(client): update the font part of the style guide

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Release 3.20.1
/deploy renku=release-0.48.x
=> build: release 3.20.1

client/src/features/session/sessions.api.ts, client/src/features/sessionsV2/sessionsV2.api.ts
WIP
/deploy #notest renku=build/new-sessions renku-data-services=build/new-sessions-demo renku-notebooks=pitch/compute-sessions-final
=> chore: final adjustments for Renku 2.0 sessions

client/package-lock.json, server/package-lock.json, tests/package-lock.json
=> build: grouped dependency update: follow-redirects

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Release support for v2 namespaces.
/deploy
=> build: release 3.22.0

client/run-telepresence.sh
This fixes an issue in the client telepresence script accidentally introduced here https://github.com/SwissDataScienceCenter/renku-ui/pull/3047
=> chore(client): fix telepresence script

.github/workflows/acceptance-tests.yml, client/src/App.jsx, client/src/components/navbar/NavBarItems.tsx, client/src/features/projectsV2/shared/WipBadge.tsx, client/src/features/secrets/LazySecrets.tsx, client/src/features/secrets/SecretDelete.tsx, client/src/features/secrets/SecretEdit.tsx, client/src/features/secrets/SecretNew.tsx, client/src/features/secrets/Secrets.tsx, client/src/features/secrets/SecretsList.tsx, client/src/features/secrets/SecretsListItem.tsx, client/src/features/secrets/secrets.api.ts, client/src/features/secrets/secrets.module.scss, client/src/features/secrets/secrets.types.ts, client/src/features/secrets/secrets.utils.tsx, client/src/features/session/components/StartNewSession.tsx, client/src/features/session/components/options/SessionUserSecrets.tsx, client/src/features/session/sessions.api.ts, client/src/features/session/sessions.types.ts, client/src/features/session/startSessionOptions.types.ts, client/src/features/session/startSessionOptionsSlice.ts, client/src/utils/helpers/EnhancedState.ts, client/src/utils/helpers/url/Url.js, tests/cypress/e2e/newSession.spec.ts, tests/cypress/e2e/secrets.spec.ts, tests/cypress/support/renkulab-fixtures/index.ts, tests/cypress/support/renkulab-fixtures/secrets.ts
Secrets in the UI -- feature branch
fix #3100
=> [ShapeUp] feat: add secrets

CHANGELOG.md, client/package-lock.json, client/package.json, client/src/features/secrets/Secrets.tsx, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
New UI release including the "User Secrets" feature.
=> build: release 3.24.0

client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/CodeRepositoryDisplay.tsx, client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/RepositoriesBox.tsx, client/src/features/ProjectPageV2/ProjectPageContent/DataSources/DataSourceDisplay.tsx, client/src/features/ProjectPageV2/ProjectPageContent/DataSources/DataSourceView.tsx, client/src/features/sessionsV2/SessionView/SessionView.tsx, client/src/styles/bootstrap/_custom_bootstrap_variables2.0.scss, tests/cypress/e2e/dashboard.spec.ts
PR to add ata sources in a v2 project.
Should be able to add, remove, see details, edit a data source.
=> feat: project page overview V2 (data sources)

client/src/components/buttons/Buttons.module.scss, client/src/features/ProjectPageV2/ProjectPageContent/DataSources/DataSourceView.tsx, client/src/features/ProjectPageV2/ProjectPageContent/ProjectInformation/ProjectInformation.tsx, client/src/features/ProjectPageV2/ProjectPageContent/Settings/ProjectSettings.tsx, client/src/features/projectsV2/api/projectV2.api.ts, client/src/features/projectsV2/api/projectV2.openapi.json, client/src/styles/bootstrap/_custom_bootstrap_variables2.0.scss
PR to include project page keywords
=> feat: project page v2 keywords

client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/CodeRepositoryDisplay.tsx
=> feat: update repository box with provider metadata

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
/deploy renku=build/custom-culling-times
=> build: release 3.25.0

client/src/features/projectsV2/api/namespace.api.ts, client/src/features/projectsV2/api/namespace.openapi.json, client/src/features/projectsV2/fields/AddGroupMemberModal.tsx
Add the new roles to the UI that were added to the backend.
=> UI changes to match new group auth model

client/src/features/projectsV2/api/namespace.api.ts, client/src/features/projectsV2/api/namespace.openapi.json, client/src/features/projectsV2/fields/AddGroupMemberModal.tsx
https://github.com/SwissDataScienceCenter/renku-ui/pull/3137 got lost in a rebase, bring it back
=> Reintroduce a commit that was lost in a rebase

.github/workflows/acceptance-tests.yml
=> tests: run acceptance tests in parallel

CODING_GUIDELINES.md
This adds details on classes/styles that we discussed offline and haven't translated into guidelines yet.
=> docs: add more guidelines for styling

client/src/features/connectedServices/ConnectedServicesPage.tsx
=> chore: small updates to the connected services page

client/src/features/ProjectPageV2/ProjectPageContainer/ProjectPageContainer.tsx, client/src/features/ProjectPageV2/ProjectPageContent/ProjectInformation/ProjectInformation.tsx, client/src/features/ProjectPageV2/ProjectPageContent/Settings/ProjectDelete.tsx, client/src/features/ProjectPageV2/ProjectPageContent/Settings/ProjectSettings.tsx, client/src/features/ProjectPageV2/ProjectPageHeader/ProjectPageHeader.tsx, client/src/features/dashboardV2/DashboardV2.tsx, client/src/features/dashboardV2/DashboardV2Sessions.tsx, client/src/features/projectsV2/list/GroupList.tsx, client/src/features/projectsV2/list/ProjectV2List.tsx, client/src/features/projectsV2/new/GroupNew.tsx, client/src/features/projectsV2/new/ProjectV2New.tsx, client/src/features/projectsV2/show/GroupShow.tsx, client/src/features/projectsV2/show/ProjectV2EditForm.tsx, client/src/features/projectsV2/show/ProjectV2ShowByProjectId.tsx, client/src/features/projectsV2/show/groupEditForms.tsx, client/src/features/rootV2/NavbarV2.tsx, client/src/features/searchV2/components/SearchV2Results.tsx, client/src/features/sessionsV2/SessionsV2.tsx, client/src/routing/routes.constants.ts, client/src/utils/helpers/url/Url.js, tests/cypress/fixtures/projectV2/list-projectV2-post-delete.json, tests/cypress/fixtures/projectV2/update-projectV2-repositories.json
See #3052.
/deploy renku=master
=> refactor: deprecate Url.js for Renku 2.0 components

client/src/features/projectsV2/new/GroupNew.tsx, tests/cypress/e2e/groupV2.spec.ts, tests/cypress/fixtures/groupV2/create-groupV2.json
=> fix: redirect to group page after creation

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
=> Change bufix release 3.27.1 into a full release 3.28.0

client/src/features/ProjectPageV2/ProjectPageContent/Settings/ProjectSettings.tsx
PR to fix bug to update project keywords
/deploy
=> fix: update keywords

client/src/features/ProjectPageV2/ProjectPageContent/DataSources/DataSourceView.tsx, client/src/features/project/components/cloudStorage/CloudStorageModal.tsx, client/src/features/project/components/cloudStorage/cloudStorageModalComponents.tsx, client/src/features/project/utils/projectCloudStorage.utils.ts, client/src/features/sessionsV2/SessionStartPage.tsx, client/src/features/sessionsV2/startSessionOptionsV2.slice.ts, client/src/features/sessionsV2/startSessionOptionsV2.types.ts, client/src/features/sessionsV2/useSessionLaunchState.ts, tests/cypress/e2e/projectV2.spec.ts, tests/cypress/fixtures/cloudStorage/cloud-storage-with-secrets.json, tests/cypress/support/renkulab-fixtures/sessions.ts
/deploy renku=ciyer/release-0.53.2
=> Code refactoring + tests for starting v2 sessions with data sources

client/src/help/HelpRelease.tsx, client/src/utils/constants/Repositories.ts
=> feat: add search version to the release page

client/src/components/formschema/FormSchema.tsx, client/src/features/ProjectPageV2/ProjectPageContent/ProjectOverviewPage.tsx, client/src/features/searchV2/SearchV2.tsx
This makes the size of the side columns consistent throughout the application
/deploy
=> refactor: use consistent sizes for side columns

client/src/features/projectsV2/new/ProjectV2New.tsx, tests/cypress/e2e/navV2.spec.ts, tests/cypress/e2e/projectV2.spec.ts
This is a bundle of minor changes aimed to improve consistency across pages. Please read the following posts for the specific changes.
=> design - minor changes to improve consistenty across components

client/package-lock.json, server/package-lock.json, server/package.json
/deploy renku=ciyer/ui-3275-data-source
=> libraries updates

client/src/features/groupsV2/members/GroupV2MemberListDisplay.tsx, client/src/features/groupsV2/show/GroupV2Show.tsx, client/src/features/projectsV2/list/GroupList.tsx, client/src/features/rootV2/NavbarV2.tsx, client/src/features/usersV2/show/UserAvatar.tsx
A bunch of minor fixes before we merge the 2nd round of changes
/deploy
=> design - minor bugfixes to wrap up the 2nd round

client/src/App.css, client/src/components/Loader.module.scss, client/src/components/Loader.tsx, client/src/storybook/bootstrap/Loader.stories.tsx
Fix the bouncer implementation of the Loader.
P.S. We might want to refresh the bouncer, perhaps switching it with the Boostrap growing spinner
/deploy
=> fix: update bouncer Loader to make it compatible with V2

client/package-lock.json, client/package.json
Fixes the broken `test-storybook` test.
=> build: update playwright

.github/workflows/acceptance-tests.yml
=> chore: add dashboardV2 test

client/src/features/ProjectPageV2/ProjectPageContent/DataConnectors/ProjectConnectDataConnectorsModal.tsx, client/src/features/ProjectPageV2/ProjectPageContent/Settings/ProjectDelete.tsx, client/src/features/dataConnectorsV2/components/DataConnectorActions.tsx, client/src/features/dataConnectorsV2/components/DataConnectorModal/DataConnectorSaveCredentialsInfo.tsx, client/src/features/dataConnectorsV2/components/DataConnectorView.tsx, client/src/features/project/components/cloudStorage/AddStorageMountSaveCredentialsInfo.tsx, client/src/features/project/components/cloudStorage/CloudStorageModal.tsx, client/src/features/project/components/cloudStorage/cloudStorageModalComponents.tsx, client/src/features/projectsV2/fields/SlugFormField.tsx, client/src/features/secrets/Secrets.tsx, client/src/features/sessionsV2/SessionView/SessionView.tsx, client/src/features/sessionsV2/components/SessionModals/AddSession.tsx, tests/cypress/e2e/groupV2.spec.ts, tests/cypress/e2e/groupV2DataConnectorCredentials.spec.ts, tests/cypress/e2e/projectV2DataConnectorCredentials.spec.ts, tests/cypress/e2e/projectV2Session.spec.ts
* introduce validation to reject upper-case characters in slugs
* Convert references to "data source" -> "data connector"
* Update the data connector sidebar to be closer to latest design
* show the number of projects in the "delete data connector" dialog
* Minor improvements
/deploy renku-data-services=leafty/build-data-connectors renku-notebooks=leafty/feat-data-connectors
=> Clean up some leftovers in data connectors

CODING_GUIDELINES.md
=> chore: add async action coding guideline

client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/AddCodeRepositoryModal.tsx, client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/RepositoriesBox.tsx, client/src/features/dataConnectorsV2/components/DataConnectorModal/DataConnectorSaveCredentialsInfo.tsx, client/src/features/project/components/cloudStorage/AddOrEditCloudStorage.tsx, client/src/features/project/components/cloudStorage/AddStorageMountSaveCredentialsInfo.tsx, tests/cypress/e2e/projectV2.spec.ts, tests/cypress/e2e/projectV2setup.spec.ts
This PR removes the "Coming soon" features and changes the warning message about the per-user credentials to an info message.
/deploy
=> refactor: adjust messages

client/src/features/dashboardV2/DashboardV2.tsx, client/src/features/groupsV2/new/CreateGroupButton.tsx, client/src/features/groupsV2/new/GroupNew.tsx, client/src/features/groupsV2/settings/GroupSettingsMetadata.tsx, client/src/features/projectsV2/LazyGroupNew.tsx, client/src/features/projectsV2/new/CreateGroupButton.tsx, client/src/features/projectsV2/new/CreateProjectV2Button.tsx, client/src/features/projectsV2/new/GroupNew.tsx, client/src/features/projectsV2/new/ProjectV2New.tsx, client/src/features/projectsV2/new/projectV2New.slice.ts, client/src/features/rootV2/NavbarV2.tsx, client/src/features/rootV2/RootV2.tsx, tests/cypress/e2e/navV2.spec.ts
Use a modal for project and group creation
/deploy renku=release-0.61.0 extra-values=amalthea-sessions.deployCrd=false #notest
=> feat: use a modal for project and group creation

client/src/features/sessionsV2/SessionView/SessionView.tsx
=> fix: correct code repositories list in session offcanvas

client/.eslintignore, client/src/features/ProjectPageV2/ProjectPageContent/ProjectCopyButton.tsx, client/src/features/ProjectPageV2/ProjectPageContent/ProjectCopyTemplateInfo.tsx, client/src/features/ProjectPageV2/ProjectPageContent/ProjectOverviewPage.tsx, client/src/features/projectsV2/api/projectV2.api.ts, client/src/features/projectsV2/api/projectV2.enhanced-api.ts, client/src/features/projectsV2/api/projectV2.openapi.json, client/src/features/projectsV2/fields/ProjectOwnerSlugFormField.tsx, tests/cypress/e2e/projectV2.spec.ts, tests/cypress/fixtures/namespaceV2/list-namespaceV2.json, tests/cypress/support/renkulab-fixtures/projectV2.ts
Minimal interface for copying projects. To test:
- Go to any project
- Click the "Copy project" button
- Look at the result
- See that you can navigate back to the original project
/deploy
=> feat: form for copying a project (initial version)

client/.eslintrc.json, client/src/features/project/components/cloudStorage/projectCloudStorage.constants.ts, tests/cypress/e2e/projectSettings.spec.ts
PR to add sftp in DC storage list
/deploy renku-data-services=main renku-notebooks=andrea/add-polybox-switchdrive-config
=> feat: add sftp storage in shortlist DC

client/src/components/Logs.css, client/src/components/Logs.module.scss, client/src/components/Logs.tsx
=> fix: scope Logs component's styling

client/src/features/sessionsV2/DataConnectorSecretsModal.tsx
Fixes #3458.
Link for testing -> https://renku-ci-ui-3459.dev.renku.ch/v2/projects/flora.thiebaut/flora-test
/deploy
=> fix: do not show "Save credentials" to anonymous users

client/src/components/navbar/NavBarItems.tsx
PR to fix typo in main navigation
/deploy
=> fix: typo main nav Back Renku 1.0 to Back to Renku 1.0

.github/workflows/acceptance-tests.yml, .github/workflows/test-and-ci.yml, client/src/features/sessionsV2/session.constants.ts
Fix a typo, reported on Slack by Wes
/deploy
=> refactor: fix a typo in the description for session environment values

client/src/features/projectsV2/fields/UserSelector.tsx
As requested here https://www.notion.so/renku/Revise-copy-text-for-adding-members-to-projects-1990df2efafc80cba433eda128f9ece0
/deploy
=> chore: change placeholder text for user

client/package-lock.json, client/package.json, server/package-lock.json, server/package.json, tests/package-lock.json, tests/package.json
A bug in how pretty-quick finds the git directory was fixed in 3.3.0:
https://github.com/prettier/pretty-quick/pull/183
=> build: update pretty-quick

.github/workflows/acceptance-tests.yml, .github/workflows/cleanup-old-deployments.yml, .github/workflows/github-project.yml, .github/workflows/prepare-release.yml, .github/workflows/test-and-ci.yml
This PR is similar to https://github.com/SwissDataScienceCenter/renku/pull/3938.
/deploy renku=build/session-env-builders
=> chore: update all actions to use ubuntu-24.04

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml
This matches better what we suggest in the ["Contribute" wiki page](https://github.com/SwissDataScienceCenter/renku-ui/wiki/Contribute).
=> chore: update issues template

client/src/features/ProjectPageV2/ProjectPageContent/Settings/ProjectSettingsMembers.tsx, client/src/features/groupsV2/settings/GroupSettingsMembers.tsx
=> minor: move add member button to right

client/src/features/ProjectPageV2/ProjectPageContent/Settings/ProjectSettingsMembers.tsx, client/src/features/groupsV2/settings/GroupSettingsMembers.tsx
=> refine: update members lists

.github/workflows/acceptance-tests.yml
=> ci: remove unnecessary deploy variables

.github/workflows/acceptance-tests.yml
Closes #3597.
/deploy renku=release-0.66.0
=> ci: fix acceptance tests

client/src/features/dataConnectorsV2/components/DataConnectorModal/DataConnectorModalBody.tsx, client/src/features/projectsV2/fields/ProjectNamespaceFormField.tsx
=> fix: ensure project as a namespace is populated when creating a data connector

client/src/features/rootV2/RootV2.tsx, client/src/routing/routes.constants.ts, tests/cypress/e2e/groupV2.spec.ts, tests/cypress/e2e/projectV2.spec.ts
=> Redirect 'v2' urls to somewhere sensible

client/src/features/sessionsV2/SessionView/SessionView.tsx, tests/cypress/e2e/projectV2Session.spec.ts
Show links for auto starting sessions on the session details sidebar
/deploy
=> feat: show autostart links in the session view

client/src/features/ProjectPageV2/ProjectPageContent/DataConnectors/ProjectConnectDataConnectorsModal.tsx, client/src/features/dataConnectorsV2/api/data-connectors.api.ts, client/src/features/dataConnectorsV2/api/data-connectors.enhanced-api.ts, client/src/features/dataConnectorsV2/api/data-connectors.openapi.json
/deploy renku-data-services=main
This fixes the issue with linking data connectors currently on prod.
=> fix: find project data connectors when linking

client/src/features/dataConnectorsV2/components/DataConnectorModal/dataConnectorModalButtons.tsx, client/src/features/project/components/cloudStorage/cloudStorageModalComponents.tsx
=> fix: data connectors success alerts spacing

client/src/features/sessionsV2/SessionView/EnvVariablesCard.tsx, client/src/features/sessionsV2/SessionView/EnvVariablesModal.tsx, client/src/features/sessionsV2/SessionView/SessionView.tsx, client/src/features/sessionsV2/api/sessionLaunchersV2.generated-api.ts, client/src/features/sessionsV2/api/sessionLaunchersV2.openapi.json, tests/cypress/e2e/projectV2Session.spec.ts, tests/cypress/e2e/projectV2setup.spec.ts, tests/cypress/fixtures/projectV2/session-launchers-without-env-vars.json
/deploy renku=release-0.68.0  renku-data-services=main
=> Support for launcher env variables

client/src/features/sessionsV2/SessionStartPage.tsx, client/src/features/sessionsV2/SessionView/EnvVariablesModal.tsx, client/src/features/sessionsV2/StartSessionButton.tsx, client/src/features/sessionsV2/components/SessionLauncherButtons.tsx, client/src/features/sessionsV2/session.constants.tsx, client/src/features/sessionsV2/session.utils.ts
=> fix: make custom launch work

client/src/features/connectedServices/ConnectedServicesPage.tsx, client/src/features/connectedServices/ContactUsCard.module.scss, client/src/features/connectedServices/ContactUsCard.tsx
Closes #3455.
/deploy extra-values=ui.client.sessionClassEmailUs.enabled=true,ui.client.sessionClassEmailUs.email.to=nobody@example.renku.ch
=> feat: add contact us card in the integrations page

client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/CodeRepositoryDisplay.tsx, client/src/features/ProjectPageV2/ProjectPageContent/SessionSecrets/AddSessionSecretButton.tsx, client/src/features/ProjectPageV2/ProjectPageContent/SessionSecrets/SecretsMountDirectoryComponent.tsx, client/src/features/ProjectPageV2/ProjectPageContent/SessionSecrets/SessionSecretActions.tsx, client/src/features/groupsV2/fields/AddGroupMemberModal.tsx, client/src/features/groupsV2/fields/EditGroupMemberModal.tsx, client/src/features/groupsV2/new/GroupNew.tsx, client/src/features/projectsV2/fields/AddProjectMemberModal.tsx, client/src/features/projectsV2/fields/EditProjectMemberModal.tsx, client/src/features/projectsV2/new/ProjectV2New.tsx, client/src/features/secretsV2/ReplaceSecretValueModal.tsx, client/src/features/sessionsV2/SessionView/EnvVariablesModal.tsx, client/src/features/sessionsV2/components/SessionModals/NewSessionLauncherModal.tsx
Pr to add minor changes
- Added missing icons to modal titles where applicable.
- Fixed missing space between icon and title in modal headers.
/deploy
=> chore: add missing icons and spacing in modal titles

client/src/components/Logs.tsx, client/src/components/modal/ScrollableModal.module.scss, client/src/features/ProjectPageV2/ProjectPageContent/DataConnectors/ProjectConnectDataConnectorsModal.tsx, client/src/features/ProjectPageV2/ProjectPageContent/Documentation/Documentation.module.scss, client/src/features/ProjectPageV2/ProjectPageContent/Documentation/Documentation.tsx, client/src/features/admin/AddManyUsersToResourcePoolButton.tsx, client/src/features/admin/UpdateResourceClassButton.tsx, client/src/features/dataConnectorsV2/components/DataConnectorModal/index.tsx, client/src/features/groupsV2/new/GroupNew.tsx, client/src/features/project/components/cloudStorage/CloudStorageModal.tsx, client/src/features/projectsV2/new/ProjectV2New.tsx, client/src/features/session/components/AboutSessionModal.tsx, client/src/features/session/components/ResourcesSessionModal.tsx, client/src/features/sessionsV2/SessionView/EnvVariablesModal.tsx, client/src/features/sessionsV2/components/SessionModals/ModifyResourcesLauncher.tsx, client/src/features/sessionsV2/components/SessionModals/UpdateSessionLauncherMetadataModal.tsx, client/src/features/sessionsV2/components/SessionModals/UpdateSessionLauncherModal.tsx
Closes #3544.
Set max-height to `75vh` on the `<ScrollableModal>` component and use this component for all scrollable modals.
/deploy #legacy
Supersedes #3679.
=> refactor: set max-height to 75vh on scrollable modals

client/src/features/session/components/StartSessionProgressBar.tsx
The product team asked for a different copy text for the initial phase of the session start
/deploy
=> refactor: change copy text for loading containers

.github/workflows/acceptance-tests.yml, .github/workflows/test-and-ci.yml
Closes #3782.
Tested teardown here -> https://github.com/SwissDataScienceCenter/renku-ui/actions/runs/16775927286/job/47501922724?pr=3784
/deploy extra-values=enableV1Services=false
=> chore: update CI deployments

client/src/features/dashboardV2/HelpV2.module.scss, client/src/features/dashboardV2/HelpV2.tsx, client/src/styles/renku_additional_classes.scss
/deploy extra-values=enableV1Services=false
=> refactor: add background on hover on the help page cards

client/src/features/connectedServices/ConnectedServicesPage.tsx, client/src/features/connectedServices/connectedServices.utils.ts
See: https://github.com/SwissDataScienceCenter/renku-data-services/pull/979
(do not deploy)
=> fix: update GitHub provider to support Enterprise Server

client/src/features/ProjectPageV2/ProjectPageContent/ProjectInformation/ProjectInformation.tsx, tests/cypress/e2e/projectV2.spec.ts, tests/cypress/support/renkulab-fixtures/projectV2.ts
=> minor: do not show inaccessible source of a copied project (#3829)

client/src/utils/constants/Docs.js
=> fix: update "Get Started" link in the footer bar

client/src/features/sessionsV2/SessionView/EnvironmentCard.tsx
=> fix: avoid environment description overflow
