npm-build.Dockerfile
package-lock is for node:6, so make was broken
=> Use node 6 for build

Dockerfile, docker-entrypoint.sh, package.json, src/utils/ServiceWorker.js
- Serve static ui files from a node server instead of using the webpack dev server when ui is running inside a docker container.
=> closes #139:

src/gitlab/client.js
Deployment of notebooks through jupyterhub has changed the deployment URL. Adapted to this.
=> Fix deployment URLs

.travis.yml, Makefile, helm-chart/chartpress.yaml, travis-deploy.sh
The crappy solution to this problem:
```
fatal: ambiguous argument '18b8ab0dc619...b8acc3c48c0c': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Traceback (most recent call last):
File "/home/travis/virtualenv/python3.6.3/bin/chartpress", line 11, in <module>
sys.exit(main())
File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/chartpress.py", line 207, in main
push=args.push,
File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/chartpress.py", line 78, in build_images
if commit_range and not path_touched(*paths, commit_range=commit_range):
File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/chartpress.py", line 43, in path_touched …
```
=> fix travis deploy

src/index.js
Alternative to PR #232. Same effect, but modifies our code, and leaves code supplied by create-react-app untouched. Fix #231.
=> Deactivate service workers as they cause problems elsewhere

src/file/File.container.js
Accept file paths beginning with or without a '/' when creating the deployment url.
=> Fix bug in file path of deployment url

README.rst
Just a small update to the README, mostly in order for the master branch to move away from a purely numeric short version of the commit sha...
=> Remove outdated reference to development branch from README.rst.

src/contribution/Contribution.container.js
Contribution creation referenced userState instead of the newer user object.
=> Fixed crash in contribution creation.

helm-chart/renku-ui/templates/_helpers.tpl
Quickfix, as the value from `renku` is `global.useHTTPS`.
=> Fixed template for http scheme

helm-chart/renku-ui/templates/NOTES.txt, helm-chart/renku-ui/templates/_helpers.tpl, helm-chart/renku-ui/templates/deployment.yaml, helm-chart/renku-ui/templates/ingress.yaml, helm-chart/renku-ui/templates/service.yaml
Rename renku-ui --> ui in helm chart templates to be consistent with other services.
=> Rename service in templates

src/gitlab/client.js
Get access level for a project not only from project but also from group permissions.
Closes #254.
=> Group access level for project

.travis.yml
travis deploy failing due to incompatibility between chartpress and new version of ruamel.yaml
=> ci: fix failing travis deploy

src/project/Project.present.js
Fix an error that was occurring when navigating directly to the files tab without previously having loaded all the data (for example when hitting the reload button or during integration tests).
=> Fix bug that leads to integration test failure

public/config.json, src/ku/Ku.js, src/model/Model.js, src/project/Project.js, src/project/Project.present.js, src/utils/UIComponents.js
Fix #217.
There are two forms that needed validation: "New Project" and "New Ku". Project uses the Model infrastructure, Ku uses Redux directly. I implemented lightweight solutions in each case: the project defers validation to the model, the ku does validation in the UI directly. I did not want to implement anything very generic yet, since we have only two examples to draw from. Once we have a few more, we can implement more generic validation handling.
=> Introduce form validation

helm-chart/renku-ui/values.yaml
Fix default values
This is likely causing `helm` issues.
```
Error: UPGRADE FAILED: render error in "renku/charts/renku-ui/templates/ingress.yaml": template: renku/charts/renku-ui/templates/ingress.yaml:1:14: executing "renku/charts/renku-ui/templates/ingress.yaml" at <.Values.ingress.enab...>: can't evaluate field enabled in type interface {}
```
=> Fix ingress in default values

src/App.js
clicking `Profile` fills the address bar with the correct URL but does not actually take the browser there... 🤔 ?
closes #276
=> set Profile -> keycloak user profile page

run-telepresence.sh
Killing telepresence can leave the swapped k8s deployment broken. We therefore run a shell and manually start the dev server which can be killed followed by gracefully exiting telepresence.
=> Manually start dev server inside telepresence shell

package-lock.json, package.json
We use npm-run-all to build css before running the app in development mode. The version we were using depends, through ps-tree, on the event-stream package which has been compromised.
- https://github.com/indexzero/ps-tree/pull/34
- https://github.com/dominictarr/event-stream/issues/116
- https://github.com/dominictarr/event-stream/issues/115
Upgrading to the latest npm-run-all fixes this issue.
=> Remove dependency on compromised flatmap-stream package.

src/api-client/test-client.js, src/landing/Landing.js, src/landing/Landing.present.js, src/landing/Landing.state.js, src/landing/NavBar.js, src/project/list/ProjectList.container.js, src/project/list/ProjectList.present.js, src/project/list/ProjectList.state.js, src/project/list/ProjectList.test.js, src/utils/quicknav/QuickNav.container.js, src/utils/quicknav/QuickNav.present.js, src/utils/quicknav/QuickNav.style.css
* The QuickNav jump function is restricted to member and starred projects. These are cached, so display of results is immediate.
* QuickNav also allows searching for projects.
Fix #353.
=> QuickNav jump improvements and support for searching for projects

src/api-client/errors.js, src/api-client/index.js, src/api-client/project.js, src/model/RenkuModels.js, src/project/new/ProjectNew.container.js, src/project/new/ProjectNew.present.js
The user now gets an alert when some errors occur while creating a new project. This addresses #387 as well as other generic errors.
The "Create" button is also disabled after the first click until a response comes from the API, and a Loader is displayed in the meanwhile.
=> Adding new project now provides an alert when some errors occurs

src/App.css, src/App.js, src/help/Help.container.js, src/help/Help.present.js, src/help/index.js, src/landing/NavBar.css, src/landing/NavBar.js
Added a new help page with 4 tabs, with routing path `/help*`.
Re-implemented the footer as a `NavBar` and moved to `/landing` folder along with the top navbar.
Added links to help page in the footer and in the user menu.
closes #382
=> Added help page, moved and adjusted footer.

src/api-client/index.js, src/file/File.present.js, src/notebooks/Notebooks.container.js, src/notebooks/Notebooks.present.js
This addresses the bug #370 (It solves the problem following the instructions that @ableuler describes in the bug) This is a way of "fake-replicating" the bug so we can't be 100% sure that it will work, but it should.
=> Logout and redirect to login when jupyterhub token expires

src/api-client/index.js, src/api-client/user.js, src/project/Project.js, src/project/Project.present.js
Users who were not logged in were mistakenly redirected to login page even when they shouldn't (e.g. navigate thorough a public project).
Preview available at https://lorenzotest.dev.renku.ch
Example of public repo: https://lorenzotest.dev.renku.ch/projects/72/
If login is triggered, be sure to clean browser cache/cookies
=> fixed navigation for anonymous users

src/api-client/graph.js, src/api-client/index.js, src/api-client/project.js, src/api-client/utils.js, src/model/RenkuModels.js, src/project/Project.css, src/project/Project.js, src/project/Project.present.js, src/project/Project.state.js, src/project/new/ProjectNew.present.js, src/utils/UIComponents.js
=> UI for configuring KG integration

src/project/new/ProjectNew.present.js
closes #417 
The warning now appears also for internal projects and it should be more clear that it's not an error.
A link to the lineage page in the docs is provided.
This is the "new project" page
Temporarily test link: https://lorenzotest.dev.renku.ch/
It's a bit fancy compared to the previous solution, let me know if you like it or not.
=> Knowledge graph warning for new projects fixed

src/file/File.container.js, src/file/File.present.js
The `Tooltip` displayed by `LaunchNotebookButton` is crashing the UI when an anonymous user tries to preview a notebook file, as pointed out by @cchoirat . This PR fixes this problem by attaching the `Tooltip` to `LaunchNotebookButton` button instead of the plus icon on top NavBar which is not available when not logged id.
It also fixes the message
* Anonymous users can't start a Jupiter server, should be prompted to log in
* Logged users can now start Jupiter server from the `Notebook Servers` tab, not from the plus icon
=> fix tooltip positioning

package-lock.json, package.json, src/api-client/project.js, src/api-client/repository.js, src/file/File.container.js, src/file/File.present.js, src/file/Lineage.container.js, src/file/Lineage.present.js, src/file/Notebook.js, src/project/Project.js, src/project/Project.present.js, src/project/Project.state.js, src/project/filestreeview/FilesTreeView.js, src/project/filestreeview/treeviewstyle.css, src/utils/Encoding.js
This is to address the issue #400, at the moment it looks like this... 
Some things will need to be addressed after this PR is merged:
- See if we can fetch LFS Files or if we can know if a file is from GIT LFS
- Being able to change between branches (now it shows master only)
- Add new formats of files to preview
- Better integration with launching JupyterLab
=> File display

package-lock.json, package.json, src/App.js, src/api-client/index.js, src/api-client/notebook-servers.js, src/api-client/test-client.js, src/model/RenkuModels.js, src/notebooks/Notebooks.container.js, src/notebooks/Notebooks.present.js, src/notebooks/Notebooks.state.js, src/notebooks/Notebooks.test.js, src/project/Project.js, src/project/Project.present.js, src/project/Project.state.js, src/utils/Media.js
closes #415 
The notebook servers APIs query the new endpoint `notebooks/servers` and the data are used in both the project page `Notebook Servers` and the `Notebooks` page in the top navbar.
@rokroskar once this PR is approved the UI won't use the `notebooks/user` endpoint anymore, neither the UI part from the `renku-notebook` project
Preview: https://lorenzotest.dev.renku.ch
=> New notebook servers page and servers endpoint

src/api-client/index.js
Closes #424 
Preview available at https://lorenzotest.dev.renku.ch
Please try it to be sure the problem solved by #404 doesn't come back.
If you wan't to play with rancher to try to generate 401 responses, the `lorenzotest` namespace is in the `UI-team` folder.
=> fix jupyterhub API

src/project/Project.state.js
One line fix so project files trees get fetched only once.
Closes #449
=> FilesTree in project get's fetched only once now. Bugfix.

src/api-client/graph.js, src/file/Lineage.container.js, src/file/Lineage.present.js, src/model/RenkuModels.js, src/project/Project.js, src/project/Project.state.js
Closes #451 
While browsing a project's `File` tab, the graph is now displayed only if the lineage is available. Otherwise, the user gets a notification depending on the current status:
* Project needs to be indexed
* Project indexing has just been re-triggered
* Indexing is currently ongoing
This can be tested here https://lorenzotest.dev.renku.ch
There is an annoying issue at the moment: when a project is forked on Gitlab and the webhook is created, no Push Event is returned by Gitlab, therefore the knowledge graph is never built correctly. (TODO: Add reference to SwissDataScienceCenter/renku-graph issue)
=> Verify lineage availability when browsing files

src/file/Lineage.present.js
The node highlighted in bold on the lineage graph is sometimes wrong when there are several files with similar names, like `data`, `data1`, `dat`.
This fixes the issue. Example:
Before: https://dev.renku.ch/projects/113/files/lineage/data2/
Later: https://lorenzotest.dev.renku.ch/projects/113/files/lineage/data2/
=> wrong node highlited in lineage visualization

.eslintrc.json, package-lock.json, package.json
The linter crashes on any files with `import React, { Component } from 'react'` with the following error:
> eslint cannot read property 'range' of null
Deleting and re-creating `package-lock.json` fixed it. This includes also a couple of minor fixes to avoid pm warnings.
Please try to delete your `node_modules` folder and re-install it through `npm` when reviewing this PR.
=> fix eslint error

src/utils/Time.js, src/utils/Utils.test.js
Should we have a standardized way to display exact dates? I have created a few helper functions to simplify handling the ISO date format returned by APIs. I will use this in #416 to display commit dates.
Feel free to disagree with this PR or to suggest alternatives.
=> time helper functions

src/api-client/project.js, src/model/RenkuModels.js, src/project/Project.present.js, src/project/new/ProjectNew.container.js, src/project/new/ProjectNew.present.js
Adds the possibility to opt-out from Knowledge Graph when creating a new project with `private` visibility.
Test available at https://lorenzotest.dev.renku.ch
=> opt-out from knowledge graph for new private projects

src/project/Project.js, src/project/Project.state.js
The intervals of the notebook server start at 3000,
when the servers are all ready the polling is set to 6000
if they are unready again for reason they are seat to 3000 again.
On top of that, if there are no servers all the polling stops.
=> fix: the interval of the notebook server is lowered when servers are ready

src/api-client/project.js, src/project/Project.js, src/project/Project.state.js
The project's notebook URL computation generates an API call (before #460, it was computed locally) that results in a `401` response for anonymous users, which triggers the authentication. There is no need to compute that URL for users who can't possibly have a running notebook server.
To reproduce: open any public project on dev as anonymous user (e.g. https://dev.renku.ch/projects/72). This will trigger authentication due to a call to `https://dev.renku.ch/api/notebooks/.../f6404d191d8067eda7a7083efdf57e4b7f56922b`
=> fix(notebook): avoid to create notebook url for anonymous users

src/file/File.container.js
Small fix, now the files with the format .ran.ipynb can be previewed.
I did a small change in the way the function gets the format of a file.
Closes #483
=> fix: the files with format ran.ipynb can be previewed now

src/project/Project.css, src/project/Project.present.js
A label was aded to show the project visibility. 
It looks as follows:
=> feat: project visibility label added to project page

package-lock.json, package.json, src/api-client/notebook-servers.js, src/model/Model.js, src/notebooks/Notebooks.container.js, src/notebooks/Notebooks.present.js, src/notebooks/Notebooks.state.js, src/notebooks/Notebooks.test.js, src/notebooks/index.js, src/project/Project.js, src/project/Project.present.js, src/project/Project.state.js, src/utils/Time.js
Add the possibility to start a Jupyterlab server form any branch and commit
If the server is already running, the user can connect directly from the launch page.
A preview is available here: https://lorenzotest.dev.renku.ch/
_It already includes full URL paths from this PR: SwissDataScienceCenter/renku-notebooks#181_
---
closes #416 
addresses https://github.com/SwissDataScienceCenter/renku/issues/437
=> feat(notebook): start jupyterlab servers from any branch and commit

src/App.js, src/api-client/notebook-servers.js, src/model/RenkuModels.js, src/notebooks/Notebooks.container.js, src/notebooks/Notebooks.present.js, src/notebooks/Notebooks.state.js, src/project/Project.js, src/project/Project.present.js, src/project/Project.state.js
This is the UI adaptation to handle the API responses from SwissDataScienceCenter/renku-notebooks#177 (requires also SwissDataScienceCenter/renku-notebooks#187)
A preview is available here: https://lorenzotest.dev.renku.ch
At the moment we have lost the distinction between "starting" and "stopping" servers, we only mark them as "pending". This may be acceptable, but the UI shows that after the stop API is invoked, the server will still be considered "ready" for a while.
An idea to improve this could be using an extra annotation to save in the pod the information that the stop command has been invoked by the user, then returning it in the `/servers` endpoint in the status.
=> Update Notebooks components

src/app-state/UserState.js, src/project/list/ProjectList.container.js, src/project/list/ProjectList.present.js, src/project/list/ProjectList.state.js, src/project/list/ProjectList.test.js
With dropdown in project search to order projects by name, created date, and updated date. 
With sorting included (Ascending - Descending) --> I'm not sure this button icons are the best, if you have better ones i can change them.
=> feat: dropdown in project search to order projects

src/App.js, src/not-found/NotFound.container.js, src/not-found/NotFound.present.js, src/not-found/index.js, src/project/Project.present.js
Basic "404 page not found" added to the UI.
The style of the previous "Project not found" has been aligned too.
closes #488
=> feat: add basic 404 page not found

src/api-client/project.js, src/model/RenkuModels.js, src/project/Project.js, src/project/Project.present.js, src/project/Project.state.js, src/project/fork/ProjectFork.container.js, src/project/fork/ProjectFork.present.js, src/project/fork/index.js
New button added to fork a project in the project page.
When the button is clicked a modal opens and gives the user the option to choose a namespace (like in the project creation) --> we could also give the user the option to set a new name for the forked project.
The submit action is still not finished, it throws some errors (i think the project is not forked properly or maybe we need to do a first commit and set some other things like in the project creation) 
==> I did this before going on holidays and a bit in a rush, I reused lot's of the code of the create project and it could happen that there are redundant things or things that are not right.
=> feat: button to fork a project

src/api-client/project.js
There was an error on the JSON body sent on the POST request, it was set to "namespace_id" but it should have been "namespace".
=> fix: fork to project works for groups

src/notebooks/Notebooks.state.js
Avoid overlapping queries to the `/servers` endpoint by implementing a very basic semaphore logic.
The first commit comes from #498, merge after that.
=> Prevent multiple simultaneous calls to the servers endpoint

src/api-client/notebook-servers.js, src/notebooks/Notebooks.state.js
#498 introduced a bug in "Notebook.state" since the polling actions are never interrupted when needed
-- e.g. when the query to the servers endpoint is skipped or the list of servers is still updating.
To test it, open the debug console while trying to launch a new notebook from any project (i.e. in the `launchNotebook` page). Without this PR, every now and then, the console will log an error (it may take long). When applying this PR, the chain of functions called in "Notebooks.state" to test for running notebooks is interrupted when needed
=> fix(notebook): fix errors introduced by #498

src/api-client/project.js, src/project/fork/ProjectFork.container.js, src/project/fork/ProjectFork.present.js
The pipeline starts now without creating a trigger.
To test fork a project and go to CI/CD => pipelines in gitlab and you will see that after forking a project there is a pipeline running. 
For some reason it fails for old projects. I think in the future we can after redirect offer the option to restart failed pipelines (Like for Knowledge Graph).
Closes #511
=> feat: pipeline starts without creating a trigger

src/model/RenkuModels.js, src/notebooks/Notebooks.container.js, src/notebooks/Notebooks.present.js, src/project/Project.present.js, src/project/Project.state.js, src/utils/HelperFunctions.js, src/utils/Utils.test.js
Add support for the autosaved branches features introduced by SwissDataScienceCenter/renku-notebooks#189 by separating the renku/autosave branches from the
user-created branches and showing a warning to the user when starting a new JupyterLab server from a
branch/commit combination with available autosaved content.
How to test it:
A preview is available at https://lorenzotest.dev.renku.ch
* Start a new JupiterLab server for any of your projects
* Connect to the server and do some work -- creating a new empty file or modifying an existing one is enough
* Stop the server from the Notebooks table.
If you now try to start again another server from the same branch/commit combination, a popup will warn you about existing autosaved data.
If you try to replicate the same steps in …
=> feat(notebook): add support for autosaved branches

src/file/Lineage.present.js
When a user clicks on a node of type "blob" (file) the user is redirected to the lineage of the clicked file.
This addresses the first point of the issue #256
=> feat: user is redirected on click to a node

src/landing/NavBar.js
Navbar for anonymous users shows a link to the project list and the search box, as it already happens for logged in users.
fix #426
=> fix: add elements to anonymous user navbar

src/project/Project.present.js
The UI now checks the user privileges before rendering any notebook-related components.
This fixes #510 and improves also the output for the "Notebook Servers" tab by avoiding any useless call to `/servers` API.
A preview is available at https://lorenzotest.dev.renku.ch/
To test it, try accessing https://lorenzotest.dev.renku.ch/projects/8/launchNotebook
=> fix(notebook): check user privileges before rendering notebook components

src/file/Lineage.css, src/file/Lineage.present.js
This addresses partially the issue #502
Nodes that represent workflows are now diamond shaped and green and nodes that are files are purple. Files that have .py .r .ipynb .sh have a black border.
The graph is centred and small improvements in layout where also done.
=> feat: conditional nodes styling

src/file/Lineage.css, src/file/Lineage.present.js
The user can use the mouse to zoom in and out of the graph and drag the graph in the viewport. 
Closes #534
=> feat(lineage): user can zoom in and out of the graph

src/api-client/notebook-servers.js
fix #540
The API is now invoked with the proper `Content-Type` header.
How to test it: start a new notebook changing the "CPU request" parameter from `0.1` to `0.5`. Connect and type in a command window `printenv | grep CPU` to check if the value is correct.
Preview available at https://lorenzotest.dev.renku.ch
=> fix(notebook): fix launch server function

src/api-client/project.js, src/api-client/test-client.js, src/file/File.container.js, src/file/File.present.js, src/file/File.test.js, src/file/Lineage.present.js, src/project/Project.js, src/project/Project.state.js, src/project/filestreeview/treeviewstyle.css
The component `<LaunchNotebookButton>` was partially broken and a lot of obsolete code has not been removed.
This PR restores the Jupyter button functionality during the preview of a notebook in a project's File tab. Please mind that the status of the running notebook is still not updated realtime (will be addressed later).
Preview: https://lorenzotest.dev.renku.ch
How to test: open any notebook in the project's File View. If you are not logged in or you don't have enough permissions, you shouldn't see the Jupyter icon on the top right (https://lorenzotest.dev.renku.ch/projects/95/files/blob/notebooks/zhbikes-notebook.ipynb), otherwise you will see it with a popups message on mouse hover. By clicking, you will open the notebook in Jupyter or go to the "start server" page if no server is …
=> fix(notebook): restore link between notebook files and Jupyter server

src/api-client/graph.js
Makes lineage API parameters mandatory to comply with SwissDataScienceCenter/renku-graph#115
Testing this requires to use the aforementioned PR (images for `renku-knowledge-graph`: lorenzocavazzitech/knowledge-graph:0.6.0-8b454cc and `renku-graph`: lorenzocavazzitech/webhook-service:0.6.0-8b454cc).
Try to open any lineage. The current UI gets stuck at the "Loading" message. The PR solves this problem.
=> fix lineage mandatory parameters

src/api-client/notebook-servers.js, src/api-client/project.js, src/notebooks/Notebooks.container.js, src/notebooks/Notebooks.present.js, src/notebooks/Notebooks.state.js, src/project/Project.present.js
This PR adapts the UI to the new notebook APIs as defined in SwissDataScienceCenter/renku-notebooks#188
It addresses the first point of #518. The main benefit of this URL change is a possible simplification of the UI logic, but that will be addressed in a subsequent PR.
How to test: create a chartpress image from the renku-notebooks PR and update the renku deployment -- or simply update the k8s services images with `lorenzocavazzitech/renku-notebooks:0.5.0-521877a` for `<namespace>-renku-notebooks` and  `lorenzocavazzitech/jupyterhub-k8s:0.5.0-521877a` for `hub`. It won't be possible to start new notebooks without this PR applied.
Preview available at https://lorenzotest.dev.renku.ch
=> refactor(notebook): invoke notebook apis according to new url structure

src/project/Project.present.js, src/project/shared/index.js
Fix bug that prevents editing of project metadata.
Fix #427.
=> fix: edit project metadata bug

src/api-client/test-client.js
fix the following error: UnhandledPromiseRejectionWarning: TypeError: this.client.<functionName> is
not a function
how to test it: run `npm test` on all tests (parameter `a`) and verify that the aforementioned error doesn't appear anymore. It used to happen with the functions `getProjectTemplates` and `getNotebookServerOptions`
=> test: fix non blocking errors in tests

package-lock.json, package.json, src/App.js, src/api-client/notebook-servers.js, src/notebooks/Notebooks.container.js, src/notebooks/Notebooks.present.js, src/notebooks/Notebooks.state.js, src/notebooks/Notebooks.test.js, src/notebooks/index.js, src/project/Project.present.js
Improves performances by transferring all the filtering logic to the backend. Refactors components
in Notebooks pages to simplify re-using parts of the code.
How to test it: ideally there aren't big differences at the user's level. The best way to test is by playing with notebooks, especially
- go in any own project in the `Notebook servers` tab and try to start, connect to and stop a notebook
- go in the global `Notebook` page and check if the information is accurate
Preview at: https://lorenzotest.dev.renku.ch
fix #518
=> perf(notebooks): move servers filtering to backend

docker-entrypoint.sh, helm-chart/renku-ui/templates/deployment.yaml, helm-chart/renku-ui/values.yaml, run-telepresence.sh, src/App.js, src/api-client/index.js, src/api-client/project.js, src/index.js, src/project/new/ProjectNew.container.js
Addresses #561 
I created the branch 'test-branch-manifests' inside our templates project for testing reasons.
In case there is no branch and url configured it fails. Specifications say that default should be master but if there is no URL it will fail anyway unless we want to set the url from our templates project as default along with master.
I had to modify also my public/config.json to make it work, i'm not sure something is missing in the configuration I made. My config file looks like this now (i put it here because is an untracked file):
{
"BASE_URL": "https://virginia.dev.renku.ch",
"GATEWAY_URL": "https://virginia.dev.renku.ch/api",
"WELCOME_PAGE": "IyMgV2VsY29tZSB0byBSZW5rdSB0aHJvdWdoIHRlbGVwcmVzZW5jZQpTb21lIGRlcGxveW1lbnQtc3BlY2lmaWMgaW5mb3JtYXRpb24gd2lsbCBiZSByZWFkIGZyb20gdGhlIH …
=> feat(templates): the  user can configure a url and ref to fetch templates from

src/notebooks/Notebooks.container.js
Components including `<input type="range">` html elements in the notebook options selection were not working correctly anymore because the target value was not properly selected.
This PR fixes it restoring the possibility to choose the number of GPU for a notebook -- only for renku deployments where this is allowed like `limited`.
fix #574
=> fix(notebooks): pick correct value in notebook options range inputs

src/api-client/index.js, src/api-client/pipeline.js, src/api-client/project.js, src/api-client/test-client.js, src/model/RenkuModels.js, src/notebooks/Notebooks.container.js, src/notebooks/Notebooks.present.js, src/notebooks/Notebooks.state.js, src/project/Project.js, src/project/Project.present.js, src/project/Project.state.js, src/utils/UIComponents.js
When starting a new interactive environment, the UI now checks for the Docker image availability.
Behind the scenes, only the GitLab pipelines are effectively checked -- technically it is still possible that the pipeline containing the image build process has correctly terminated but the image is not available anymore in the Docker repository.
How to test: open a project, create a new commit and open the "start new server" page just after. Verify that the "Docker Image" badge says something is ongoing and is updated later.
It's possible to play a bit with the relevant pipeline by opening it in GitLab and start/stop/re-run it. The information should be updated almost immediately.
fix #495
=> feat(notebooks): check docker image related pipeline before starting a new server

src/notebooks/Notebooks.present.js, src/utils/Time.js, src/utils/Utils.test.js
The commit datetime showed to the user while launching a new notebook is now local timezone aware.
fix #571
=> refactor: add local timezone aware date format

src/project/Project.present.js
Notebook servers tab is now displayed also to users without sufficient permissions for the project.
The page contains an alert with meaningful information about what the user can do.
fix #565
=> feat(notebooks): notebook servers for anonymous users

src/api-client/project.js, src/dataset/Dataset.container.js, src/dataset/Dataset.present.js, src/dataset/index.js, src/project/Project.css, src/project/Project.js, src/project/Project.present.js, src/project/Project.state.js, src/project/datasets/DatasetsListView.js
This addresses #525 .
There is now a dataset explorer that is similar to the file explorer but for datasets. 
This is "WIP" for two reasons:
1) We are getting the datasets info from the yml file in .renku instead of the KG.
2) This only works for datasets imported with the latest renku version. The older versions have the files in the dataset in a different way than the new ones so this makes everything break. Also, the older version for data import don't include so much data.
Test Deployment:
https://virginiatest.dev.renku.ch/projects/412/datasets/cc0c4e5f87d7411485c77577b0addca2/
Preview:
=> WIP feat(datasets): with datasets explorer

src/project/Project.css, src/project/Project.js, src/project/Project.present.js
There is a tab for datasets inside project overview tab, there still needs to be a button that redirects the user to the detailed overview of the dataset. It still needs to be decided what information exactly we want to display.
Addresses #525
=> feat(datasets): tab for datasets inside project overview

src/App.js, src/api-client/ku.js, src/api-client/project.js, src/ku/Ku.js, src/landing/NavBar.js, src/merge-request/MergeRequest.container.js, src/notebooks/Notebooks.container.js, src/notebooks/Notebooks.present.js, src/notebooks/Notebooks.state.js, src/project/Project.js, src/project/Project.present.js, src/project/Project.state.js, src/project/list/ProjectList.present.js, src/utils/HelperFunctions.js
This addresses #167 
Old URLs that where using the project id will be rerouted to the corresponding namespace/project-name url is possible.
There could be some edge cases that overlap with the new routing, priority will be given to the new schema, i think this edge cases don't exist in reality in renku.
Test Deployment:
https://virginiatest.dev.renku.ch/
Since this traverses all of the projects routing I would appreciate you testing it, if you find some error let me know :)
=> refactor: project url uses namespace and name instead of id

src/notebooks/Notebooks.container.js
Selecting a different branch now automatically select the last available commit -- after the commit list is refreshed.
~Preview available here: https://lorenzotest.dev.renku.ch~
fix #588
=> feat(notebooks): always select the latest commit when changing branch

src/api-client/project.js, src/project/list/ProjectList.container.js, src/project/list/ProjectList.present.js, src/project/list/ProjectList.state.js, src/project/list/ProjectList.test.js
The user can search by user name and group name. 
Before reviewing the pr is important to understand that gitlab has big limitations on the search api, at some point this will have to be addressed differently.
It looks as follows:
Test deployment: https://virginiatest.dev.renku.ch/
Closes: #560
=> feat(projects): search by username and group

src/file/File.container.js, src/file/File.present.js, src/file/File.test.js, src/file/Lineage.present.js, src/file/index.js, src/notebooks/Notebooks.container.js, src/notebooks/Notebooks.present.js, src/project/Project.js, src/project/Project.present.js
The UI showed wrong feedback when trying to start a new interactive environment for projects without a `master` branch or without any branch/commit at all (note that 1 branch requires at least 1 commit, and also the other way around is also true).
This PR handles the 2 cases as follows:
* no branch named "master" --> another branch is selected
* no branch (and therefore no commit) --> the user is notified that at least 1 commit is necessary. Following the approach similar to #578, a few suggestions are provided to the user 
**How to test**:
1. create a project starting from the empty template, then go to the "Notebook servers" tab and click on "Start new server"
2. clone the project locally, add a branch with a name different from "master", create a commit and push to `origin`
fix #595
=> feat(notebooks): handle non-standard branches projects

src/api-client/repository.js, src/file/File.container.js, src/file/File.present.js, src/file/File.test.js, src/file/index.js, src/project/Project.js
Commit hash, with link to commit in github, commit message, commit author, and commit date/time has been added to the display.
It looks like 
Running on https://sekhartest.dev.renku.ch/ for testing.
Fix #487.
=> Display commit and timestamp information about the file in the file view

src/landing/NavBar.js
Closes #401 
I think the cleanest option for this is as @ciyer mentioned, opening a new tab.
The user might have to refresh after changing things but i don't see this as a major issue. Otherwise we might have to send key cloack a redirect link... i'm not sure that is possible.
=> fix(navbar): the key cloack user profile opens in a new tab

src/App.js, src/landing/NavBar.js, src/notebooks/Notebooks.present.js, src/project/Project.js, src/project/Project.present.js
I prefer to change the wording now before addressing the other routing/layout notebook related issues.
Note that the naming of `launchNotebook` route will be changed in #482 
fix #568
=> change wording: from jupyter notebooks to interactive environments

src/api-client/project.js
… it is (for projects that take longer).
I replaced some setTimer for setInterval, the spinner was running indefinitely since the algorithm inside setTimer doesn't run several times until the project is ready for the pipelines to run. The setInterval solves this problem.
Before: 
- Fork project
- Wait 3000ms
- If project ready -> run the pipeline and redirect
After
- Fork project
- Every 3000ms --> if project ready run the pipeline and redirect
=> fix(fork): the project wasn't being redirected after the fork and now

src/file/File.container.js, src/project/filestreeview/FilesTreeView.js
Context: there could be files of type "commit" inside the file tree of gitlab, we only have one example of this in the vom_natt project. 
Before when the user was clicking the file nothing was happening (because there was no link) and now the fileviewer tries to display the file:
=> fix(fileviewer): files with type commit have a preview now

src/api-client/project.js, src/project/fork/ProjectFork.container.js, src/project/fork/ProjectFork.present.js
There is a new field inside the project fork modal where the user can change the name of the forked project.
=> feat(fork): the user can change the name of the forked project

src/notebooks/Notebooks.container.js, src/notebooks/Notebooks.present.js, src/project/Project.js, src/project/Project.present.js
This PR integrates the "launch notebook" page into the new "Environments" tab, applying also minor changes to the layout according to #482. Please note that it doesn't filter/change the environment options (refer to the issue).
=> feat(environments): create environment route with sub-routes

src/App.js, src/file/File.container.js, src/file/File.present.js, src/file/File.test.js, src/index.js, src/model/GlobalSchema.js, src/model/Model.js, src/model/RenkuModels.js, src/model/index.js, src/notebooks/Notebooks.container.js, src/notebooks/Notebooks.present.js, src/notebooks/Notebooks.state.js, src/notebooks/Notebooks.test.js, src/project/Project.present.js
This PR starts the re-organization of the code to have a single redux store.
* creates a single global model that is instantiated in `src/index.js` and passed down as a property (`client` may be also merged there?)
* move environments schema to `RenkuModel` and add it as a sub-model `notebooks`
* convert `NotebooksModel` as `NotebooksCoordinator` and adapt the
container components
* adapt the test and fixes a couple of minor bugs
Adding the function `NotebooksCoordinator.reset` was needed because the state is not reset anymore when a component is instantiated and the functions were created without that in mind (e.g. the filters for the `/servers` query are stored in the state) -- this may be improved later.
How to test: try the pages where the components are used: global environments, …
=> move environments logic to a single global model

src/api-client/notebook-servers.js, src/notebooks/Notebooks.container.js, src/notebooks/Notebooks.present.js, src/notebooks/Notebooks.state.js, src/utils/HelperFunctions.js
This PR change the table layout of the environments table and adds a couple of extra options for non-running servers:
* show a popup containing kubernetes pod information
* allow force-stop
How to test: start one or more interactive environments, check the environment pages and try to force stop.
Projects that can't start correctly:
* https://lorenzotest.dev.renku.ch/projects/lorenzo.cavazzi.tech/slow-build
* https://lorenzotest.dev.renku.ch/projects/lorenzo.cavazzi.tech/failing-image
So far, I have not been able to re-produce a pure "error" state (any suggestion is welcome). Maybe the labeling should be tuned: I will try to identity "pending" states that should be labeled as "error".
fix #361, re #499
=> feat(environments): show more status data and allow force stop

src/project/fork/ProjectFork.container.js, src/project/fork/ProjectFork.present.js, src/project/new/ProjectNew.container.js, src/project/new/ProjectNew.present.js
Using `path` instead of `name` when dealing with namespaces seems a good solution to avoid users name personalization issues https://docs.gitlab.com/ee/api/namespaces.html
fix #635
=> fix: use path instead of name when working with namespaces

src/api-client/notebook-servers.js, src/model/RenkuModels.js, src/notebooks/Notebooks.container.js, src/notebooks/Notebooks.css, src/notebooks/Notebooks.present.js, src/notebooks/Notebooks.state.js, src/notebooks/index.js
This adds the possibility to fetch and show the kubernetes logs for each environment. In this first implementation, I used a simple modal to display logs. I know it's not one of @ciyer favorite solutions, we can discuss it and visualize them in a different way
Sadly, it's not possible to get logs during some spawn phases. This means that, usually, there aren't logs for hanging pods, making this addition less useful than expected.
Preview available at https://lorenzotest.dev.renku.ch/
How to test: start an environment, use the "get logs" button during any phase.
fix #414
=> feat(environments): show kubernetes log per server

.travis.yml
pin chartpress version to avoid using the new charts naming convention as defined here
https://github.com/jupyterhub/chartpress/pull/52/files#diff-1b186cf0a304f81b305251eb344e0c47R241
and ultimately avoid deploy issues like this https://concourse.dev.renku.ch/teams/renku/pipelines/renku/jobs/check-renku-ui/builds/471
=> ci: fix chartpress version

src/project/fork/ProjectFork.container.js, src/project/new/ProjectNew.container.js
On project creation, errors without a description were filtered out. This sometimes ended up in misleading error messages. This PR introduces the following
* include errors without description in the error message
* makes the message for users without project creation permission more understandable
* remove error message after changing any data
* fix a minor issue on error handling while forking a project
Testing requires an account with limited permission, like john.doe@mail.org
Log in and try to create a new project
fix #636
=> feat: handle limit-reached errors on new project creation

src/model/Model.js, src/model/Model.test.js, src/notebooks/Notebooks.state.js
Allow using any command available from the immutability-helper library https://github.com/kolodny/immutability-helper#available-commands
This enables to use `.setObject()` to perform atomic updates to the store even when trying to remove object attributes or array items, without forcing to invoke `.set()`. A few examples of ` notebooks` model changes are provided in the second commit.
Unexpected behavior may happen when trying to update attributes starting with `$`, but this doesn't look to be a big deal.
A bit tricky, it requires to run the PR through telepresence
* Start 2 interactive environments
* Don't perform any operation on the first, do something on the second (open it and try a command in the command line)
* Click on the action "Get logs". With this PR in place, the logs are the …
=> feat(state): allow using immutability-helper commands on model objects

src/notebooks/Notebooks.state.js, src/project/Project.state.js
It turns out that the `.setObject` function doesn't handle well overwriting arrays. When updating the commits, it happened that switching from a branch with `n` commits to another with `m<n` commits left old data behind.
This PR fixes that problem and makes atomic a few other environments related state updates. 
Fix #663
EDIT:
~It requires #655 to be merged.~ --> merged
Preview: https://lorenzotest.dev.renku.ch
=> fix(environments): reset commits data correctly on branch change

src/dataset/Dataset.present.js
Added link to external source and author affiliation.
Test Env: https://virginiatest.dev.renku.ch/
Closes #687
=> feat(datasets): with link to external source and author affiliation

helm-chart/renku-ui/values.yaml
Updated the project templates tag.
Currently used in Renku 0.5.0.
=> Updated templates tag

src/dataset/Dataset.present.js, src/project/Project.state.js
Closes #706 
Testing: https://virginia.dev.renku.ch 
--> you will see using the debugging tools that before we where receiving a 404 when a project had no datasets and now we get a 200 with an empty array.
=> feat(dataset): fetch datasets without 404 and delete identifier modification

src/api-client/dataset.js, src/api-client/pagination.js, src/dataset/list/DatasetList.container.js, src/dataset/list/DatasetList.state.js
Handle pagination according to the specifications from the knowledge-graph endpoint. Please note that
pagination headers are different from the GitLab ones.
Preview available here: https://lorenzotest.dev.renku.ch/datasets
fix #713
=> feat(datasets): implement pagination

package-lock.json, package.json, src/landing/Landing.js, src/model/Model.test.js
Attempt to fix console warning on `npm test`. There are still 2 libraries responsible for throwing react related warnings
```
react-autosuggest
@nteract/notebook-render
```
Currently, no up-to-date version is available
=> test: fix test warnings

src/file/File.container.js, src/model/RenkuModels.js, src/notebooks/Notebooks.present.js, src/notebooks/Notebooks.state.js, src/notebooks/Notebooks.test.js, src/utils/HelperFunctions.js, src/utils/Utils.test.js
When starting a new interactive environment, the UI now checks for project options available in the `.renku/renku.ini` file, it tries to apply the settings and it displays popup warnings where needed.
More info in the docs here: SwissDataScienceCenter/renku#723
**HOW TO TEST**
A preview is available at https://lorenzotest.dev.renku.ch/
This is a project with some already defined custom options: https://lorenzotest.dev.renku.ch/projects/lorenzo.cavazzi.tech/projectoptions
fix #481
=> feat(environments): read project level notebook options

src/api-client/notebook-servers.js, src/notebooks/Notebooks.container.js, src/notebooks/Notebooks.present.js, src/notebooks/Notebooks.state.js
Server logs API now returns data in JSON format SwissDataScienceCenter/renku-notebooks#225
This PR modifies the logs functionality as follows:
* adapt to JSON response
* query by default 250 lines from the logs
* query the whole log when clicking on download
fix #700
fix #715
=> feat: update server logs

src/api-client/project.js
fix #724
how to test: search for project filtering by groups and use `sub`. Clicking on `cav-sub-level1` doesn't show the projects without this fix
=> fix: show all group's descendants

src/notebooks/Notebooks.present.js
This PR follows up #721 by disabling the logs download button when no logs are available.
Preview here: https://lorenzotest.dev.renku.ch
Start any environments, try to get the logs immediately after. As long as the logs are unavailable, it's not possible to click on download.
=> feat: prevent downloading empty logs

src/help/Help.present.js
Fix #710
See preview at https://sekhar.dev.renku.ch/help
=> Add link to discourse to help page

src/model/RenkuModels.js, src/project/Project.js, src/project/Project.present.js, src/project/Project.state.js, src/project/fork/ProjectFork.container.js, src/project/fork/ProjectFork.present.js
Fix #723
Solution available for testing on https://sekhar.dev.renku.ch
To test -- fork a project and see that
1. The fork popup dialog disappears when the fork succeeds
1.1 The dialog remains until the browser has loaded the new forked project
2. The dialog stays around when the fork fails and notifies the user of the problem.
Check on at least two browsers, as the behavior was different before on Chrome vs. Safari or Firefox.
=> Close pop-up after successful fork operation

.github/ISSUE_TEMPLATE/bug_report.md
Some other repos (renku, renku-python) have bug report templates that help people who are finding bugs fill out information that help devs fix the bug. This adds a bug report template for the UI repo.
=> feat: bug report template for ui

src/project/Project.present.js, src/project/Project.test.js
For anonymous users, both the environments and the 404 pages suggest to log in. The former one shows a login button, the latter doesn't (see picture below). This PR adds the button to the latter.
<kbd>
</kbd>
re #SwissDataScienceCenter/renku#730
**HOW TO TEST**
A preview is available at https://lorenzotest.dev.renku.ch/projects
Try to access a non-existing project *as anonymous user*, e.g. https://lorenzotest.dev.renku.ch/projects/noname/fakeproject
Compare with https://dev.renku.ch/projects/noname/fakeproject
=> refactor: add log in button on 404 page warning for anonymous users

docker-entrypoint.sh, helm-chart/renku-ui/templates/deployment.yaml, helm-chart/renku-ui/values.yaml, package-lock.json, package.json, run-telepresence.sh, src/index.js
This PR introduces the support for tracking expectations in Sentry.
It works, but any suggestions for improvements are welcome :slightly_smiling_face: 
The errors are reported here https://sentry.dev.renku.ch/swissdatasciencecenter/renku-ui/
* Using telepresence: execute the telepresence script with "SENTRY=1" `SENTRY=1 ./run-telepresence.sh`. Generate any error, e.g. by adding `throw Error("fake")` in `index.js` **after** `// configure Sentry`
* On a deployment: you can deploy it to any namespace after updating the value file as per SwissDataScienceCenter/sdsc-dev-docs#57 . Remember to add a fake error as pointed out above.
* It is temporarily possible to generate fake errors by visiting https://lorenzo.dev.renku.ch/
The errors take up to one or two minutes to show up. …
=> Add support for sentry

src/App.css, src/project/Project.js, src/project/Project.present.js
This PR improves the `fork` and `star` buttons displayed in the project's header:
* dynamic layout (it used to be fixed and this causes problems with specific window sizes)
* responsive to mouse click (loader icon and custom text)
* add link to GitLab projects fix #765 (and partially addresses #746)
Preview available on https://lorenzotest.dev.renku.ch/
Open any project and try to change browser sizes while checking the top buttons.
Try to start/unstar the project and click on the fork numbers to open the gitlab fork page.
=> feat: add link to gitlab forks page

src/project/Project.js, src/project/Project.present.js, src/project/new/ProjectNew.container.js
This PR address 2 issues
* prevent 404 page when loading projects by id (fix #716 )
* redirect to `/projects/<namespace>` on new project creation instead of `/projects/<id>` (fix #766 )
Open a new project by id and verify that the 404 page doesn't appear. Compare it with `dev`
fixed: https://lorenzotest.dev.renku.ch/projects/95
previous: https://dev.renku.ch/projects/95
The same applies when creating a new project.
=> fix: prevent 404 pages

src/api-client/graph.js, src/file/Lineage.container.js, src/file/Lineage.css, src/file/Lineage.present.js, src/project/Project.present.js
The UI lineage needs to be adapted to prevent it from failing due to the new nodes id format.
SwissDataScienceCenter/renku-graph#248 adds extra properties to the lineage query we can use in order to stop guessing nodes properties from the id.
I mixed a few fixes in this PR
* Update lineage query to get more data and stop guessing nodes properties from the id
* Fix location issues that prevented switching correctly between files and lineage
* Allow viewing folders lineage
* Remove unnecessary scrollbar on svg elements
Please take some time to check the lineage of a few projects.
Preview available here:  https://lorenzotest.dev.renku.ch/
=> feat(lineage): adapt to the lineage endpoint update

src/api-client/test-client.js, src/namespace/Namespace.container.js, src/namespace/Namespace.present.js, src/namespace/Namespace.test.js, src/namespace/index.js, src/project/Project-Route.test.js, src/project/Project.js, src/project/Project.present.js
Users and groups are not first-class citizens yet. Since users may try to reach the `/projects/<namespace>` url anyway, we want to provide useful information when hitting that route.
With this PR, the existence of the `<namespace>` is tested and, according to the result (user, group or non-existing), actions are suggested to the user.
fix #750
Try to reach a few `/projects/<namespace>` URLs, at least one for each of the 3 following types
* User: E.G. https://lorenzotest.dev.renku.ch/projects/lorenzo.cavazzi.tech
* Group: E.G. https://lorenzotest.dev.renku.ch/projects/eurobioc2019
* Non-existing: E.G. https://lorenzotest.dev.renku.ch/projects/nonexistent
=> feat: add basic page for namespaces

src/App.js, src/landing/Landing.js, src/namespace/Namespace.present.js, src/project/list/ProjectList.container.js, src/project/list/ProjectList.present.js, src/project/list/ProjectList.test.js, src/utils/quicknav/QuickNav.container.js, src/utils/quicknav/QuickNav.style.css
Implemented changes suggested by @ciyer in the issue #771 
It's basically this:
I have a small suggestion to add to that, i can implemented if you think is good, i think we should add a shadow to the autosuggest list... 
Now:
With shadow:
Change to add the shadow:
```
.searchBarSuggestionsContainer {
position: fixed;
top: 50px;
background-color: white;
z-index: 3;
padding-top: 30px;
box-shadow: 0 15px 20px rgba(0, 0, 0, 0.3);
}
```
Closes #771
=> fix(projects): changes on project naming and search to make it more user friendly

package-lock.json
Forgot to include this in the post update version bump.
=> chore: post 0.8.0 package-lock version bump

src/dataset/Dataset.present.js, src/project/Project.present.js, src/project/datasets/new/DatasetNew.present.js
There was an error after the dataset create that was NOT on the KG.
It was on the UI, after a dataset was created we where waiting until the dataset was on the KG and then redirecting the user to the datasets list, on this process we where getting the new datasets list but since this was taking some time (and we weren't waiting for the list to be there) we where displaying a message as if the dataset wasn't there. 
We now update the list (only when necessary).
There is also a change on the error message that is displayed so is not so strong. (I removed the Error 404 from it.
Docker image for testing: virfried/renku-ui:0.8.1-192a720
=> fix(datasets): the list of datasets is reloaded after dataset create

src/api-client/dataset.js, src/dataset/Dataset.present.js, src/model/RenkuModels.js, src/project/Project.js, src/project/Project.present.js, src/project/Project.state.js, src/project/datasets/DatasetsListView.js, src/project/datasets/edit/DatasetEdit.present.js, src/project/datasets/import/DatasetImport.container.js, src/project/datasets/import/DatasetImport.present.js, src/project/datasets/import/index.js, src/project/datasets/new/DatasetNew.present.js, src/utils/formgenerator/FormPanel.js
Closes #528 
There is a new button in the UI so the user can import datasets using the UI.
There are some things to be fixed in the backend for this to properly work. 
Button:
Form:
Deployment: https://virginiatest.dev.renku.ch/
=> feat(datasets): user can import datasets though the UI

src/dataset/list/DatasetList.container.js, src/dataset/list/DatasetList.present.js, src/dataset/list/DatasetList.state.js
Closes #757 
- When pressing search /datasets endpoint is invoked only 1 time.
- Fixed a small typo error under the search bar.
- Fix pagination problem (there are only 3 dataset's in renkulab so i can't test this) 
Testing: https://virginiatest.dev.renku.ch
=> fix(datasets): search calls KG once and paging problem fixed

src/help/Help.present.js, src/landing/Landing.present.js
Update the hardcoded links to the first step tutorial.
The reference issue implies these links need to be updated also in the `ops-*` repositories for the affected environments.
re SwissDataScienceCenter/renku#875
=> fix: update first step tutorial links

src/notebooks/Notebooks.present.js
In the environments pages, a new column shows the resources allocated for every environment
A preview is available here: https://lorenzotest.dev.renku.ch/
Start an environment in any project. After it is up and running, the environments table should show the requested resources in the new `Resources` column 
This requires SwissDataScienceCenter/renku-notebooks#261
fix #788
=> feat(environments): add requested resources info

src/utils/HelperFunctions.js
We support GitHub style markdown on `.md` files preview, but links are not automatically converted to `<a>` elements if not contained in the proper brakes `< >`.
Since also the GitLab preview supports it, we should have consistent behavior.
https://github.com/showdownjs/showdown/wiki/Showdown's-Markdown-syntax#links
**How to test**: Look at the difference in how the link on the second line is rendered here
* https://lorenzotest.dev.renku.ch/projects/lorenzo.cavazzi.tech/basic_python_project
* https://dev.renku.ch/projects/lorenzo.cavazzi.tech/basic_python_project
=> feat: convert links to anchor automatically on markdown files

src/dataset/Dataset.present.js, src/utils/FileExplorer.js, src/utils/UIComponents.js
The datasets display folder information now...
I deleted the links to the file and graph display but we could potentially add them next to the file name or something similar...
Testing: https://virginiatest.dev.renku.ch/datasets/9b3b47b7-277e-4368-87bd-c66513701dc5/
=> fix(datasets): dataset displays folder information

src/api-client/dataset.js, src/model/Model.js, src/model/RenkuModels.js, src/project/Project.present.js, src/project/datasets/edit/DatasetEdit.present.js, src/project/datasets/new/DatasetNew.present.js, src/utils/formgenerator/FormGenerator.css, src/utils/formgenerator/FormGenerator.test.js, src/utils/formgenerator/UseForm.js, src/utils/formgenerator/fields/FileUploaderInput.js, src/utils/formgenerator/services/InputValidator.js
Closes #849 
When a user uploads a zip file we ask the user if they want to unzip the file:
After they choose all work as normal.
Possible modification: we can see if the user chose or not, at the moment all files that are not in ready state are dismissed on form submit.
Testing available in: virginiatest.dev.renku.ch
=> feat(dataset): users can unzip files in the backend #849 #796

src/utils/HelperFunctions.js
Tables were rendered without proper styling, making them look like unformatted text.
This PR adds the proper classes to converted `<table>` elements so that Boostrap styling is applied without requiring changes from the users.
Compare these 2 examples:
https://lorenzo.dev.renku.ch/projects/lorenzo.cavazzi.tech/test
https://dev.renku.ch/projects/lorenzo.cavazzi.tech/test
=> feat: render markdown tables with bootstrap styling

.github/workflows/ci.yml
This is the first step in moving from Travis CI to GitHub actions.
It runs Jest test and ESlint linting. We could keep both sets of actions for a while to verify if the result is similar.
Partially address #772
=> ci: add github test action

src/App.css, src/issue/Issue.js, src/utils/HelperFunctions.js, src/utils/UIComponents.js
The issues list now correctly parse the markdown text shown as a preview.
The markdown preview is ideally limited to a single line, but this may fail in some cases (e.g. if the issue starts with a table, no content is visible).
PREVIEW: https://lorenzotest.dev.renku.ch
EXAMPLE: https://lorenzotest.dev.renku.ch/projects/lorenzo.cavazzi.tech/test/collaboration/issues
--> compare with https://dev.renku.ch/projects/lorenzo.cavazzi.tech/test/collaboration/issues
fix #847
=> feat: show markdown extract in issues list preview

package-lock.json, package.json
Minor update. It removes the warning due to the use of the deprecated react function `componentWillReceiveProps`. The last component that still has that issue is `@nteract/notebook-render`
=> chore: update react-autosuggest

docker-entrypoint.sh, helm-chart/renku-ui/templates/deployment.yaml, helm-chart/renku-ui/values.yaml, run-telepresence.sh, src/Maintenance.js, src/Maintenance.test.js, src/index.js, src/landing/NavBar.js, src/landing/index.js
Provide a maintenance page to be used during renkulab maintenances when important components are not available (e.g. Keycloack, GitLab, ...). This prevents any API call.
The maintenance page is piloted by `ui.maintenance` in the values files or the `MAINTENANCE` environment variable in the pod (the latter is created from the former).
By default `ui.maintenance: false`. It can be set to `true` or to any other string that will be used as a message to display on the maintenance page.
**TEST**
Feel free to modify the values while testing (the easiest is modifying the `MAINTENANCE` UI pod env variable from rancher).
This is the maintenance page with the standard message:
fix #894
=> feat: add maintenace page

docker-entrypoint.sh, helm-chart/minikube-values.yaml, helm-chart/renku-ui/templates/deployment.yaml, run-telepresence.sh, src/App.js, src/api-client/index.js, src/api-client/notebook-servers.js, src/api-client/pipeline.js, src/landing/NavBar.js, src/model/RenkuModels.js, src/notebooks/Notebooks.container.js, src/notebooks/Notebooks.present.js, src/notebooks/Notebooks.state.js, src/notebooks/Notebooks.test.js, src/notebooks/index.js, src/project/Project.present.js, src/utils/UIComponents.js
Allow all users (both unprivileged and anonymous) to start environments on public projects.
* As an unprivileged user, you can start environments also in protected projects and check the pipelines/jobs status.
* As an anonymous user, only the image status will be checked without further details. You are not allowed to ignore that, so it shouldn't be possible to start environments from the wrong image.
A temporary login (not requiring name or any user action) will be triggered when accessing the environments page. This is needed to correctly associate environments to users.
Testing this PR requires an appropriate backend. A preview is available here:
https://andreas.dev.renku.ch
Try to access any public project and start an environment there.
supersede #865 
close #857
=> feat(environments): allow all users to start interactive environments

src/index.js
The maintenance feature in the UI has shown its limits during the last maintenance and we may want to overhaul it soon.
Anyway, in the current form, it's safer to consider the strings "0" and "false" as if they were `0` and `false` to allow ops people to change values on the fly on rancher.
=> fix: consider falsy string values for maintenance page

src/file/File.container.js, src/file/File.present.js, src/file/File.test.js, src/styles/_jupyter_notebook.scss, src/styles/index.scss
Fix #838 (Allow hiding/showing of notebook cells)
Also:
* Use Source Code Pro for output display
* Show stdout output in black
* Style tables as bootstrap tables
See the difference in fonts and colors
* https://dev.renku.ch/projects/cramakri/notebook-rendering/files/blob/notebooks/ouput-test.ipynb
* https://sekhar.dev.renku.ch/projects/cramakri/notebook-rendering/files/blob/notebooks/ouput-test.ipynb
See how the input cells are hidden when papermill runs in report mode
* https://dev.renku.ch/projects/cramakri/notebook-rendering/files/blob/notebooks/tables-test-report.ran.ipynb
* https://sekhar.dev.renku.ch/projects/cramakri/notebook-rendering/files/blob/notebooks/tables-test-report.ran.ipynb
See how the tables look different
* https://dev.renku.ch/projects/cramakri/notebook-rendering/files …
=> Fix notebook display issues

src/file/File.container.js, src/file/File.present.js, src/notebooks/Notebooks.container.js, src/notebooks/Notebooks.present.js, src/project/Project.present.js
This fixes the `CheckNotebookStatus` component by correctly setting the `"user"` subModel in the constructor and showing the normal commands also to unprivileged users.
It goes further by adding basic support for being re-directed back to the notebook page when starting an environment from there. That part needs polishing but it will be addressed in the proper issue.
Go to a project containing a notebook, click on the "Start environment" Jupyter icon. This should now work again and bring you back to the original page when done, even if the feedback you get there is still poor.
https://lorenzotest.dev.renku.ch/projects/lorenzo.cavazzi.tech/zurich-bikes-tutorial/files/blob/notebooks/zhbikes-notebook.ipynb
=> fix: update the jupyter button used in file view

src/api-client/project.js
A quick fix to avoid any unknown jinja variable and jinja `if-endif` statement to generate problems during project creation.
E.G: SwissDataScienceCenter/renku-project-template#72
Please use an environment deployed using a `values.ymal` file containing the following setting -- it should be standard (otherwise please add them and re-deploy):
```
ui:
templatesRepository:
url: https://github.com/SwissDataScienceCenter/renku-project-template
ref: master
```
Creating a new `Python basic` project will result in a wrong README file (notice the `udefined` value and the `{ if` ) without this PR.
You can either use telepresence and switch between this branch and `master`, or use this image for the current branch `lorenzocavazzitech/renku-ui:0.9.2-4161b4a`
=> fix: remove conditional statemens from template files

src/help/Help.container.js, src/help/Help.present.js, src/landing/Landing.present.js, src/landing/NavBar.js
Fix #892
Menu now looks like: 
Help page looks like:
Try it out at https://sekhar.dev.renku.ch/help
=> Link to renku documentation in the UI

src/api-client/dataset.js, src/project/datasets/new/DatasetNew.container.js
"dataset_name" inside the core service changed to "short_name" this will allow us to use in the future for "dataset_name" a proper title with spaces and short name would be the title that we have now.
For testing this in your own env you need to have the latest version of renku-core(0.10.3-cf08d03)
=> fix(datasets): dataset_name changed to short_name

src/App.js, src/api-client/dataset.js, src/api-client/project.js, src/dataset/Dataset.container.js, src/dataset/Dataset.present.js, src/dataset/addtoproject/DatasetAdd.container.js, src/dataset/addtoproject/DatasetAdd.present.js, src/dataset/addtoproject/index.js, src/model/RenkuModels.js, src/project/Project.js, src/project/datasets/import/DatasetImport.container.js, src/project/new/Project.style.css, src/project/shared/Projects.state.js, src/utils/Dataset.js, src/utils/HelperFunctions.js, src/utils/formgenerator/FormPanel.js, src/utils/formgenerator/UseForm.js, src/utils/formgenerator/fields/SelectAutosuggestInput.js, src/utils/formgenerator/fields/index.js, src/utils/formgenerator/services/InputValidator.js
Closes #527 
I added a button in the datasets (for users that are logged in) so users can add datasets to projects.
(I don't really like the way this buttons looks, maybe we could do something to improve them
---> I know i was the one creating them haha)
After the user presses on the button a modal opens, and they can select a project from the list of projects where they are MAINTAINER.
They press Add dataset, they wait and they are redirected to the project/new-dataset
I am not 100% sure it works on datasets with unzipped files. (If this is the case it would be a backend issue)
=> feat(datasets): users can add datasets that are inside renku to other projects

src/api-client/repository.js, src/merge-request/MergeRequest.container.js, src/merge-request/MergeRequest.present.js, src/model/GlobalSchema.js, src/model/RenkuModels.js, src/model/index.js, src/notebooks/Notebooks.container.js, src/notebooks/Notebooks.state.js, src/project/Project.js, src/project/Project.present.js, src/project/Project.state.js, src/project/Project.test.js, src/project/index.js, src/utils/Commits.css, src/utils/Commits.js, src/utils/Time.js, src/utils/UIComponents.js, src/utils/Utils.test.js
Adds all the necessary logic to handle projects commits.
It includes a `ProjectCoordinator` component to handle storing project data to the global Redux store (#623). This created extra difficulties since we can't easily migrate all the `ProjectModel` logic at once. To simplify the temporary co-existence, I created a higher order function `withProjectMapped` to map project data from the global store to single components whenever needed.
The first commit closes #852 by adding a new "Commits" section in the project overview tab, while the second commit re-uses the `CommitsView` component in the merge request section.
The third commit injects all the commits-related logic in the environments components. We may want to clean up a little bit `Notebooks.container.js` when `branches` will be …
=> feat: show commit list

src/notebooks/Notebooks.container.js, src/utils/HelperFunctions.js, src/utils/Utils.test.js
This filters autosaved branches based on the username.
Preview temporarily available on https://lorenzo.dev.renku.ch/
* Generate an autosaved branch: go to any public project, start an environment, do any change and stop the environment without committing/pushing
* Verify that trying to start an environment from the same project will show you the autosaved branch popup -- don't start it!
* Log out and try to start an environment as an anonymous user or using another user without developer privileges on the project. This time you shouldn't see any popup.
fix #906
=> fix(environments): skip autosaves for unprivileged users

src/project/datasets/edit/DatasetEdit.present.js, src/project/datasets/new/DatasetNew.container.js, src/utils/FileExplorer.js, src/utils/UIComponents.js, src/utils/formgenerator/fields/FileUploaderInput.js
Fixes #896
(Luis made a good explanation of the problem on the issue)
Now the folder looks like this: 
There is still a small problem since there is an extra file there that wasn't on the folder structure.
Also, the redirect after the operation is finished isn't working well now.
(We weren't sending all the id's for unzipped files and now we are)
=> fix(datasets): dataset has all folders from unziped file

package-lock.json, package.json, src/dataset/Dataset.present.js, src/dataset/list/DatasetList.present.js, src/model/RenkuModels.js, src/project/datasets/DatasetsListView.js, src/utils/UIComponents.js, src/utils/formgenerator/fields/CKEditorTextArea.js
This is the first step into integrating CKEditor inside renku.
For this: 
- I created a new build of the editor for renku  https://github.com/SwissDataScienceCenter/ckeditor5-build-renku 
- I forked the ckeditor5 entire project (https://github.com/SwissDataScienceCenter/ckeditor5) (this is what they call ckeditor5 frameworK) since i was having some problems with some components.
- Inside this project i modified and published individually inside npm:
- https://www.npmjs.com/package/@renku/ckeditor5-code-block
- https://www.npmjs.com/package/@renku/ckeditor5-markdown-gfm
- https://www.npmjs.com/package/@renku/ckeditor5-table
Since i was having some problems with integrating this and markdown inside the editor. I hope 
they fix this bugs and we can just delete this packages and use the …
=> feat(ckeditor): ckeditor partially integrated inside renku

src/App.css, src/utils/UIComponents.js
Right now code gets a bit "lost" inside markdown....
I think we should highlight it a bit better.. 
This is just a proposal, we could also do it a bit darker with lighter words or something similar.
We could also think about going all the way and using something like this https://github.com/sindresorhus/github-markdown-css 
(This makes all our markdown look like the gitlab one) ---> NOT SURE THIS IS WHAT WE WANT
=> feat(markdown): code is highlighted a bit more

src/api-client/project.js, src/project/datasets/import/DatasetImport.container.js, src/project/datasets/new/DatasetNew.container.js
Closes #924 
In case a dataset fetch fails all dataset fetch was failing.
This was causing a "no dataset inside this project" message.
Now in case a dataset can't be fetched we display all the datasets that where fetched with no problem.
I also replaced some calls to get dataset for simplified ones when we don't need to get all the dataset info (i.e redirect after dataset add).
=> fix(datasets): if a dataset fails we display non-failed datasets

src/dataset/addtoproject/DatasetAdd.container.js, src/dataset/addtoproject/DatasetAdd.present.js, src/utils/formgenerator/FormPanel.js
When adding a dataset takes too long we display display OK button when import fails (This button will close the modal) instead of "Add Dataset" and "Cancel" this should be less confusing for the user. 
To test this pull the branch and inside /dataset/addtoproject/datasetadd.container change line 125 
from:
`if ((cont > 30 && job.state !== "IN_PROGRESS") || (cont > 50 && job.state === "IN_PROGRESS")) {`
to:
`if ((cont > 1 && job.state !== "IN_PROGRESS") || (cont > 1 && job.state === "IN_PROGRESS")) {`
this will make the wait too short so the dataset add should display an error message and the new button.
=> fix(datasets): when dataset takes too long we display an ok button instead of cancel and add dataset

src/dataset/Dataset.present.js
Closes #943 
"Add to project" button was removed from the UI, inside project and dataset general search.
Testing: https://virginiatest.dev.renku.ch
=> fix(dataset): add to project button removed from datasets UI

src/api-client/project.js, src/project/Project.state.js
Every time we update the topics or the description in the setting page of a project, the name is also provided to the API so that it's updated with the current value.
This makes the update fail when the user has the permissions to update one of the fields but not the project name (see the example in #951).
This PR removes that unnecessary name update and fixes the `is_updating` label that appears on the tags list when removing the last tag (probably introduced during a recent re-factory)
fix #951
=> fix: update project topics correctly

src/notebooks/Notebooks.container.js, src/notebooks/Notebooks.present.js
Custom project options selected by default don't disappear anymore when another option is selected.
The problem happened only if the pinned option at the project level was of type `enum` and it was not available per default on that renkulab deployment.
This also fixes a bug introduced in a recent refractory that prevented fetching commits for specific branches.
Preview: ~https://lorenzotest.dev.renku.ch/~
***HOW TO TEST***
Pick a project with custom options, try to select different options and verify none of them disappear.
E.G. on the following project, select the branch `tree` and compare
https://lorenzotest.dev.renku.ch/projects/lorenzo.cavazzi.tech/flights-tutorial/environments/new
https://dev.renku.ch/projects/lorenzo.cavazzi.tech/flights-tutorial/environments/new
fix #935
=> fix(environments): avoid project options to disappear once deselected

src/utils/formgenerator/fields/CKEditorTextArea.js
Closes #953
To test this:
- go to dev
- pick a dataset to modify
- change the editor to "code view"
- you will be able to modify (but not to save) the dataset description
- do this again on this branch and you will not be able to do this
=> fix(editor): when the editor is in code mode on edit is now disabled

src/App.css, src/landing/Landing.present.js, src/landing/NavBar.js, src/project/list/ProjectList.container.js, src/project/list/ProjectList.present.js, src/project/list/ProjectList.state.js, src/utils/UIComponents.js, src/utils/quicknav/QuickNav.present.js
In #703, we suggest to slightly modify the project list layout, hiding the description when not available.
This PR introduces that change and it fixes a number of other issues related to project list and project search. The idea is to keep the layout consistent at different window sizes while adapting to the content (e.g. missing description, date positioning, ... -- see the screen below or the preview).
Preview: https://lorenzotest.dev.renku.ch/projects
Please feel free to suggest any further improvement.
The final result is closer to the current GitLab project list layout: https://dev.renku.ch/gitlab/
=> feat: improve project search and project list layout

run-telepresence.sh
Update the telepresence file to support the `RENKU_DOMAIN` environment variable set up while using localhost.run as suggested by the renku documentation.
=> chore: update minikube url

src/project/Project.present.js
#961 got merged to handle projects without a `Description` field. This PR fixes a couple of minor leftovers:
1. Avoid React error on project's setting tab page
2. Avoid `<br />` element adding extra space on top of the project's overview page
=> fix: properly handle missing description field in project page

src/api-client/project.js, src/project/shared/Projects.state.js
We should query for 100 projects per page instead of 20 to prevent unnecessary multiple queries.
Not a big change tbf, but I noticed that the current limit per page is pretty low and we end up making way more queries than necessary.
=> perf: query 100 projects instead of 20

src/api-client/project.js, src/landing/Landing.js, src/landing/NavBar.js, src/project/Project.js, src/project/shared/Projects.state.js, src/utils/quicknav/QuickNav.container.js
This improves the `client.getAllProjects` function and limits its use to whenever it's necessary.
* Prevent fetching user projects when browsing as an anonymous user.
* Re-use `client.getProjects` function in `client.getAllProjects` and make it more readable.
* Invoke `client.getAllProjects` also for starred projects to be sure we are not missing projects.
fix #986
EDIT: sorry for not making a preview available, I'm running out of test deployments :disappointed:
=> perf: adjust code fetching all projects

src/dataset/list/DatasetList.state.js
This works in a similar way as projects, when user goes to the "Datasets" tab on top they see an initial search...
Closes #826
=> fix: when user clicks on dataset tabs they see an initial search

src/dataset/Dataset.present.js
Go to source button and source link are redirecting the user to the current location when the dataset is seen from outside a project:
With this change the buttons are not displayed in case the user is not inside a project.
Closes #729
=> fix: go to source and source button only displayed when inside project

src/dataset/Dataset.present.js, src/dataset/list/DatasetList.present.js, src/project/Project.present.js, src/project/datasets/DatasetsListView.js
Name was replaced by title for dataset display purposes...
Before:
After:
Right now the difference is only visible with datasets that have name and title that are not the same (like the flights dataset or zenodo imported datasets)
If you want to see the "before" you might have to deploy the renku-graph version: 1.5.0
Closes #1009
=> fix: dataset name replaced by title where needed

docker-entrypoint.sh, helm-chart/renku-ui/templates/deployment.yaml, helm-chart/renku-ui/values.yaml, run-telepresence.sh, src/App.js, src/App.test.js, src/help/Help.container.js, src/help/Help.present.js, src/index.js, src/landing/Landing.js, src/landing/Landing.present.js, src/model/Model.js, src/model/RenkuModels.js, src/statuspage/Statuspage.container.js, src/statuspage/Statuspage.present.js, src/statuspage/StatuspageAPI.js, src/statuspage/index.js, src/utils/Time.js, src/utils/UIComponents.js, src/utils/UseInterval.js, src/utils/Utils.test.js
The is PR implements the design specified in #938.
The configuration for this feature is documented in https://github.com/SwissDataScienceCenter/renku/pull/1315.
The dev-values file template is updated in this PR: https://github.com/SwissDataScienceCenter/sdsc-dev-docs/pull/65
- if the statuspage.id value is not configured, then you should not see the help/status page
- if the statuspage.id value is set to junk, then you should see a banner explaining that the statuspage is not correctly configured in the help/status page
- if you add a scheduled maintenance, you should a notification banner and details in the help/status page
- if a component is not stable, you should a notification banner and details in the help/status page
You can create a free account at …
=> Integrate statuspage.io in the UI

.github/workflows/ci.yml
The helm chart should be linted only for master/tagged version, not on the PRs.
This fixes a wrong precedence in the ci action preventing them from publishing the chart
=> ci: fix test-chart action precedence

src/notebooks/Notebooks.container.js, src/notebooks/Notebooks.present.js
This should better handle the case that sometimes happens where a user tries to start a notebook and is shown an endless spinning wheel.
The source of the problem is a 500 response from the notebook server when the UI asks to start a notebook.
If the server returns an error on notebook launch, it is retried. If the second attempt also fails, an info message is shown:
This is hard to test because it does not happen very frequently. To simulate, you can change the implementation of the function in notebook-servers.js:75 to:
```
client.startNotebook = async (namespacePath, projectPath, branchName, commitId, options) => {
const headers = client.getBasicHeaders();
headers.append("Content-Type", "application/json");
const url = `${client.baseUrl}/notebooks/servers`;
const parameters = { …
```
=> Notebook launch errors

src/help/Help.container.js, src/help/Help.present.js
The server setup documentation isn't very helpful for the normal RenkuLab user. We can remove it.
The help page now looks like this:
=> feat: remove superfluous server setup documentation

package-lock.json, package.json
I found this solution that fixes the ckeditor problem:
https://github.com/ckeditor/ckeditor5-react/issues/142#issuecomment-659060608
I implemented the solution but I am still not sure what are the consequences of this, besides the fact that the CKEditor works well now.
I ran a command found [here](https://github.com/browserslist/browserslist#query-composition) to compare the difference between the configurations, there is only one difference:
If we can live with this config change I would push this fix.
I saw that create react app also removed the "not ie 11" from their config here:
https://github.com/facebook/create-react-app/commit/f4f20a20d095c7ea97191292e9d17753ff24596a
Can be tested in https://virginia.dev.renku.ch/
Closes #1022
=> fix: ckeditor toolbar works as expected now

src/App.css, src/collaboration/issue/Issue.js, src/contribution/Contribution.container.js, src/contribution/Contribution.present.js, src/dataset/Dataset.container.js, src/dataset/Dataset.present.js, src/file/File.container.js, src/model/RenkuModels.test.js, src/project/Project.js, src/project/Project.present.js, src/utils/Markdown.js, src/utils/UIComponents.js, src/utils/Utils.test.js
I created a markdown component that fetches images from relative paths and also fixes relative links in markdown files.
I also improved/restyled the preview of files...
We only preview files with "!" in the front... since I think it's nice to also leave the option to not preview a file in case this is not desired.
Closes #667 
Closes #941
=> feat: display of relative paths in markdown and improvement in file preview in markdown

public/index.html, src/index.js
All code resources are retrieved from the renkulab server.
Before, `jquery`, `popper`, and `bootstrap` were retrieved from the web.
Compare before change:
With after:
Compare (new):
Now, only the Source Code Pro font is retrieved from the web, but if this is missing, it shouldn't cause a major problem for the UI, since it will default to another monospaced font.
The new version can be tested on https://sekhar.dev.renku.ch/
Fix #1027
=> Get all code resources from webpack

CHANGELOG.md
Changelog updates for 0.10.4 (which is based on the 0.10.x branch, not master).
(cherry picked from commit ff0633a2cf4a4b8c1fa3e554ceda221a8bbf3a88)
=> chore: 0.10.4 changelog

src/notebooks/Notebooks.present.js, src/notebooks/Notebooks.test.js
#950 introduced a change to prevent project options from disappearing, but this was applied to things like cpu_request and mem_request, which the user cannot actually control. With this change, only default_url can be extended by the project options in the `renku.ini` file, other options will be ignored and show a warning if the project default is not available in the server environment. 
The fix is deployed to https://sekhar.dev.renku.ch, to test, try out this project: https://sekhar.dev.renku.ch/projects/cramakri/project-defaults-test/environments/new
Fix #1025.
=> fix: only merge server options for the default_url (#1025)

package-lock.json, package.json, src/App.js, src/App.test.js, src/index.js, src/landing/NavBar.js, src/model/GlobalSchema.js, src/model/RenkuModels.js, src/notebooks/Notebooks.container.js, src/notifications/Notifications.container.js, src/notifications/Notifications.css, src/notifications/Notifications.present.js, src/notifications/Notifications.state.js, src/notifications/Notifications.test.js, src/notifications/index.js, src/project/Project.present.js, src/utils/UIComponents.js
Client-side notification system with toast notifications and dropdown menu in the top navbar.
Currently, only a couple of notebooks action trigger notifications.
For convenience, on the test deploment it's possible to create fake notifications from the notifications menu
=> feat: client side notification system (core)

.eslintrc.json, src/api-client/index.js, src/api-client/pagination.js, src/api-client/repository.js, src/api-client/utils.js, src/model/RenkuModels.js, src/notebooks/Notebooks.present.js, src/project/Project.present.js, src/project/Project.state.js, src/project/Project.test.js, src/utils/UIComponents.js
This went a bit further than expected, introducing a couple of related (minor) changes.
* Introduces a method to fetch from API returning paginated data.
* Handles up to 1000 branches and commits (the limit is in place to prevent endless fetching loops that will fail anyway due to the gateway rate limit).
* Updates visualization where needed (project pages "overview --> commits" and "environments --> new")
* Minor changes to the Pagination component.
fix #1037, accidentally fix #764
P.S. All my namespaces are currently full so no preview available. You can run it on telepresence or contact me and I'll create a temporary preview.
=> feat: handle paging responses from apis

src/api-client/index.js, src/api-client/notebook-servers.js, src/notebooks/Notebooks.state.js
Fix an API call that mistakenly triggered the login workflow when trying to start an anonymous session. That happened only in specific situations.
This includes a minor workaround to prevent the UI from showing for a moment an error page when performing the "anonymous login".
***How to test it***
The problem happens almost always if you
* Use a chrome-based browser
* Goes directly to the `/environments/new` page
A good test can be done by comparing the 2 following pages (advice: use chrome/chromium in a Private Window)
https://lorenzotest.dev.renku.ch/projects/renku-test/test-2020-09-24-13-27-17/environments/new
https://dev.renku.ch/projects/renku-test/test-2020-09-24-13-27-17/environments/new
fix #1030
=> fix: anonymous interactive environments

src/api-client/dataset.js, src/api-client/project.js, src/dataset/Dataset.container.js, src/dataset/Dataset.present.js, src/file/KnowledgeGraphStatus.container.js, src/file/KnowledgeGraphStatus.present.js, src/project/Project.js, src/project/Project.present.js, src/project/Project.state.js, src/project/datasets/DatasetsListView.js, src/project/datasets/edit/DatasetEdit.container.js, src/project/datasets/edit/DatasetEdit.present.js, src/project/datasets/import/DatasetImport.container.js, src/project/datasets/new/DatasetNew.container.js, src/project/datasets/new/DatasetNew.present.js
Dataset info for projects is partially retrieved from the core service.
--> Dataset List is almost the same, I only took out the number of projects a dataset is in and replaced it for information about whether the dataset is or not in the KG:
--> Dataset list for projects that are not in the KG is now visible:
--> Inside datasets that are not in the KG: (this can be because the entire project doesn't have the kg activated or because the kg is building)
--> Datasets that are not in the KG have the "add to project" button disabled.
There are no major changes that are visible in dataset preview, add and edit. This operations run much faster because they don't wait for the KG. Messages about KG errors were removed. 
When the planets are aligned all works much smoother, I have experienced some …
=> refactor: dataset info partially retrieved from the core service

src/project/Project.present.js, src/utils/UIComponents.js
Adds a button with the commands to clone the project locally, similar to what we find in both the GitLab and GitHub interfaces.
fix #929
=> Add button to clone renku project

src/api-client/repository.js, src/model/RenkuModels.js, src/notebooks/Notebooks.container.js, src/notebooks/Notebooks.present.js, src/notebooks/Notebooks.state.js
There are a couple of issues requiring to show commit data in the environments list. The proposed solutions were slightly different from the implemented one, but it turns out that other ways would require to implement operations in the backend that are possibly (probably) resource/time intensive for a marginal benefit.
In this PR, commit details are fetched directly through the GitLab API only when required by the user. The implemented interaction requires clicking on an info icon in the "commit" column (mind that the click on the commit-sha already redirects the user).
If the interaction is confusing, we can change it (e.g. remove the icon and change the popover trigger to "on-hover")
I didn't make a preview because my test namespaces are already used, but this can be run through …
=> feat: show commit details on-request in environments pages

src/project/Project.js, src/project/Project.present.js
Datasets are now displaying the correct message.
They display: 
"in the knowledge graph" if they are in the knowledge graph and the project has the knowledge graph activated
"not in the knowledge graph" in case one of the previous conditions isn't reached
---> This bug was introduced because there was a missing check to see if a project had the kg activated or not, in some cases we where also not fetching this information.
Testing:
--> check datasets for a project that you don't have rights in. I.E: https://dev.renku.ch/projects/virginiafriedrich/more-dataset-testing/datasets this project has the kg activated and the kg finished building so the datasets should display "in the knowledge graph"
--> this is fixed here... https://virginiatest.dev.renku.ch/projects/virginiafriedrich/more-datase …
=> fix: dataset displays kg message correctly

src/project/Project.present.js
Here is the new appearance. Initially, only the renku command is shown. Clicking on the text opens the git command.
Fix #1057
=> feat: better explain that renku clone is preferred

src/project/new/ProjectNew.present.js
The error message we get when trying to fetch custom templates can be structured. Invoking `JSON.stringify` when that happens is the easiest solution to prevent the UI from crashing.
In the specific case mentioned in the reference issue, I *think* the message is changed in the core service and it becomes more cryptic compared to the original git command error.
If it turns out that users get confused, we could either try to intercept and parse specific errors in the UI or change the message we emit from the core service.
Preview: https://lorenzotest.dev.renku.ch/projects/new
fix #1056
=> fix: jsonify structured error messages when fecthing custom templates

package-lock.json, package.json, src/file/File.container.js
The highlight library we are using is outdated and the support for the R language has a few bugs.
This PR updates the library and adds it to the npm dependencies (previously, it was imported as a requirement for another dependency).
OLD (some comments not highlighted)
NEW
=> build: update highlight library

src/model/RenkuModels.js, src/project/Project.js, src/project/Project.present.js, src/project/Project.state.js
This PR address most of the points from #1051. Speficially, these are the implemented changes:
* Create a new `status` tab on the project overview page
* Move the Knowledge Graph integration and Renku version information to the new page, adapting the layout to be consistent
* Remove Webhook banner from the project title/header
* Add Knowledge Graph integration info to project warning icon
I'll create a follow-up issue for further reworking the webhook-relate parts once the ui-backend will be in place --> #1080 
***Preview***: https://lorenzotest.dev.renku.ch/
=> feat: unify kg integration and renku version warning

client/src/dataset/Dataset.container.js, client/src/dataset/addtoproject/DatasetAdd.container.js, client/src/dataset/addtoproject/DatasetAdd.present.js, client/src/project/Project.present.js, client/src/utils/Dataset.js
The redirect after dataset add was broken... it was trying to redirect a user to /project/datasets/identifier (this was the identifier like c3177e09-0582-494d-8be3-a558ded9ea63) the projects now use the dataset-name. This pr redirects the user to the right place.
On top of that, it doesn't wait for the dataset to be in the KG to redirect since it's not needed anymore. 
To test: try to add a dataset to a project in dev using the "add to project" button
To see the fix: do the same in virginia.dev.renku.ch 
Closes #1075
=> fix: dataset redirects well and doesn't wait for the kg

client/package-lock.json, client/package.json, client/src/project/Project.js, client/src/project/Project.present.js, client/src/project/Project.state.js, client/src/project/filestreeview/FilesTreeView.js, client/src/project/filestreeview/treeviewstyle.css
Here is an alternative implementation of the file tree component with independent scroll from the main page (the other was #1070)
Following the reviews, I tried to
* remove any custom listener
* fix the visualization on Safari
* adjust the scroll
These required a few workarounds because the components in the project page are re-drawn every time the user clicks a file node on the tree. Changing this behavior would require a big re-design.
The only library I ended up using is [react-sticky](https://www.npmjs.com/package/react-sticky). I tried other solutions with [react-stickynode](https://www.npmjs.com/package/react-stickynode), [react-sizes](https://github.com/renatorib/react-sizes) and [react-measure](https://github.com/souporserious/react-measure), but the final result was either more …
=> Stick file tree component and set max height

client/src/dataset/Dataset.container.js, client/src/dataset/Dataset.present.js, client/src/file/KnowledgeGraphStatus.container.js, client/src/file/KnowledgeGraphStatus.present.js, client/src/file/Lineage.present.js, client/src/project/Project.js, client/src/project/Project.present.js
Unified status sign for /projects/datasets
In case the general sign is present there is no sign when entering a dataset view /projects/datasets/dataset-name 
(i deleted the big purple sign here)
In case the general sign is not present, there is a sign inside the dataset (This can happen if the dataset was recently added or the kg recently activated)
This alerts redirect the user to the status page
When the users activate the kg ---> here we use the same component as we use inside files (We could think about removing this in a future issue)
Testing: virginia.dev.renku.ch
=> feat: kg activation and kg in datasets improvements

.github/workflows/ci.yml
Reference: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
~P.S. the second commit is just for testing, I'll remove it as soon as the chart has been published correctly.~
UPDATE: second commit removed, it worked :tada: 
Chart pushed here: https://swissdatasciencecenter.github.io/helm-charts/renku-ui-0.11.2-9af026e.tgz
Chart tested here: https://lorenzo.dev.renku.ch/ (not that this test was very useful since the env variables are used only to push the  chart :grin: )
=> Replace deprecated set-env commands in the GitHub actions

client/src/project/Project.css, client/src/project/datasets/DatasetsListView.js, client/src/utils/UIComponents.js
The description is now cropped... This is just a proposal, when the user hovers over the description he can see a bit more, we can do changes to this by just cropping and not showing more.
We could also crop the creator's list, in most cases is not too long but in other it could be.
TEST: https://virginiatest.dev.renku.ch/projects/virginiafriedrich/project-11/datasets
https://virginiatest.dev.renku.ch/projects/virginiafriedrich/markdown-images/datasets
=> feat(dataset): description display has ben shortened

client/src/App.js, client/src/model/RenkuModels.js, client/src/notebooks/Notebooks.container.js, client/src/notifications/Notifications.container.js, client/src/notifications/Notifications.present.js
This includes 2 changes
1. fix: use the current location for notifications
2. refactor: change environments notifications
* Use error notifications when starting an environment fails
* Prevent successful notification from generating a toast when not needed (i.e. the user is on a environment page relevant for that project)
* Change link on the successful notification from the JupiterHub url to the project environments page
***Preview***: https://lorenzotest2.dev.renku.ch
=> fix notifications and change notebook notifications

client/package-lock.json, client/package.json, client/src/App.js, client/src/api-client/index.js, client/src/authentication/Authentication.container.js, client/src/authentication/Authentication.test.js, client/src/authentication/index.js, client/src/index.js, client/src/landing/NavBar.js, client/src/model/RenkuModels.js, client/src/notifications/Notifications.present.js, client/src/notifications/Notifications.state.js, client/src/setupTests.js
This implements a basic mechanism to synchronize tabs on relevant authentication events.
I prepared 2 previews, one with notifications and one without. I believe taking advantage of the notification system is very useful for this case. Otherwise, the user may be confused when he switches to a page that was refreshed without explanations.
***Preview without notifications***: https://lorenzotest2.dev.renku.ch/
***Preview with notifications***:  https://lorenzotest.dev.renku.ch/
***How to test***: Open at least 2 tabs on the same deployment. Try to login/logout in one of them, then check what happens in the other.
fix #1048
=> feat: sync tabs on authentication events

client/src/notebooks/Notebooks.container.js, client/src/notebooks/Notebooks.present.js, client/src/notebooks/Notebooks.state.js, client/src/notifications/Notifications.state.js, client/src/project/Project.state.js
In specific circumstances, it was possible to get outdated content after changing branch / commit.
In practice, that seems to happen only when changing the branch while commits fetch wasn't complete yet (it's not too tricky on projects with 1000+ commits).
I tried a few solutions, but I settled on disabling the branch / commit dropdown while fetching resources. Other solutions were potentially better but required a lot of changes in the code for minimal benefit.
The PR also implements better error handling when fetching commits fails.
Test environment: https://lorenzotest.dev.renku.ch
***How to test***: you can use a project with 1000+ commit, like `covid-19/covid-19-public-data`. Previously, changing the branch quickly after clicking on the "Environments --> New" tab resulted in wrong …
=> Fix wrong commit list when starting new environment

.github/workflows/ci.yml
The `test-chart` action uses the helm version `2.16.9`. We need to update to version `>= 2.17.0` to prevent it from failing as in https://github.com/SwissDataScienceCenter/renku-ui/runs/1649868184
Reference: https://helm.sh/blog/new-location-stable-incubator-charts/
=> ci: update helm url

client/src/file/Lineage.present.js
The UI seems to crash on the lineage preview when a `label` property of a "ProcessRun" node doesn't contain any space. In the example provided in #1101, the command is `sbt`.
I modified the logic we use to derive the label we show in the graph. Now the output looks fine in most cases, but it can be improved for very long strings. One way would be providing more interactions, like popovers or tooltips for long commands.
I guess this is enough as a bugfix, but we may want to refactor the graph output later to provide a better UX (that would require a design and a deep overhaul).
Please test using different projects, I may very well have missed corner cases.
fix #1101
=> fix: prevent crashes on lineage for short node labels

.github/workflows/acceptance-tests.yml, .github/workflows/test-and-ci.yml, README.rst, client/run-telepresence.sh
This has finally reached a mergeable state.
A new GitHub action allows developers to request an automatic RenkuLab deployment for any PR.
The trigger is the string `/deploy` anywhere in the PR message. It works even if the message is changed later.
The action will also automatically clean up the environment once the PR is closed.
This PR also includes a simplified way to start telepresence on a specific test PR (thanks @ciyer for that part! And sorry for melding the commit into the others), and a refresh on the `README` file.
re #1165
=> ci: deploy new environments on PRs on request

.github/workflows/acceptance-tests.yml
This fix is required to properly trigger the `cleanup` action whenever a PR is merged or closed in any way.
In short, the `cleanup` action required another step to start, but that could never happen because that step doesn't run on `close` events.
P.S. This has been tested here #1203
=> ci: remove unneeded requirements on cleanup job

client/src/App.js
There was code in the handling of route that appended '/' to routes that end in number. The line is very old (there at least since 2018), but it looks like it is no longer necessary and was probably causing problems with routing.
Testing:
**Check that routing of projects behaves correctly**
Resolve a project by project id:
- (old) https://dev.renku.ch/projects/7289
- (new) https://sekhar.dev.renku.ch/projects/7289
Resolve a project by project by namespace/path:
- (old) https://dev.renku.ch/projects/cramakri/file-type-test
- (new) https://sekhar.dev.renku.ch/projects/cramakri/file-type-test
Resolve a project by project by namespace/path, when path contains numbers:
- (old) https://dev.renku.ch/projects/renku-qa/1234/
- (new) https://sekhar.dev.renku.ch/projects/renku-qa/1234/
Resolve a …
=> fix: do not attach trailing '/' on routes that end in a number (#1148)

helm-chart/renku-ui/templates/deployment.yaml
This PR makes the `PRIVACY_BANNER_CONTENT` and `PRIVACY_BANNER_LAYOUT` env variables robust to missing values when the privacy `enabled` flag is `false`.
Tbh it was unlikely to mess up since default are assigned in the local values file, but it was tecnically possible. Considering how env variable values are consumed in "docker-entrypoint.sh", en empty `PRIVACY_BANNER_CONTENT` would have crashed the UI because of an invalid `config.json` file
> Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 11 column 28 of the JSON data
/deploy
fix #1045
=> ci: improve robustness to missing privacy values

client/src/App.js, client/src/index.js, client/src/landing/Landing.js, client/src/notebooks/Notebooks.present.js, client/src/utils/url/Url.js, client/src/utils/url/Url.test.js, client/src/utils/url/index.js
Adds a `Url` helper class with static methods and properties that simplifies getting a URL form wherever in the application.
Most of the URLs are static strings, but some are more complex (e.g. project in subgroups, projects search page). Those can now be built on the fly and even validated.
The PR also includes a thorough list of tests acting as documentation, and a few first examples.
The goal is to remove all the duplicate codes to create URLs on the fly (sometimes faulty, especially for project pages). We can either:
1. Gradually change the URL code when addressing issues impacting it.
2. Try to remove all the duplicates and fix the problems as part of this PR.
3. Create a follow-up issue for `2)`
I'm undecided between `1)` and `2)`, let me know if you have any preference.
**How to …
=> feat: add Url helper class

client/.eslintrc.json, client/docker-entrypoint.sh, client/package-lock.json, client/package.json, client/run-telepresence.sh, client/src/index.js, client/src/utils/sentry/Sentry.js, client/src/utils/sentry/Sentry.test.js, client/src/utils/sentry/index.js, helm-chart/renku-ui/templates/deployment.yaml, server/run-telepresence.sh
* Move Sentry configuration to a separate object.
* Add more information to exceptions sent to Sentry, including the UI version.
* Add a mechanism to filter events before sending them.
This has been used to prevent sending notebook preview related exceptions ( fix #1112 ).
**How to test**: try to preview a notebook that triggers an exception. Compare `dev` (exception logged in Sentry) to the auto deployed environment (no exceptions logged).
The following link provides a good test case; the exception is generated after clicking on "preview it anyway" https://dev.renku.ch/projects/cramakri/plotly-test/files/blob/notebooks/Plotly.ipynb
/deploy
=> Expand sentry configuration and prevent sending notebook errors

client/src/api-client/index.js, client/src/api-client/utils.js, client/src/utils/sentry/Sentry.js
This PR filters client-side errors that are not relevant to RenkuLab.
* Network errors: these happen when invoking `fetch` without reaching the url.
* Errors triggered after the `beforeunload` event: these seem to be Firefox specific. When the user manually navigate to another page, any ongoing `fetch` get interrupted and generate an error.
Testing is tricky, especially in the automatically deployed environment. In my dev environment, I hijacked some APIs to slow them down and trigger errors easily, or I manually faked extra network errors.
/deploy
fix #1141, fix #1106
=> Prevent sending to Sentry useless client-side errors

client/run-telepresence.sh, client/src/project/Project.present.js, client/src/utils/UIComponents.js
Fixes for:
- fix: get datasets even if user is not logged in (#1222)
- refactor: remove superfluous throttling (#1168)
- chore: fix run-telepresence to work with FreeBSD grep
Fix #1222 
Fix #1168
Compare:
- https://renku-ci-ui-1223.dev.renku.ch/projects/cramakri/dataset-test-project/datasets
- https://dev.renku.ch/projects/cramakri/dataset-test-project/datasets
In the first one, you will see datasets, on dev you will not.
Look at https://renku-ci-ui-1223.dev.renku.ch/projects/cramakri/collaboration-test/collaboration/issues/1/
(You need to be logged in)
Mouse over the buttons
You should see tooltips and they should disappear if you move the mouse off.
/deploy
=> Collection of small fixes

client/src/project/Project.state.js
The error was not affecting the usability of the UI.
It happened when trying to access a project that either doesn't exist or requires privileges.
Sentry caught that, it's good to fix it.
**How to test**: when the deployment is ready, compare accessing the following with the console open. The first should trigger an error, the second doesn't.
https://dev.renku.ch/projects/lorenzo.cavazzi.tech/idontexists
https://renku-ci-ui-1235.dev.renku.ch/projects/lorenzo.cavazzi.tech/idontexists
fix #1234
/deploy
=> fix: prevent accessing stats for non existing projects

client/src/landing/NavBar.js, client/src/project/list/ProjectList.present.js
This PR adds an `id` to the links to "Projects" pages.
It's useful to make our acceptance tests more robust and it doesn't introduce any change visible to users.
P.S. feel free to suggest a different naming.
=> refactor: add an id to every projects link

client/src/project/status/ProjectVersionStatus.present.js
The URL for the migration instructions was wrong, the right URL is in place now.
Closes #1213 
/deploy
=> fix: url for manual migration instructions changed

client/src/file/File.container.js, client/src/utils/Markdown.js
When markdown has a file inside it breaks because of the new threshold variable.
I set this for markdown. Another option would be to use a default threshold variable for all file previews instead.
Example:
https://dev.renku.ch/projects/virginiafriedrich/project-11
/deploy
=> fix: mardown breaks when it has a file inside

client/src/file/File.container.js
Some non-lfs files were mistakenly considered as lfs, preventing the preview.
Compare:
- https://dev.renku.ch/projects/lorenzo.cavazzi.tech/csci-e-88b-2021-problem1/files/blob/notebooks/git_lfs.ipynb
- https://renku-ci-ui-1242.dev.renku.ch/projects/lorenzo.cavazzi.tech/csci-e-88b-2021-problem1/files/blob/notebooks/git_lfs.ipynb
/deploy
=> fix: test lfs status properly on the preview

client/src/dataset/Dataset.present.js, client/src/dataset/DatasetFunctions.js, client/src/dataset/Datasets.test.js, client/src/dataset/list/DatasetList.container.js, client/src/dataset/list/DatasetList.present.js, client/src/dataset/list/DatasetList.state.js, client/src/project/datasets/DatasetsListView.js
There was a bug in dataset search that was not ordering datasets per imported date.
I revised the way we handle dates in datasets to display it in a more accurate way.
**Datasets Search**
We get from the KG "date" we check if the dataset was published or not (we do this by checking if it has a datePublished or not) we display "Published date" or "Created date" and the date.
**Dataset Display**
For datasets inside projects:
- Datasets created in renku: Inside projects we get created_at from the core service we map this to created
- Imported datasets: we get datePublished from the KG and we use this since we get nothing from core
For datasets inside the kg (display from search)
- Datasets created in renku have created
- Imported datasets have published date
For datasets that are not in the …
=> fix: datasets ordered by dates created

client/src/utils/Markdown.js
If markdown contains a line like this it breaks leaving the project not usable:
`# <a name="litterature-review"></a> Litterature review`
This pr fixes that.
@erbou @pameladelgado 
/deploy
=> fix: markdown with incomplete links in comments

client/src/project/list/ProjectList.container.js, client/src/project/list/ProjectList.present.js
* Use the `full_path` property for the project links to prevent failure with subgroups.
* Prevent showing the `Filter by` section to anonymous users since they can't change it.
/deploy
fix #1248
=> fix: use full_path in projects list

client/src/notebooks/Notebooks.container.js
The current notification for the environment creation is not very useful because it notifies the user when the creation API invocation is successful, not when the environment is available (i.e. the user still needs to wait before using the environment).
This PR removes it. We can revive that once we will get the information about the ready environment.
P.S. Notice that the notification for a failure is still shown. We don't need to wait for any further information in that case.
/deploy
=> refactor: remove environment notification

client/src/dataset/Dataset.container.js, client/src/dataset/Dataset.present.js
Adds a 404 page when the dataset doesn't exist or the user doesn't have access (currently, the access control is not yet enforced by the APIs).
It's similar to the 404 project page when the user is trying to access `/datasets/<id>`, while it's a simpler message when trying to access datasets in a project page.
**Hot to test**: try to access non-existing datasets as anonymous or logged user
1. PR: https://renku-ci-ui-1258.dev.renku.ch/datasets/fake-id
DEV: https://dev.renku.ch/datasets/fake-id
2. PR: https://renku-ci-ui-1258.dev.renku.ch/projects/lorenzo.cavazzi.tech/dataset-test-project-copy/datasets/fake-id
DEV: https://dev.renku.ch/projects/lorenzo.cavazzi.tech/dataset-test-project-copy/datasets/fake-id
/deploy
fix #1003
=> fix: fail gracefully when a dataset is missing

client/src/api-client/dataset.js, client/src/api-client/index.js, client/src/api-client/project.js, client/src/dataset/Dataset.container.js, client/src/project/Project.state.js
This routes all the knowledge-graph API through the gateway using the prefix `/api/kg`
Since it requires SwissDataScienceCenter/renku-gateway#382 , I manually created a deployment to test it
https://lorenzotest.dev.renku.ch
/deploy
fix #1053
=> refactor: route all the kg requests through the gateway

client/package-lock.json, client/package.json, client/src/project/new/Project.style.css, client/src/project/new/ProjectNew.present.js
~That was not planned for this sprint but~
I was checking something on bootstrap and I accidentally found the `custom-select` class to style an input element as a dropdown.
Sadly, I had to re-implement the same styling because the Autosuggest element has a minor bug preventing adding a class on the main `input` element when untouched.
/deploy
fix #1271
=> refactor: add dropdown indicator on autosuggest

client/src/dataset/Dataset.present.js, client/src/landing/NavBar.js, client/src/notebooks/Notebooks.present.js, client/src/notebooks/Notebooks.test.js, client/src/project/Project.present.js, client/src/project/new/ProjectNew.present.js, client/src/project/new/ProjectNew.test.js, client/src/utils/url/Url.js
While working on #1194 , I had to update the login mechanism to preserve the query parameters on the return URL.
I decided to split this out to simplify testing and merging separately.
/deploy
re #1194
=> refactor: update login to preserve query params

client/src/notebooks/Notebooks.present.js
Minor change: adds the "copy to clipboard" icon to the image source URI in the popover on the interactive environment row status.
/deploy
=> refactor: add copy to clipboard on registry popover

client/src/api-client/instance.js, client/src/project/new/ProjectNew.container.js, client/src/project/new/ProjectNew.present.js
This PR fixes the following:
- Keep the original project name as default when clicking on the `Fork` button.
- Fetch namespaces recursively: now we handle up to 1'000 namespaces -- even though the UX with >50 is not great.
- Automatically select the user namespace if available.
Pinging @rokroskar to verify the last 2 points.
/deploy
fix #1294
=> Update project fork: default name and namespace handling

.github/workflows/test-and-ci.yml
Fixes this error https://github.com/SwissDataScienceCenter/renku-ui/runs/2276583841
It has been tested on #1300 with this successful result https://github.com/SwissDataScienceCenter/renku-ui/runs/2276677109
=> ci: provide chart name when publishing chart

server/Dockerfile
Reduces the footprint of the ui-server chart
**How to test**: Query the `GET /ui-server` endpoint and verify it returns a valid response
fix #1091
=> ci: use a smaller footprint image in docker

.github/workflows/test-and-ci.yml
The charts and images are created together, but the `update-component-version` considers each component separately ( SwissDataScienceCenter/renku#2059 ).
This change manually opens another PR in the Renku repository for bumping the ui-server component on new tags
=> ci: create ui-server pr for bumping version

client/package-lock.json, client/package.json, client/src/model/RenkuModels.js, client/src/project/new/ProjectNew.container.js, client/src/project/new/ProjectNew.present.js, client/src/project/new/ProjectNew.state.js, client/src/project/new/ProjectNew.test.js, client/src/utils/HelperFunctions.js, client/src/utils/UIComponents.js, client/src/utils/url/Url.js
Manage metadata from the query paramaters on the "create project page" to automatically fill in some inputs. Thin included the pieces to generate the URL and to read the data:
* Generate URL: click on the dropdown button "share link" to open a modal with the encoded URL. The user can decide which inputs to include in the metadata (screenshot 1).
* Read metadata: detect and read the metadata from the query parameters. The URL resets back to the basic one, then the data are gradually fetched and restored automatically (screenshot 2). Any error (e.g. unexisting template) or warning (e.g namespace unaccessible) will appear on top (screenshot 3).
For testing purposes, you can easily generate the encoded content of the `data` param by using `btoa` and `JSON.stringify` from the browser console …
=> Read encoded metadata from the URL when creating new project

client/src/notebooks/Notebooks.state.js, client/src/notebooks/Notebooks.test.js
The UI now supports both the new and the previous environments options section name in the renki.ini file .
This problem should not exist anymore once #1114 will be implemented.
/deploy
fix #1306
=> fix: update environments section name

client/src/file/File.container.js
_(from offline discusison https://swiss-data-science.slack.com/archives/G67N59QL8/p1615489091082400 )_
Preview the following hidden files: .dockerignore, .gitattributes, .gitkeep, .gitignore, .renkulfsignore
/deploy
=> feat: add preview for common hidden files

.github/workflows/acceptance-tests.yml
Integrates the support for reading a command provided after the `/deploy` string.
It's possible to specify components versions (e.g. a tag `renku-core=v0.14.0` or a branch `renku-notebooks=debug-with-vscode-k8s`)) and provide a `#notest` switch to turn off the acceptance tests
re SwissDataScienceCenter/renku#1959
/deploy #notest renku-core=v0.14.0 renku-notebooks=debug-with-vscode-k8s renku=6435400de6e5d79798c75f8112289880805e2e34
=> Support deploy command for specifying components versions

client/src/landing/NavBar.js, client/src/notebooks/Notebooks.css, client/src/project/Project.css, client/src/project/Project.present.js, client/src/project/overview/ProjectOverview.present.js, client/src/project/status/ProjectVersionStatus.present.js, client/src/styles/bootstrap_ext/_button.scss, client/src/styles/bootstrap_ext/_nav.scss, client/src/styles/bootstrap_ext/_underline_pill_nav.scss, client/src/styles/index.scss, client/src/utils/Commits.css, client/src/utils/Commits.js, client/src/utils/UIComponents.js
Header redesigned... this is a proposal, might make project path and description with a lighter font or in italics.
Decided to move the project visibility like a tag, but I'm not sure this is the best. I thought next to the title it didn't look so good.
This doesn't shrink well but will fix it once we like the design for it unshrinked
Menu...
Readme
Stats
Commits
Status
/deploy
=> feat(design): project header nav and overview redesigned

.github/workflows/acceptance-tests.yml
It seems that the CI tests are often failing due to a 40 minutes timeout in the `helm test` command.
We should increase that, as already done in the main renku repository SwissDataScienceCenter/renku#2041
/deploy
=> ci: increase helm test timeout

client/src/project/new/ProjectNew.state.js
This happens sometimes when the project creation process started from a link with embedded metadata.
E.G. https://dev.renku.ch/projects/new?data=eyJ0aXRsZSI6InRlc3QgcHl0aG9uIHRlbXBsYXRlIDAuMTQuMiIsInVybCI6Imh0dHBzOi8vZ2l0aHViLmNvbS9Td2lzc0RhdGFTY2llbmNlQ2VudGVyL3Jlbmt1LXByb2plY3QtdGVtcGxhdGUiLCJyZWYiOiJ1cGRhdGUtcmVua3UtdjAuMTQuMiIsInRlbXBsYXRlIjoiQ3VzdG9tL3B5dGhvbi1taW5pbWFsIn0%3D
Compare with https://renku-ci-ui-1325.dev.renku.ch/projects/new?data=eyJ0aXRsZSI6InRlc3QgcHl0aG9uIHRlbXBsYXRlIDAuMTQuMiIsInVybCI6Imh0dHBzOi8vZ2l0aHViLmNvbS9Td2lzc0RhdGFTY2llbmNlQ2VudGVyL3Jlbmt1LXByb2plY3QtdGVtcGxhdGUiLCJyZWYiOiJ1cGRhdGUtcmVua3UtdjAuMTQuMiIsInRlbXBsYXRlIjoiQ3VzdG9tL3B5dGhvbi1taW5pbWFsIn0%3D
fix #1324
=> fix: prevent ui crashes after project creation

server/package-lock.json, server/package.json, server/run-telepresence.sh, server/src/index.ts, server/src/routes/index.ts
* Add tools for debugging when running through Telepresence
* Add libraries for supporting WebSockets and update the ones already available
* Lint code with the current rules (prevents warnings from ESlint in editors like VScode)
This is a preparation for #1264 , but it doesn't specifically address that issue.
**HOW TO TEST**: clone this branch locally, run `npm install` on the `/server` folder, and start telepresence using the `/server/run-telepresence.sh` script. It will show instructions on how to run in debug mode and how to set the configuration file in VScode to use the integrated remote bedugging for NPM.
=> Add debugging tools to uiserver

client/src/notebooks/Notebooks.present.js, client/src/project/Project.present.js, client/src/styles/icons/icons.scss
Deleted side tabs, so now when you enter environments inside projects you see this...
Form switch fix...
Shall we delete the info message?
Shall we make the width of all forms be 12 (max)?
/deploy
=> feat(design): small fixes for environments inside projects

.github/workflows/acceptance-tests.yml, README.rst, helm-chart/renku-ui-server/templates/deployment.yaml, helm-chart/renku-ui-server/templates/hpa.yaml, helm-chart/renku-ui-server/values.yaml
This should set the autoscaling for the UI server component.
Something is probably wrong because I tried to enable the policy and to load the UI server pod CPU to >50%, but it doesn't spawn a second pod. Maybe @ableuler could help?
fix #1092
/deploy
=> build: set autoscaling for uiserver

client/src/api-client/test-client.js, client/src/dataset/Dataset.present.js, client/src/dataset/DatasetFunctions.js, client/src/dataset/Datasets.test.js
Replace the `isPartOf` property with `usedIn` on the query `GET /knowledge-graph/datasets/:id` as request from the KG team.
/deploy
fix #1275
=> refactor: update property on datasets kg query

client/src/notifications/Notifications.css, client/src/notifications/Notifications.present.js, client/src/project/Project.present.js, client/src/project/list/ProjectList.present.js, client/src/styles/bootstrap_ext/_button.scss
Redesign of notifications.
For preview go to the new dataset form (test notifications are triggered here)
Bold text looks blurry but this should be fixed with fonts added to a different PR.
Toasts
Menu
List
/deploy
=> feat(design): notifications redesign

client/src/project/Project.present.js, client/src/project/list/ProjectList.present.js
The GitLab description field is now translated to HTML when it contains markdown.
The first commit addresses the project overview page (it also changes a bit the header layout, see screenshots), while the second changes the preview in the project list.
**How to test**: try to search for some projects with a description and open the overview page.
E.G. https://dev.renku.ch/projects/lorenzo.cavazzi.tech/test-comment
Here are a few screenshots: on the left the updated version, on the right the previous one.
* PROJECT HEADER - large page
* PROJECT HEADER - small page
* PROJECT LIST
/deploy renku=ui-design-test-fix
fix #1346
=> Handle markdown in GitLab description

client/src/file/File.container.js, client/src/file/File.present.js, client/src/project/Project.present.js, client/src/project/filestreeview/FilesTreeView.js
This PR changes the behavior when clicking on folders in the file browser: if the user is visualizing the lineage, it changes the address and fetches the folder's lineage. This doesn't happen when browsing the files.
Mind that it contains a (raw) mechanism to prevent showing a `404` message when trying to visualize a folder in "file mode" -- that may happen when the user switches from the lineage of a folder to the file visualization (this was possible even before this PR, but it's likely to happen more frequently now).
**How to test**: try with a project having lineage on folders. Here is an example (navigate to `data` subfolders and then out):
https://renku-ci-ui-1356.dev.renku.ch/projects/lorenzo.cavazzi.tech/imagej/files/lineage/data/step-1
/deploy renku=ui-design-test-fix
fix #1342
=> feat: show lineage on folders

client/src/api-client/project.js, client/src/project/Project.present.js, client/src/project/new/ProjectNew.container.js, client/src/project/new/ProjectNew.present.js
This improves the UX when a non-fatal error occurs while forking (i.e. the pipeline or webhook creation fails)
**How to test**: it's a bit tricky. The easiest way is running telepresence on the PR environment and manually modifying the code in the `client.forkProject` function to trigger the error on the target API (try with the main fork API, then with `runPipeline` and `createGraphWebhook`)
P.S. mind that the error message is slightly different than the suggested one, to keep it coherent with the other cases. Feel free to suggest changes if it's not clear (or change it directly in the PR).
/deploy renku=ui-design-test-fix
fix #1341
=> feat: handle non blocking errors on fork

client/src/project/Project-Route.test.js, client/src/project/Project.js
Fix #1257
Namespaces that start with numbers are now correctly handled.
Compare the following:
New: https://renku-ci-ui-1359.dev.renku.ch/projects/123testgroup/testing-project
Old: https://dev.renku.ch/projects/123testgroup/testing-project (endless spinning wheel)
New: https://renku-ci-ui-1359.dev.renku.ch/projects/123testgroup/987test-project
Old: https://dev.renku.ch/projects/123testgroup/987test-project (endless spinning wheel)
If you wish, create new project in a namespace that starts with a number and see that you get properly redirected to the project after it is created.
/deploy
=> fix: handle namespaces that start with numbers

client/src/dataset/Dataset.container.js, client/src/dataset/Dataset.present.js
@rokroskar found a bug when accessing datasets in the dataset search.
When accessing a dataset for a second you can see an "error unknown" sign, this was due to a bag if, this has been fixed.
To test you can search for datasets and open one.
Do the same in this deployment and the error shouldn't be there.
I removed an unnecessary call to the core service that was also failing since it was trying to fetch a dataset outside a project.
/deploy
=> fix: remove flash error when loading datasets

.github/workflows/acceptance-tests.yml, .github/workflows/test-and-ci.yml, client/.eslintrc.json, client/package-lock.json, client/src/App.css, client/src/notebooks/Notebooks.container.js, client/src/notebooks/Notebooks.css, client/src/notebooks/Notebooks.present.js, client/src/notebooks/Notebooks.state.js, client/src/notebooks/Notebooks.test.js, client/src/notebooks/index.js, client/src/project/Project.js, client/src/project/Project.present.js, client/src/utils/UIComponents.js, client/src/utils/url/Url.js
Embed running sessions in RenkuLab using an `<iframe>`, allowing use to also access logs and docs on the same page.
From the test environment, it seems that SwissDataScienceCenter/renku-notebooks#606 is not a requirement since the iframe's content is loaded correctly even without that PR.
/deploy renku=ui-design-test-update-iframe
fix #1220
=> feat: show environments in iframe

client/src/dataset/list/DatasetList.container.js, client/src/dataset/list/DatasetList.present.js, client/src/dataset/list/DatasetList.state.js, client/src/project/list/ProjectList.present.js, client/src/utils/List.js, client/src/utils/UIComponents.js
I created a List component that receives a list of items with different fields and maps them to a grid or list (depending on what the user wants).
It looks like the project grid, there is a benefit here... if we want to implement a generic search in the KG (for projects, datasets, etc) we could use this generic component to display a list of mixed elements.
I applied this to datasets and projects. I see the project row is used in the landing page as well, we could delete this code after we adapt the landing page to using this.
=> feat(design): generic component to map items into a list applied to projects and datasets

client/src/collaboration/lists/IssueList.present.js, client/src/collaboration/lists/MergeRequestList.present.js, client/src/dataset/list/DatasetList.present.js, client/src/project/datasets/DatasetsListView.js, client/src/project/list/ProjectList.present.js, client/src/styles/icons/icons.scss, client/src/utils/HelperFunctions.js, client/src/utils/List.js
We decided that each entity has a color, this will be useful when we have different entities returned by the same search results.
Green --> projects
Pink --> datasets
Yellow --> collaboration (until the tab is replaced by the iframe)
Closes #1376
=> feat(design): use of colours to identify entities

client/src/api-client/notebook-servers.js, client/src/api-client/project.js, client/src/landing/NavBar.js, client/src/model/RenkuModels.js, client/src/notebooks/Notebooks.present.js, client/src/notebooks/Notebooks.state.js, client/src/notebooks/Notebooks.test.js, client/src/project/Project.js, client/src/project/Project.present.js, client/src/project/Project.state.js, client/src/project/settings/ProjectSettings.container.js, client/src/project/settings/ProjectSettings.present.js, client/src/project/settings/ProjectSettings.test.js, client/src/project/settings/index.js, client/src/project/shared/ProjectAvatar.container.js
_INFO: ready to review, but the `pinned image` is still missing and will be added soon_
The project settings are now split in 2 pages, where `General` contains the previous settings and `Sessions` allows the logged users to:
* Check the project and RenkuLab options and default values
* Allor user with > developer permissions to change the options according to the values supported on RenkuLab
**Changes/discrepancies with the original issue**
- Change multiple values and confirm later: I tried using different colors to distinguish current settings vs yet-to-be-applied changes. The result was very confusing. I opted for applying any change directly on click. The UX looks much easier, even though we may get extra commits.
- Set arbitrary values: I tried to add an "unlock values" option to …
=>  feat: edit project sessions settings

client/src/dataset/Dataset.present.js, client/src/dataset/list/DatasetList.present.js, client/src/help/Help.present.js, client/src/notebooks/Notebooks.present.js, client/src/project/Project.css, client/src/statuspage/Statuspage.present.js, client/src/styles/bootstrap_ext/_button.scss, client/src/utils/UIComponents.js
change to text size in help page
fix to menu in environments
Pagination now looks like:
Warning sign style:
before
after
Dataset details table has less spacing 
before
after
Action buttons in datasets are now green
Closes #1367
=> fix(design): small fixes to the UI design

client/src/project/list/ProjectList.present.js, client/src/styles/components/_renku_search.scss, client/src/utils/List.js
Rok asked me to do this change... instead of slug we display the project title inside the search result. The slug is displayed but smaller.
Possible changes:
- Make description and slug the same size
- In case there is space in the card put the slug under the title
=> feat(project): title and slug in search result

client/src/project/settings/ProjectSettings.present.js
This adds a link on the image session setting to the container registry page in GitLab.
P.S. the screenshot may look slightly different than the preview because it includes the changes to the buttons from #1403 
=> feat: add link to registry images

client/src/notebooks/Notebooks.container.js
Remove the duplication on notebooks options that could be tested to false.
That may happen when receiving the number `0` as one of the possible values.
**How to test**: This would require a deployment with GPUs. One way to manually fake it would be to add the following code before the `return data;` at line 82 in the file "client/src/api-client/notebook-servers.js" 
```
data = {
...data, gpu_request: {
"default": 0,
"displayName": "Number of GPUs",
"options": [
0,
1,
2
],
"order": 5,
"type": "enum"
}
};
```
fix #1122
=> fix: prevent duplication of falsy options

client/src/file/Lineage.present.js
https://dev.renku.ch/projects/lee.gavin.k/plurilingue/files/lineage/outputs/num.txt
=> feat: extend the list of extensions for code files in lineage display

client/src/notebooks/Notebooks.container.js, client/src/notebooks/Notebooks.present.js, client/src/project/settings/ProjectSettings.present.js
Four cases to test:
1. Pinned image: https://renku-ci-ui-1418.dev.renku.ch/projects/cramakri/pinned-image-test (should start smoothly)
2. Slow build: https://renku-ci-ui-1418.dev.renku.ch/projects/renku-qa/slow-build (should start smoothly if image has built)
3. Slow build: https://renku-ci-ui-1418.dev.renku.ch/projects/renku-qa/slow-build (should show warning if image is building)
4. Broken build: https://renku-ci-ui-1418.dev.renku.ch/projects/renku-qa/broken-build (should show warning)
=> Fix start button behavior for projects with pinned images

client/src/notebooks/Notebooks.container.js
A previous fix introduced a worse bug that shows duplicate values whenever a user picks a non-stringy value in a session enumeration. This PR fixes it.
Thank you @gavin-k-lee for reposting it!
fix #1436
=> fix: prevent values duplication for session enum

client/src/landing/NavBar.js
Clicking on the logo used to reload the application because a standard anchor element was used instead of a react `<Link>`.
This PR fixes it.
**How to test**: browse to any page (e.g. `/projects`) and try to go back to the home by clicking on the logo. Compare the behavior with that on https://dev.renku.ch
=> fix: use link on the logo to prevent reload

client/src/api-client/dataset.js, client/src/dataset/Dataset.present.js, client/src/project/Project.present.js, client/src/project/datasets/change/DatasetChange.container.js, client/src/styles/bootstrap_ext/_button.scss, client/src/utils/formgenerator/fields/ImageInput.js
When a dataset is created or edited it could happen that this succeeds but the file add function fails.
When this happens the error is not managed properly, a message is displayed making the user think that the entire operation failed.
This fix provides the user with a better picture of what happens.
1. If the dataset is created but the file add fails,  we redirect the user to the dataset and show an error message.
2. If the dataset is edited but the file add fails,  we show the user a message allowing them to retry on spot (no redirection necessary).
1-To make things fail: api-client/dataset.js --> line 227 make "name" become "namee" (example)
2-Add a dataset (you can see the error message), then edit a dataset (to see the error message on edit)
Closes #1077
=> fix(datasets): proper error handling when dataset add fails

client/src/notebooks/Notebooks.present.js
Things look like this now
I feel like there is a lot of information there and a lot has bold/underline information, i could try and clean up a bit this bar to make the actions stand out a bit more if desired.
I don't really like the icon we are using on links and i also feel it should go at the end of the text instead of at the beginning.
Closes #1400
=> feat: open in new tab in sessions is now more visible

client/src/notebooks/Notebooks.present.js
When an image is not available but then becomes available the "no image available" sign fades.
I also added a message (because of the comment linked to the issue) to tell users the image is not available.
The message has a link to expand info on top (When it's not expanded).
Closes #1448
=> fix(sessions): improvements to messagging when no image is available

client/src/App.js, client/src/Maintenance.js, client/src/model/RenkuModels.js, client/src/user/User.state.js
This adds a very basic warning page when GitLab is not available.
We could try to fetch the data from StatusPage and verify if a maintenance is ongoing, and provide a better feedback to the user.
**Hot to test**: the only way is to trigger an error in the `GET /user` API.
Running telepresence to modify the `client.getUser` function in "client/src/api-client/user.js" is the easiest option.
fix #805
=> feat: show error page when gitlab is not available

client/src/App.css, client/src/utils/HelperFunctions.js
The addition of the `text-break` class on the `<RenkuMarkdown>` component ([Link](https://github.com/SwissDataScienceCenter/renku-ui/blob/713770f670468ff1675fb165c028a00050b1c4f0/client/src/utils/UIComponents.js#L476)) accidentally broke the way column width is computed in tables.
This fix restores the normal word break behavior on tables.
You can use the example in the reference issues. A better test would be creating on the fly a project where the README has a markdown table with 3-4 columns, where all of them contain just a (long-ish) word expect one that contains a long text.
Without the fix (i.e. on dev) the column with a single word should be very narrow, while this PR should display something more reasonable.
Here is an example from the reference issue
/deploy
fix …
=> fix: restore columns auto width in markdown tables

client/src/dataset/Dataset.present.js
This PR is an attempt to fix the broken links we would have once we won't get the `name` property for the files from the KG datasets API. We can merge it now since it still uses the `name` property when available, and it derives it from `atLocation` otherwise.
In the end I followed the suggestion in #1497 , although a cleaner solution may be desirable.
We should consider refactoring the `FileExplorer` component that has grown way too much, handling generic file trees, lineage, dataset files [...] despite the different object properties. An abstraction layer would greatly simplify handling minor changes like the current one.
/deploy
fix #1497
=> refactor: derive name on dataset files when missing

client/package-lock.json, client/package.json, client/src/utils/HelperFunctions.js
Since we already use [highlight.js](https://www.npmjs.com/package/highlight.js) for highlighting syntax in code files, and [Showdown](https://www.npmjs.com/package/showdown) to convert Markdown to HTML, using [showdown-highlight](https://www.npmjs.com/package/showdown-highlight) allows us to highlight inline code in Markdown file with a coherent color scheme.
The library is very simple, allowing for few personalizations out of the box, but it works well as long as users specify the code language. There are other solutions but they are more complicated and they may result in a different default highlighting scheme for some languages, forcing us to create a customized common color pattern.
Example:
- New: https://renku-ci-ui-1534.dev.renku.ch/projects/lorenzo.cavazzi.tech/readme-file-dev
- …
=> feat: highlight code syntax in markdown files

client/src/statuspage/Statuspage.present.js
**The message appears as expected**
**The component listing does not show "Loud"**
/deploy
=> feat: filter out the internal Loud component from the list

client/src/notebooks/Notebooks.present.js
- Move the stop option to the end of the list to avoid click problems.
- Refactor the NotebookServerRowAction component to be a functional component and use memo to avoid rendering that component if the props have not changed and it is already rendered, the component was rendered for each session state request.
Fix #1545
/deploy renku=ui1337-uiserver-values
=> refactor: Rearrange session menu options (#1545)

client/src/dataset/list/DatasetList.container.js, client/src/dataset/list/DatasetList.present.js, client/src/dataset/list/DatasetList.state.js, client/src/model/RenkuModels.js
Added cancellation of dataset search when a search is already in progress, which prevents the input from being used for new searches when a new one is still running. The user can cancel the current one.
Included searchId to show only the results of the current search.
/deploy renku=ui1337-uiserver-values
=> feat: Add cancel datasets search (#1352)

.github/workflows/test-and-ci.yml, .gitignore, chartpress.yaml, client/.eslintrc.json, client/Dockerfile, client/craco.config.js, client/docker-entrypoint.sh, client/package-lock.json, client/package.json, client/run-telepresence.sh, client/src/api-client/environment.js, client/src/api-client/index.js, client/src/index.js, client/src/landing/AnonymousHome.js, client/src/landing/NabBarWarnings.js, client/src/landing/NavBar.js, client/src/landing/TransitionalHome.js, client/src/model/GlobalSchema.js, client/src/model/RenkuModels.js, client/src/styles/components/_renku_home.scss, client/src/utils/formgenerator/fields/FileUploaderInput.js, client/src/utils/quicknav/QuickNav.present.js, helm-chart/renku-ui-server/values.yaml, helm-chart/renku-ui/values.yaml, server/Dockerfile, server/src/authentication/index.ts, server/src/authentication/routes.ts, server/src/config.ts, server/src/routes/apis.ts, server/src/routes/index.ts
This PR solves the various problems around users accidentally working on outdated UI versions after a new release.
Please check the following ~annoying~ verbose explanations for the details.
**UI client build**
We use `react-scripts` to automate a few operations around starting the development server and compiling/bundling the code.
One limitation is the opinionated use of webpack, that makes adding customization difficult.
I used [this library named craco](https://github.com/gsoft-inc/craco) as a drop-in replacement that still invokes `react-script` (it's a drop-in replacement) but also allows to easily changes webpack config files.
The production-ready bundled JS files now include in the filename the last commit short sha, invalidating any cached file on new releases.
**UI versions** …
=> Simplify refreshing the UI after publishing new RenkuLab versions

.github/workflows/acceptance-tests.yml, CHANGELOG.md, chartpress.yaml, client/package-lock.json, client/package.json, helm-chart/renku-ui-server/Chart.yaml, helm-chart/renku-ui-server/values.yaml, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Bugfix release to prevent accidentally showing the "new version" banner after a release where the last commit didn't touch an "essential" file (i.e. not in the server, client, or helm_chart folder).
=> 1.2.1 bugfix

client/src/api-client/errors.js, client/src/api-client/index.js, client/src/api-client/utils.js, client/src/index.js, server/src/config.ts, server/src/logger.ts, server/src/routes/apis.ts, server/src/utils/index.ts, server/tests/utils/index.test.ts
This PR routes all the UI client API through the UI server.
It handles also the credentials expirations (e.g. tokens not refreshable anymore) by adding a specific header that the client reads and uses to redirect to the login page. This should happen very rarely and it's similar to the current behavior.
Should we want a different UX, we could redirect to a new UI page where we explain what happened and suggest to re-login.
P.S. Mind that the expired credentials also cause the invoked API to return a `500` message. This prevents very weird behaviors, happening when GitLab APIs respond with a `30x` code. The browser (at least Firefox) doesn't re-read the headers, causing an infinite login loop.
* Keep the network tab open and verify the APIs go through …
=> Route all requests to APIs through UI server

client/src/project/new/ProjectNew.present.js, client/src/project/new/ProjectNew.state.js
This PR implements the UI side to support template variables metadata, keeping backward compatibility with old template repositories.
The input elements bound to variables are now styled based on the underlying type, and enumerations are presented as dropdowns. Mind that there are differences between different browsers --  we can implement customization if needed.
The default value is pre-filled, unless a different value is otherwise defined (e.g. when sharing project creation links containing pre-filled data).
This is a sample template repository where variables have metadata: https://dev.renku.ch/gitlab/lorenzo.cavazzi.tech/core-it-template-variable-test-project
If the reviewer wants to try some variations of that templates repo, the available metadata are: …
=> Support template variables metadata

client/src/file/File.container.js, client/src/file/File.present.js, client/src/file/File.test.js, client/src/notebooks/Notebooks.present.js
There were a few issues with the `CheckNotebooksStatus` component, leading to different results based on a few factors (status of the sessions, user default branch already loaded when browsing the file, ...)
This should restore the previous behavior, and correct the wrong links.
With #1345, the feature will become more useful since it will be possible to identify the "correct" commit for the session instead of checking the latest
/deploy
fix #1606
=> fix(client): show the correct session status on notebooks preview

client/src/statuspage/Statuspage.present.js
Added sorting by schedule date in the maintenance summary.
Tested in Chrome, Safari and Firefox browsers.
Closes #1609 
/deploy ui.statuspage=lhwy5ln8yrnn
=> fix: Order maintenance by schedule date asc

client/src/project/status/MigrationUtils.js, client/src/project/status/ProjectVersionStatus.present.js, client/src/project/status/RenkuVersionStatus.present.js
This PR shows an estimate of the migration time **if** the user is a member of the project and the project is being updated to metadata version 9. The first restriction is because the computation requires knowing the number of commits and that information is only available if the user is a member of the project. The second restriction is because the method of estimating only works for projects migrating to metadata version 9.
Here are some projects that can be used to test:
- https://renku-ci-ui-1621.dev.renku.ch/projects/cr-migration-test/project-with-core-1-0-1-group-v2/ (no estimate shown, since project is already on metadata v. 9)
- https://renku-ci-ui-1621.dev.renku.ch/projects/cr-migration-test/test-8 (estimate shown, since project can be updated to v9 automatically)
- …
=> Present estimate of migration duration

client/src/project/Project.state.js
Forked information is now correctly set when navigating to a new project.
Go to 
- https://renku-ci-ui-1633.dev.renku.ch/projects/lorenzo.cavazzi.tech/covid-19-forecast
Click on the "forked from" link
See that the fork information is correctly displayed.
Compare with the description in #1625
Fix #1625
/deploy renku=0000-project-version renku-graph=cli-v1 renku-core=v1.0.1
=> Correctly set forked information

client/src/api-client/migration.js, client/src/dataset/Dataset.present.js, client/src/dataset/addtoproject/DatasetAdd.container.js, client/src/project/Project.js, client/src/project/Project.state.js, client/src/project/Project.test.js, client/src/project/status/ProjectVersionStatus.present.js, client/src/project/status/RenkuVersionStatus.present.js, client/src/project/status/TemplateVersionStatus.present.js
This is a follow-up to #1507 , currently separate because it requires a backend release to remediate SwissDataScienceCenter/renku-python#2541
In short, it allows anonymous users to invoke renku-core APIs (where currently supported) by switching to using git_url + branch for migrations instead of project_id.
Anonymous users can also access project version information, getting limited access (only "up-to-date" / "outdated").
Here is the comparison
/deploy renku=1.0-next renku-graph=cli-v1 renku-core=0000-disbale-check-migration-optimization
re #1507
=> feat(client): add migrations for anonymous users

client/src/api-client/project.js, client/src/dataset/Dataset.container.js, client/src/dataset/Dataset.present.js, client/src/dataset/addtoproject/DatasetAdd.container.js, client/src/project/shared/Projects.state.js
This fixes a bug spotted by @gavin-k-lee that prevents datasets to be added to projects.
**How to test**: look for a dataset using the dataset search, open any and click on the "Add to project" button on the top right.
The user should be able to look for a project again and import the dataset (if the target project is up-to-date).
Trying the some on dev won't work -- the user won't even be able to select a target project.
P.S. We should probably check also the source project version. That may not be straightforward in the current implementation.
I would suggest re-working a bit the "add to project" logic, removing the overcomplicated FormGenerator Autosuggest (it's half-bugged, not checking for the input data to be available and not filtering some unusable target projects), adding the …
=> fix(client): restore projects data used by datasets

client/.eslintrc.json, client/src/api-client/notebook-servers.js, client/src/file/File.container.js, client/src/model/RenkuModels.js, client/src/notebooks/Notebooks.container.js, client/src/notebooks/Notebooks.present.js, client/src/notebooks/Notebooks.state.js, client/src/notebooks/SessionCheatSheet.js, client/src/project/Project.js, client/src/project/Project.present.js, client/src/project/Project.state.js
This PR implements most of the changes from #1345 , except the visual changes to the commits info in the dropdown menu.
There are a few additional changes to simplify selecting an already running session for a target branch.
In short, these are the changes:
* Get and delete autosaves.
* Select new session commit based on autosaves and running sessions.
* Update CheckNotebookStatus component to support per-branch sessions.
Start a session on any project (possibly from last - 1 or -2 commit), do some work, and stop the session.
You should now have an autosave. If you try to start a session again, you should see some info when trying to select a branch/commit (P.S. this is silent unless you click on "select branch/commit/..." -- see screenshots below).
Notice that the older …
=> feat(client): support session autosaves

client/src/api-client/environment.js, client/src/api-client/instance.js, client/src/api-client/job.js, client/src/dataset/addtoproject/DatasetAdd.container.js, client/src/project/datasets/change/DatasetChange.container.js, client/src/project/datasets/import/DatasetImport.container.js
The URL for jobs API doesn't include the version. This causes problems when adding/editing datasets on projects with an older metadata version (specifically, the answer from the job APIs is `undefined` cause it's querying the wrong service).
**How to test**: Use an older project with metadata V8, and try to add a datasets (E.G. clone `ralf.grubenmann/test-8`)
/deploy renku=1.0-next renku-graph=development renku-core=release/v1.0.3
re SwissDataScienceCenter/renku-python#2604
=> Add version to the job APIs URL

client/src/notebooks/Notebooks.container.js, client/src/notebooks/Notebooks.present.js, client/src/notebooks/Notebooks.state.js
This PR handles missing pipelines by:
* Displaying the correct warning (missing docker image) when trying to start a new session
* Adding a "Build branch image" button.
The latter tries to build an image when there is no pipeline. Mind that it works only per-branch, not per commit https://docs.gitlab.com/ee/api/pipelines.html#create-a-new-pipeline
It also harmonizes the messages and buttons showed on non-available images.
/deploy renku=1.0-next
fix #1667
=> feat(client): handle missing pipelines

client/src/dataset/Dataset.present.js
Look at the dataset view on https://dev.renku.ch and see that projects are not displayed there. Compare with the PR deployment were projects are shown.
=> Use the new usedIn field to get dataset projects

client/src/dataset/addtoproject/DatasetAdd.container.js, client/src/dataset/addtoproject/DatasetAdd.present.js, client/src/model/RenkuModels.js, client/src/project/shared/Projects.state.js, client/src/utils/components/SelectAutosuggestInput.js, client/src/utils/components/formgenerator/FormGenerator.present.js, client/src/utils/components/formgenerator/README.md, client/src/utils/components/formgenerator/fields/SelectAutosuggestInput.js, client/src/utils/components/formgenerator/fields/index.js
This PR refactors the AddDataset component to not use FormGenerator.
This PR also includes:
+ Adding loading animation if the project list is not ready
+ Validation when the dataset project does not exist
+ Validation if the version of the dataset project is not supported
+ Validation if the version of the dataset project and the selected project are not the same
- The dataset project does not exist
- The dataset project version is not supported
- The project selected needs migration
- The project selected version is not supported 
-  The project selected version and the dataset project version has a different version
- The dataset is not activated in kg
**v8 dataset, v9 project**
**v8 dataset, v8 project**
**v4 dataset, v4 project**
=> refactor(client): do not use formGenerator to import the dataset into an existing project (#1604)

client/src/api-client/dataset.js, e2e/cypress/integration/local/projectDatasets.spec.ts, e2e/cypress/support/renkulab-fixtures/datasets.ts
This PR fixes the dataset identifiers returned from the core service to match the identifiers in the KG.
To test, look at a dataset in an older project. Before this fix, the dataset is not recognized as being in the KG, since the identifiers do not match, so the dataset cannot be added to projects and there is a warning. With the fix, the dataset is found in the KG.
**Without fix**
https://dev.renku.ch/projects/cramakri/test-8-cloned/datasets/v8-dataset/
**With fix**
https://renku-ci-ui-1716.dev.renku.ch/projects/cramakri/test-8-cloned/datasets/v8-dataset/
Fix #1694
/deploy #persist renku=000-acceptance-tests
=> feat: strip '-' from dataset identifiers

client/src/notebooks/NotebookStart.present.js, client/src/notebooks/Notebooks.container.js, client/src/notebooks/Notebooks.present.js, client/src/notebooks/Notebooks.state.js, client/src/notebooks/Notebooks.test.js, client/src/project/Project.js, client/src/utils/constants/Notebooks.js, e2e/cypress/integration/local/home.spec.ts
This PR is for refactoring the session status display with the changes in renku-notebooks [here](https://github.com/SwissDataScienceCenter/renku-notebooks/pull/898)
The session status changed from:
````
status: {
message: "containers with unready status: [jupyter-server oauth2-proxy git-proxy]" // string
phase: "Pending", // Pending, Running, Error
ready: false
reason: "ContainersNotReady"
step: "Ready"
}
```` 
To:
````
status: {
message: "Containers with non-ready statuses: git-proxy, jupyter-server, oauth2-proxy, init-certificates, git-clone." // string or undefined
state: "starting" // starting, running, stopping, failed
}
````
Error case: https://renku-ci-ui-1718.dev.renku.ch/projects/tasko.olevski/test-failing-project-1/sessions/new?autostart=1
Closes #1646 
/deploy …
=> feat(client): use simplified session state (#1646)

client/src/notebooks/NotebookStart.present.js, client/src/notebooks/Notebooks.present.js, client/src/project/Project.present.js, client/src/utils/components/Button.js
This PR redirect Notebook connects button to renku session link in the same window.
1. Launch a session with Notebooks
e.g. https://renku-ci-ui-1725.dev.renku.ch/projects/dandrea.cordoba/essm-egu-2022/sessions/new?autostart=1
2. Go to Notebook file
e.g. https://renku-ci-ui-1725.dev.renku.ch/projects/dandrea.cordoba/essm-egu-2022/files/blob/notebooks/Priestley-Taylor_equation.ipynb
3. Click in connect button, it should display the session Iframe and the link to go back to the file: 
Closes #1613 
/deploy renku=000-acceptance-tests renku-notebooks=get-all-session-logs #persist
=> feat(client): redirect Notebook connect button to session (#1613)

helm-chart/renku-ui-server/requirements.lock, helm-chart/renku-ui-server/requirements.yaml, helm-chart/renku-ui-server/templates/deployment.yaml, helm-chart/renku-ui-server/values.yaml, server/src/config.ts, server/src/storage/RedisStorage.ts
Hopefully I did this right. It is really cool that you use typescript in the ui server. I did not know this.
With this change everything the ui server needs is specified in the global redis section. So if someone brings their own redis then they do not install the redis chart bundled with renku but they fill out all stuff in global.redis. If people use the included redis then they can stick with the defaults and everything should work. If they change the defaults then the global.redis section and regular redis section need to be compatible and some values between the two will be duplicated.
**THIS IS A BREAKING CHANGE FOR THE HELM CHART**
~Please add any comments on the helm chart and its organization in the parent PR in the renku repo at …
=> feat(chart)!: use global redis

e2e/cypress/integration/local/project.spec.ts
The bug that was reported was due to the UI not being correctly updated, but this PR adds a test for the project settings page.
Fix: #1744
=> add tests for the project settings page with and without cloud storage

client/src/utils/components/progress/Progress.css, client/src/utils/components/progress/Progress.stories.tsx, client/src/utils/components/progress/Progress.tsx
Component to show the progress of a process, for example, after submitting a form.
It has two types of progress-bar Indeterminate and determinate. For the determined type the percentage value is required.
It also includes two forms of dark and light display.
The light one is recommended for use in modals.
run storybook `npm run storybook`  in the client folder
Closes #1735
/deploy renku-core=develop renku=tests-new-project-form-changes #persist
=> 1735 progress component

client/src/api-client/index.js, client/src/api-client/notebook-servers.js, client/src/notebooks/Notebooks.state.js
/deploy renku-core=develop renku=tests-rp-version renku-notebooks=chore-prepare-1.6.0-release #persist
This PR changes the faulty check for the docker image availability when a project specifies a pinned image.
Instead of using the GitLab API and accessing the project registry, it uses a new renku-notebooks API `GET /notebooks/images`
fix #1767
=> feat(client): use new api for pinned images

client/src/api-client/project.js, client/src/notebooks/NotebookStart.present.js, e2e/cypress/integration/local/newSession.spec.ts, e2e/cypress/support/renkulab-fixtures/newSession.ts
This should improve the UX when a user forks a project and something goes wrong with the pipelines.
In short:
- The pipeline API is invoked again after a short delay when it fails during a fork.
- In case of missing pipelines, the UI correctly shows the "build the branch image" button when trying to start a new session.
Here is an example of recovering from pipeline failures.
/deploy renku-core=develop renku=auto-update/renku-core-1.2.0 #persist
=> feat(client): improve error handling on missing pipelines

client/src/api-client/index.js, client/src/user/User.state.js
The fact that the server response was caused by an expired token was getting lost, so it was not possible to handle the error correctly at higher levels. This has been fixed.
Testing: Log into the Keycloak admin console and set the *SSO Session Idle* and *Client Session Idle* values to something very short (like 1 min). This will provoke more frequent auth token expirations, and you will be redirected to login, but you should not see the "RenklabDown" warning.
Fix #1759
/deploy renku=auto-update/renku-core-1.2.1 #persist
=> fix: do not show renkulab down when the users auth token has expired

server/run-telepresence.sh
Minor fix to telepresence script which only worked on ci-deployments, but not the main dev deployment.
=> minor: allow telepresence against the dev/renku deployment

helm-chart/renku-ui-server/values.yaml
Run UI server as non-root.
To keep it coherent with the other repos, we should add also `runAsGroup: 1000`, but that creates problems with telepresence v1. I can give a quick try to telepresence v2. If that works, we could upgrade
/deploy #persist 
fix SwissDataScienceCenter/renku-notebooks#1001
=> build(server): run ui-server as non-root user

client/src/utils/components/formgenerator/fields/FileUploaderInput.js, client/src/utils/components/formgenerator/fields/FileUploaderInput.stories.tsx
This PR includes the UX changes for the file upload component.
To test it go to the form to create a new dataset:
Go to Projects -> click on a project -> click on Datasets -> click on Add a dataset.
Closes #1739 
/deploy renku=1811-main-menu-changes #persist
=> feat: Update upload file component to adopt UX changes

client/src/App.js
The solution is simpler than the one suggested in the issue. We actually don't need to redirect the user since the new id is just the older one with the `-` chars stripped out.
/deploy renku=tests-new-project-form-changes #persist
fix #1819
=> feat(client): strip dash from dataset id URLs

client/src/dataset/Dataset.present.js
The dataset page should show the projects a dataset is used in, even if there is just one.
But the project dataset page should not (if there is just one).
/deploy renku=000-tests-ui-2_0-next #persist
=> fix: missing project display

client/src/model/RenkuModels.js, client/src/notebooks/NotebookStart.present.js, client/src/notebooks/Notebooks.state.js, client/src/notebooks/README.md, e2e/cypress/integration/local/newSession.spec.ts
This PR speeds up how we check for Docker image availability when starting a new session.
It prioritizes testing the Docker image, deferring checking pipelines and jobs -- doing it only when the image is missing.
This makes the logic in the UI similar to the one already used in renku-notebooks.
If no image is available, we either:
- [for anonymous users] notify the image is not available and keep checking for it
- [for logged users] check pipelines and jobs and provide adequate feedback -- showing quickfix buttons for users with permissions on the project
For pinned images, no big changes: we can't really check the pipelines in that case, so we just verify the image availability (without looping).
Ideally, the user shouldn't notice many differences. Trying to start a …
=> feat(client): speed up checking docker images availability

client/package-lock.json, client/package.json, client/src/dataset/Dataset.present.js, client/src/dataset/DatasetError.js, client/src/dataset/addtoproject/DatasetAdd.present.js, client/src/dataset/addtoproject/addDatasetExistingProject.js, client/src/dataset/addtoproject/addDatasetNewProject.js, client/src/notebooks/Notebooks.container.js, client/src/notebooks/Notebooks.present.js, client/src/project/new/ProjectNew.present.js, client/src/project/overview/ProjectOverview.container.js, client/src/project/settings/ProjectSettings.present.js, client/src/utils/components/loginAlert/LoginAlert.stories.tsx, client/src/utils/components/loginAlert/LoginAlert.tsx, e2e/cypress/integration/local/project.spec.ts
This PR adds an action button to the datasets pages making the UX more in line with logged users.
All the pages requiring anonymous users to log in now have a similar style too (see screenshots below).
P.S: the PR includes also a couple of minor bug fixes.
**Screenshots: dataset**
Logged users on the left, anonymous on the right
**Screenshots: other log-in pages**
/deploy renku=000-tests-ui-2_3_1 #persist
fix #1836
=> feat(client): add activation button to datasets page

client/src/project/datasets/change/DatasetChange.container.js
PR to send the url of the current image when updating the dataset so as not to delete the existing image.
Currently the endpoint for updating a dataset requests the url of the current image from the dataset to keep that image, otherwise it deletes the image. This is a workaround for this case, but the API should not delete the image if it is not included in the dataset object when updating a dataset.
closes #1861 
=> fix: send dataset current image url when updating the dataset (#1861)

.github/workflows/acceptance-tests.yml, CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui-server/Chart.yaml, helm-chart/renku-ui-server/values.yaml, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
End of sprint 10 Jun 2022 release.
/deploy
=> Release 2.3.2

client/src/project/datasets/change/DatasetChange.container.js
#1887 introduced an error in editing datasets that do not contain images. This PR makes dataset actions work in the following scenarios:
- Add a dataset without an image
- Add a dataset with an image
- Modify a dataset without an image
- Modify a dataset with an image
=> fix: editing datasets without images

helm-chart/renku-ui-server/values.yaml, helm-chart/renku-ui/templates/deployment-template.yaml, helm-chart/renku-ui/values.yaml
This does a few things:
- Changes the security context defaults in the values file for the server so that the "global" pod-level security context is not set but rather the container-level security context is used. We cannot set the global security context for the whole pod because it interferes with the certificates container which needs elevated permissions
- Adds a security context to the nginx server in the ui client component, this already ran as non root which is great but it still does not hurt to make the security context modifiable through the helm chart and not have it hardcoded.
=> chore(chart): modify security context

client/nginx.vh.default.conf, server/src/routes/apis.ts
* gzip proxied requests
* provide cache-control information for css, js, and, images
* turn off caching for config.json
Fix #1908 #1876
**Compression**
Make a request for content (e.g., HTML) specifying that compression is allowed.
```
curl -H "Accept-Encoding: gzip" -i https://renku-ci-ui-1914.dev.renku.ch | head -n 10
```
You should see the following headers included in the response:
```
vary: Accept-Encoding
content-encoding: gzip
```
Compare with renkulab.io:
```
curl -H "Accept-Encoding: gzip" -i https://renkulab.io | head -n 10
```
**Cache control**
Request css, images, and js and see that cache-control headers are returned:
```
curl -I https://renku-ci-ui-1914.dev.renku.ch/static/css/main.31d541f2.chunk.css
```
```
curl -I …
```
=> build: nginx configuration

client/src/notebooks/Notebooks.container.js
PR to handle error where autosave commit id of autosave is used which does not exist in project commit list.
=> fix: check if autosave commit exists in project commit list before use it

client/package-lock.json, client/package.json, client/src/App.js, client/src/dataset/Dataset.present.js, client/src/project/Project.present.js, e2e/cypress/integration/local/datasets.spec.ts, e2e/cypress/integration/local/project.spec.ts
Introduces changes to set the title tag as a user navigates through Renku.
- On a project page, the title tag is the title of the project 
- On a dataset page, the title tag is the title of the dataset
- Otherwise, the title tag is "Reproducible Data Science | Open Research | Renku"
closes #1881 
**Project**
**Dataset**
/deploy renku=tests-ui-2.5.0 #persist
=> feat: set page title to project or dataset title (#1881)

.gitignore, helm-chart/renku-ui/requirements.lock, helm-chart/renku-ui/requirements.yaml, helm-chart/renku-ui/values.yaml
The latest certificates image and chart can run as non-root.
This is safer than what we had before.
Also the chart and image tags are not tracking each other. This is on purpose.
Lastly, the `.lock` file is not needed to be tracked in git. We always pin the requirements versions so this is not necessary to check into git and keep updating.
/deploy renku=000-ui-server-chart #persist
=> chore: run ca cert injection as non-root

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
New version of the UI
/deploy renku=000-fix-acceptance-tests #persist
=> build: release 2.6.0

client/src/api-client/notebook-servers.js
Use new notebook server error format
rel https://github.com/SwissDataScienceCenter/renku-notebooks/pull/849
Start a session in which the branch does not exist, you should be able to see the error message in the alert and in the error notification
/deploy renku-notebooks=feat-standardize-error-messages #persist
=> feat: use new notebook server error response format

client/src/notebooks/NotebookStart.present.js
Undo a change that was introduced in #1781, which opens the wrong dialog.
Fix #1947
To test, fork this project:
https://sekhar.dev.renku.ch/projects/cramakri/test-accessing-gpus
Then, in your fork, create a branch based on `renku/autosave/cramakri/master/2f88472/2f88472` with the name `renku/autosave/{your username}/master/2f88472/2f88472`
=> show the correct dialog when starting a session on an autosave branch 

client/src/project/Project.state.js, client/src/project/datasets/ProjectDatasets.test.js, client/src/project/list/ProjectList.test.js, client/src/utils/components/entities/Description.tsx, client/src/utils/components/entities/Tags.tsx
PR to fresh project header after update tagList and description values.
/deploy renku=1978-styles-cards-projects-and-datasets  #persist
=> feat: refresh project header after update tags and description (#1984)

client/src/project/Project.present.js, client/src/project/list/ProjectList.container.js, client/src/styles/components/_renku_search.scss
This PR contains a few fixes. I split them in different commits so that it's easier to review the code changes separately:
1. The star button displayed an endless spinning wheel for anonymous users. Not it shows the start and it restores the behavior on click (will redirect to the login to continue)
2. Adjust the margins on search containers by reducing margin in equal parts on both left and right sides, instead of left only (in the screenshot, the left screen shows balanced margins, while on the right screen there is a smaller space on the left and a bigger one on the right).
3. Prevents invoking multiple times the projects API with the same parameters when reaching the projects page. This was worse in the case of anonymous users since they were also redirected, adding an extra query for …
=> Fix a few UI glitches

client/src/project/Project.state.js, client/src/project/filestreeview/FilesTreeView.js
PR to fix wrong file tree display when changing to original project from fork.
Closes #1907 
/deploy renku-gateway=master #persist
=> fix: wrong file tree display when changing to original project from fork (#1907)

client/.eslintrc.json, client/package-lock.json, client/package.json, client/src/App.js, client/src/api-client/environment.js, client/src/index.js, client/src/landing/AnonymousHome.js, client/src/landing/NavBar.js, client/src/landing/NavBarWarnings.js, client/src/landing/index.js, client/src/model/GlobalSchema.js, client/src/model/RenkuModels.js, client/src/websocket/WsMessages.ts, client/src/websocket/handlers/userHandlers.test.ts, client/src/websocket/handlers/userHandlers.ts, client/src/websocket/index.test.ts, client/src/websocket/index.ts, server/src/routes/apis.ts, server/src/websocket/handlers/clientVersion.ts, server/src/websocket/index.ts
This PR adds the client-side logic for WebSocket.
The WebSocket channel is set up and it gets re-created in case of recoverable errors (to be further expanded), and it listens to incoming messages.
Once a new message comes, it checks for a suitable handler and executes it.
Mind that we save minimal data to the store for the WebSocket channel itself, but the handlers can modify any part of the model.
This fully moves the logic to check for UI version updates to the WebSocket channel. It's also a good example of how we can send all the required data through the channel, although we probably want to avoid this behavior in most cases where we need to get a lot of data.
Open the network tab and verify that the WebSocket channel is created and information about the client …
=> feat(client): add WebSocket channel setup

client/src/dataset/Dataset.present.js, client/src/project/Project.present.js, client/src/utils/components/TimeCaption.js
PR to hide the project header in the view of a project dataset and modify a dataset.
/deploy renku-gateway=master renku=1978-styles-cards-projects-and-datasets #persist
=> feat: hide project header in dataset view (#1984)

client/src/notebooks/NotebookStart.present.js, client/src/notebooks/Notebooks.container.js, client/src/notebooks/Notebooks.present.js, client/src/notebooks/components/LaunchErrorAlert.tsx, client/src/project/Project.present.js, client/src/styles/components/_renku_form.scss, e2e/cypress.json, e2e/cypress/integration/local/newSession.spec.ts
Develop a new session start flow with more emphasis on the session and less on the project.
Try starting sessions with and without options and see that the interaction is smooth.
I'm still not sure about the behavior after closing a session -- currently, the user gets taken back to the main project page. I think that feels better than going to watch the session shut down, since you usually do not care, but we can discuss this.
/deploy renku=ui-tests-2.8.0 renku-gateway=master #persist
Fix #1990
=> feat: new session start flow

server/src/routes/apis.ts
This should prevent propagating the headers to set the anon-id related cookies from the gateway to the UI since that is managed by the UI server now.
=> feat(server): prevent gateway from setting anon users cookies

helm-chart/README.rst, helm-chart/minikube-values.yaml, helm-chart/renku-ui/templates/ui-client-deployment-template.yaml, helm-chart/renku-ui/templates/ui-server-deployment.yaml, helm-chart/renku-ui/values.yaml, server/src/config.ts, server/src/utils/index.ts, server/src/utils/url-join.ts
Remove duplicate values from chart
/deploy renku-gateway=master #persist
=> build(chart): remove duplicates in client/server charts

client/src/App.js, client/src/websocket/index.ts
Propagate WebSocket object so that the `.send()` function can be invoked everywhere at any point.
=> chore(client): save and propagate socket object

server/src/config.ts, server/src/storage/RedisStorage.ts
The ui server was defaulting to using the `0` redis namespace which is reserved for the gateway.
This has not caused issues as far as I know because the likelihood of collisions is low.
But it is better to use a dedicated redis namespace for the ui-server and not put keys in the gateway's namespace.
=> fix(server): use the correct redis namespace

client/src/notebooks/NotebookStart.present.js, client/src/notebooks/Notebooks.container.js, client/src/notebooks/Notebooks.css, client/src/notebooks/Notebooks.present.js, client/src/notebooks/Notebooks.test.js, client/src/notebooks/components/ResourcesSessionModal.tsx, client/src/notebooks/components/Session.d.ts, client/src/notebooks/components/SessionFullScreen.tsx, client/src/notebooks/components/SessionModal.css, client/src/notebooks/components/SessionUnavailable.tsx, client/src/notebooks/components/StartSessionProgressBar.tsx, client/src/utils/components/progress/Progress.css, client/src/utils/components/progress/ProgressSteps.stories.tsx, client/src/utils/components/progress/ProgressSteps.tsx, client/src/utils/helpers/HelperFunctions.js, client/src/utils/ts-wrappers.js
PR to add progress indicator when start a session.
- Start a new session
- Reload a session
- Unavailable session
Closes #1879 
/deploy #persist renku-notebooks=feat-detailed-status-message extra-values=notebooks.amalthea.image.repository=registry.dev.renku.ch/tasko.olevski/renku-images/amalthea,notebooks.amalthea.image.tag=0.5.2-n014.h50ddcaa
=> feat: add progress indicator when start a session (#1879)

client/src/api-client/notebook-servers.js, client/src/api-client/utils.js, client/src/model/RenkuModels.js, client/src/notebooks/NotebookStart.present.js, client/src/notebooks/Notebooks.container.js, client/src/notebooks/Notebooks.state.js, client/src/notebooks/Notebooks.test.js, client/src/notebooks/components/EnviromentVariables.tsx, client/src/utils/components/shareLinkSession/ShareLinkSession.tsx
This PR add the env variables fields in start session form.
- User should be able to start a session with environment variables
- Verify environment variable is available
- Create a session link to share with environment variables
Closes #2058 
*Note: Added renku-notebooks dependency just to make available other functionalities merged before in master
/deploy #persist renku-notebooks=master extra-values=notebooks.amalthea.image.repository=registry.dev.renku.ch/tasko.olevski/renku-images/amalthea,notebooks.amalthea.image.tag=0.5.2-n014.h50ddcaa
=> feat: add env variables in start session form

client/src/utils/components/quicknav/QuickNav.container.js
This PR prevents re-fetching the starred/member projects too often. By mistake, we were checking `!featured.featured` instead of `!featured.fetching`. By using `refreshIfNecessary` we still refresh the projects every now and then.
=> fix(client): prevent repeated queries to gitlab graphql

client/src/notebooks/components/SessionFullScreen.tsx, e2e/cypress/fixtures/sessions/sessionsV2.json, e2e/cypress/support/renkulab-fixtures/sessions.ts
PR to fix session shows loader when session resources data change.
/deploy extra-values=notebooks.amalthea.resourceUsageCheck.enabled=true #persist
=> fix: no show session loader when other values than session state change

client/src/utils/components/Tree.tsx, client/src/workflows/Workflows.present.tsx, client/src/workflows/Workflows.state.ts
Changes to browser components:
- Remove "steps" from composite workflow browser executions row
- Add the `renku rerun <workflow>` command to the details view with copy/paste
-  change interaction on the browser elements: open on element click, collapse on arrow click
- Add auto-scroll to the top of the details section when clicking on a new workflow (it requires a project with many workflows)
=> Shape Up #1 - Fixes and changes to fourth prototype

client/src/notebooks/NotebookStart.present.js, client/src/notebooks/Notebooks.container.js
This fixes the issue reported in #2086 
The problem seems to happen when the commit specified in the autosaves is not available in the reference branch. There might be a few reasons for that, and it's very difficult to guess the correct one in every case.
Since it doesn't seem to happen frequently, I decided to handle it by showing a warning to the user (see next screen) and removing the corrupted autosave to prevent the problem from happening again. We could also decide to leave the branch and point the user in that direction, but that seems more fragile (PVS can't allow that, so it might not always work)
Create a corrupted branch: pick any repo, create a new branch with this pattern:
```
renku/autosave/<user>/<exising_branch>/<fake_commit_sha-7-chars>/fake_commit_sha-7-ch …
```
=> sessions: handle corrupted autosaves and improve warning messages positioning

client/src/project/new/ProjectNew.container.js, client/src/project/new/ProjectNew.state.js, client/src/project/new/components/ProjectIdentifier.tsx, client/src/project/new/components/ShareLinkModal.js, e2e/cypress/integration/local/newProject.spec.ts
This PR is to pre-fill all values in the new project form.
- Fixed interminal spin when selecting a namespace.
- Show url and ref of custom templates if included, previously it was only if the template was also included.
- added e2e test of all cases
Closes #2026 
=> fix: pre-fill all values in the new project form (#2026)(#2089)

client/src/utils/helpers/EnhancedState.js
The middleware for the projectKgApi was not correctly registered.
**before**
**after**
Fix #2096
=> fix: correctly set up the projectKgApi

e2e/cypress/support/authentication/gui_commands.ts, server/src/utils/url.ts, server/tests/utils/url.test.ts
This PR is to fix e2e and acceptance tests after gitlab url changed.
List of changes needed to fix the tests:
- the gitlabUrl set in gateway.gitlaburl should be `https://gitlab.dev.renku.ch/`.
- The CSP at https://gitlab.dev.renku.ch/ should include the frame-ancestors `https://*.renku.ch`. 
- The necessary changes to the acceptance tests are in the `000-fix-acceptance-tests-after-changing-gitlab-url `branch in the renku repository
/deploy renku=000-fix-acceptance-tests-after-changing-gitlab-url extra-values=gateway.gitlabUrl=https://gitlab.dev.renku.ch/ #persist
=> fix: tests after gitlab url changed

client/src/utils/components/Tree.tsx, client/src/workflows/Workflows.present.tsx, e2e/cypress.local.json, e2e/cypress/fixtures/workflows/workflow-show-details-notexists.json, e2e/cypress/fixtures/workflows/workflow-show-links-mappings.json, e2e/cypress/fixtures/workflows/workflow-show-outdated.json, e2e/cypress/fixtures/workflows/workflow-show-params.json, e2e/cypress/fixtures/workflows/workflows-list-links-mappings.json, e2e/cypress/integration/local/workflows.spec.ts, e2e/cypress/support/index.ts, e2e/cypress/support/renkulab-fixtures/workflows.ts, e2e/cypress/support/workflows/gui_commands.ts
Covering the basic workflows functionalities with e2e tests
/deploy renku-core=develop renku=000-fix-acceptance-tests-after-changing-gitlab-url #persist extra-values=gateway.gitlabUrl=https://gitlab.dev.renku.ch/
=> Shape Up #1 - e2e tests

client/src/features/session/sidecarApi.ts, client/src/notebooks/components/PullSession.tsx, client/src/notebooks/components/SaveSession.tsx, client/src/notebooks/components/SessionButtons.tsx, client/src/notebooks/components/SessionFullScreen.tsx, client/src/notebooks/components/Sidecar.tsx, client/src/utils/components/Tooltip.js, client/src/utils/ts-wrappers.js, e2e/cypress/integration/local/session.spec.ts, e2e/cypress/support/renkulab-fixtures/sessions.ts
As decided in #1956, the plan is to handle only the simplest case where the session is behind the orgin, but is not dirty and has not diverged.
1. Session is not behind origin (could be ahead)
2. Session is strictly behind origin
3. Session is dirty
4. Session is behind and ahead of origin
6. No sidecar or anonymous
Closes #1986 
/deploy renku=000-fix-acceptance-tests-after-changing-gitlab-url extra-values=gateway.gitlabUrl=https://gitlab.dev.renku.ch/ #persist
=> feat: add refresh button (#1986)

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Updates to the version numbers and changelog for the post-sprint release
/deploy extra-values=gateway.gitlabUrl=https://gitlab.dev.renku.ch/ #persist
fix #2108
=> build: release 2.11.0

client/src/notebooks/components/PullSession.tsx, client/src/notebooks/components/SaveSession.tsx, client/src/notebooks/components/SessionFullScreen.tsx
The save/pull buttons were not always working because the UI was requesting session sidecar health before it could possibly be available.
Fix #2100
/deploy extra-values=gateway.gitlabUrl=https://gitlab.dev.renku.ch/ #persist
=> Do not request sidecar health too early

client/src/notebooks/Notebooks.container.js, e2e/cypress/integration/local/autostartSession.spec.ts
PR to update message when custom commit or branch not found.
Closes #1777 
/deploy  renku=000-new-notebook-renderer-tests #persist
=> feat: update message when custom commit or branch not found (#1777)

client/src/notebooks/NotebookStart.present.js, client/src/notebooks/Notebooks.container.js, client/src/notebooks/components/StartSessionLoader.tsx, client/src/utils/components/buttons/Button.js
PR to apply the same Auto start session flow to Start a session with options flow.
Current flows to test:
- Quick start session from project header button or project card button
- Start session from link
- Start session with options
- Error starting a session (autostart, from link or with options)
Closes #2115 
/deploy renku=2115-unify-start-session-flow #persist
=> feat: unify start session flow (#2115)

client/src/features/projects/ProjectApi.ts, client/src/project/Project.present.js, client/src/project/new/ProjectNew.container.js, client/src/project/new/ProjectNew.present.js, client/src/project/new/ProjectNew.test.js, client/src/project/shared/Projects.state.js, client/src/utils/customHooks/UseGetNamespaces.ts, client/src/utils/customHooks/UseGetProjects.ts, client/src/utils/customHooks/UseGetVisibilities.ts, client/src/utils/helpers/EnhancedState.js, client/src/utils/helpers/HelperFunctions.js, client/src/utils/helpers/ProjectFunctions.ts
PR to refactor fork component to use redux toolkit to fetch namespaces, groups and member projects.
Closes #2157 
=> refactor(client): Fork component to use redux toolkit (#2157)

client/src/project/new/ProjectNew.state.js
When project creation succeeds but one of the following APIs fails (E.G. the webhook creation) the user gets a warning and can click on a "go to the project" button. The links was broken for projects with different name and slug.
This PR fixes it.
=> fix(client): use project slug for links

client/src/notebooks/ObjectStoresConfig.present.js
Update description for S3 services
fix #2198
=> chore(client): update S3 sources descriptions

client/src/file/File.present.js, client/src/file/Lineage.present.js
PR to fix overflow title in file/lineage view.
Closes #2132 
=> fix: overflow title in lineage (#2132)

client/src/notebooks/NotebookStart.present.js, client/src/notebooks/Notebooks.present.js, client/src/project/Project.present.js, client/src/project/new/components/SubmitFormButton.tsx, client/src/styles/bootstrap_ext/_button.scss, client/src/utils/components/buttons/Button.js, client/src/utils/components/buttons/Buttons.stories.tsx, client/src/utils/ts-wrappers.js, tests/cypress/support/sessions/gui_commands.ts
PR to add button with menu and round group button styles.
Closes #2200 
=> feat: add styles button with menu and group button (#2200)

client/src/dataset/Dataset.present.js, client/src/project/Project.present.js, client/src/styles/components/_renku_cards.scss, client/src/utils/components/entities/Tags.tsx, client/src/utils/components/entityHeader/EntityHeader.scss, client/src/utils/components/entityHeader/EntityHeader.tsx
This PR addresses a few layout details in the new headers.
* Restore the missing title in the default avatar on the projects and datasets detail pages.
* Add minimal margin to entity tags to prevent collapsing into the description (in the image, the previous version with the collapsed content)
* Remove extra space on the detail pages when tags are missing. This happened only on small and medium window sizes (in the image, the previous version with the extra space on the bottom)
/deploy renku=renku-ui-2.15.0-tests #persist #cypress
=> fix(client): improve headers layout

client/src/file/KnowledgeGraphStatus.present.js, client/src/project/Project.present.js, client/src/project/Project.state.js, client/src/utils/components/progress/Progress.css, tests/cypress/e2e/local/project.spec.ts, tests/cypress/fixtures/project/project-status-done.json, tests/cypress/fixtures/project/project-status-processing.json, tests/cypress/support/renkulab-fixtures/projects.ts
This adapts the UI to the [new response from the KG status endpoint](https://github.com/SwissDataScienceCenter/renku-ui/issues/2230), and restores the percentage indication when indexing a project.
As a comparison, on the following video the current PR deployment is on the left and "dev" on the right.
BREAKING CHANGE: requires a yet-unreleased version of renku-graph
re https://github.com/SwissDataScienceCenter/renku-graph/pull/1253
/deploy renku-graph=development #persist #cypress
=> fix(client)!: update KG status indexing percentage

README.md
Developer documentation
Fix #2165
=> docs: developer documentation

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Release including the KG status endpoint breaking change
/deploy #persist #cypress renku=auto-update/renku-graph-2.26.0
=> build: release 2.16.0

tests/cypress/e2e/local/autostartSession.spec.ts
This should prevent failures when waiting on APIs
/deploy renku=000-cypres-tests-new-search #persist #notest #cypress
=> test(e2e): avoid loading the URL early

helm-chart/renku-ui/values.yaml
Disable UI server default autoscaling settings since it might collide with settings in some deployments (E.G. in the CI deployments where the reserved resources are _very_ low).
/deploy renku=000-connect-btn #persist #cypress
=> build(server): remove default autoscaling settings

CHANGELOG.md, client/package-lock.json, client/package.json, client/src/project/overview/ProjectOverview.present.js, client/src/utils/components/buttons/Button.js, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
Release 3.1.0
This includes another minor PR to add a `data-cy` value to the "refresh commits" buttons -- it helps for the Cypress acceptance tests.
/deploy renku=000-connect-btn #persist #cypress
=> Release 3.1.0

client/src/utils/helpers/KgSearchFunctions.ts
Fix wrong label on search page.
`Creation` --> `Created`
/deploy #persist #cypress renku=update-renku-ui-3.1.0
=> chore(client): update wrong label on search page

client/src/features/inactiveKgProjects/InactiveKgProjects.tsx, client/src/features/kgSearch/KgSearchPage.tsx, client/src/utils/components/entities/VisibilityIcon.tsx, client/src/utils/context/appContext.ts
This provides type information for appContext so it is not necessary to do `//@ts-ignore` everywhere that the appContext is used.
=> refactor: provide type information for appContext

client/src/utils/components/entities/LinkedEntitiesByItemType.tsx
This is a quick fix to #2355 
fix #2355
=> fix(client): add trailing slash to dataset links

client/src/features/dashboard/components/ProjectsDashboard.tsx, client/src/features/session/sessionApi.ts, client/src/landing/NavBar.js, client/src/project/Project.present.js, client/src/utils/components/Logs.tsx, client/src/utils/components/entities/Buttons.tsx, client/src/utils/components/list/ListBar.scss, client/src/utils/components/list/ListBarSessions.tsx, client/src/utils/customHooks/UseGetSessionLogs.ts, client/src/utils/helpers/EnhancedState.js, tests/cypress/e2e/local/dashboard.spec.ts
PR to add get logs, stop session and link to Dashboard.
- It should show all existing sessions
- If a session is in Error it should show the error icon, the error message and the main action to stop the session.
- If a session is starting or running, it should show "Connect" as the main action and the corresponding icon.
- If the session is being stopped, it should show "Stop" as the main action, but disabled.
- The user should be able to get Logs in all cases
/deploy renku=000-ui-dashboard #persist #cypress
=> feat: add session actions in dashboard (#2305)

client/src/utils/components/FileExplorer.js
Elements rendered on the file browser were not properly aligned. This PR fixes it
=> fix(client): align elements in the datasets file browser

client/src/notebooks/Notebooks.present.js
=> Show session table without overflowing

client/src/notebooks/NotebookStart.present.js, client/src/notebooks/Notebooks.container.js, client/src/notebooks/Notebooks.state.js
Restores the "start with base image" button for pinned images with a broken image.
@olevski Using an example like the project `lorenzo.cavazzi.tech/pinned-image-broken`, everything works well but I noticed that the `GET /servers` endpoint returns `false` on the annotation `default_image_used`.
1. Should I pass some specific value to the `POST /servers` API to properly set the `default_image_used` annotation?
2. [_very_ minor] Any chance we can get a real `true/false` boolean for that field instead of a stringified Pythonish boolean `"False"/"True"`?
```
"annotations": {
...
"renku.io/default_image_used": "False",
},
```
fix #2395
=> fix(client): start sessions with base images on broken pinned images

.github/workflows/test-and-ci.yml, client/src/features/dashboard/components/ProjectsDashboard.tsx, client/src/project/new/Project.style.css
This minor change prevents react autosuggest dropdowns from being overlayed by group buttons: in the example, I have quite a few groups listed on the namespace. The "Choose File" group button has a `z-index` of 2 and, on the "New Project" page, it shows on top of the autosuggest dropdown menu.
=> chore(client): bump autosuggest container z-index

client/package-lock.json, client/package.json, server/Dockerfile
Group snyk updates
/deploy #persist #cypress renku=renku-ui-3.4.1-tests
=> Group snyk updates 2023-04-05

client/src/notebooks/NotebookStart.present.js
This fixes a nasty bug accidentally introduced here #2410 that prevents pinned images from being picked up correctly.
In the screenshot, I tested a project with a pinned image that was picked up correctly -- it's from a different commit than the current one.
You can use this project to test it https://dev.renku.ch/projects/lorenzo.cavazzi.tech/1408-pinned-image
/deploy #persist #cypress renku=renku-ui-3.4.2-updates
fix #2458
=> fix(client): prevent dropping pinned images

client/src/project/Project.present.js
This should fix the sessions list fork button, but the styling needs to be fixed to only show the "Fork" option and not the number of forks.
Fix #2451
/deploy #persist #cypress renku=renku-ui-3.4.2-updates
=> Make the sessions list fork button work

client/package-lock.json, client/src/features/projects/ProjectsApi.ts, tests/cypress.config.ts
Fixes a bug where the API `/projects/<project>?statistics=false&doNotTrack=true` 404 response is processed as project data. We now skip these items.
/deploy #persist #cypress renku=renku-ui-3.4.2-updates
Fixes #2437.
=> Dashboard: fix issue with trying to process deleted project data

client/src/features/project/dataset/ProjectDatasetsView.tsx
See screenshot:
This is most likely a typo, an extra "," is seen above "Add Dataset".
=> Remove conspicuous "," in the add dataset screen

client/src/project/Project.present.js
In PR #2452, the line https://github.com/SwissDataScienceCenter/renku-ui/blob/39853035225ac330e34beb8ce11392e9116181a5/client/src/project/Project.present.js#L903 was not updated like https://github.com/SwissDataScienceCenter/renku-ui/blob/39853035225ac330e34beb8ce11392e9116181a5/client/src/project/Project.present.js#L858-L859.
This PR should also fix the `UnprivilegedSessionSpec` Selenium acceptance test.
=> fix(client): fix `notebookWarning()` broken invocation after #2452

client/src/project/Project.present.js
The removed route is never hit as the `datasetUrl` one is always hit beforehand.
Also, displaying the project navbar would not follow the convention used in other screens using a "Back to <project>" button.
=> Remove unused route in client/src/project/Project.present.js

client/src/file/File.container.js, client/src/file/File.present.js, client/src/notebooks/NotebookStart.present.js, tests/cypress/e2e/project.spec.ts
This fixes the "Start a session" button for anonymous users viewing a notebook in a project's files tab.
Fixes #2477.
=> fix(client): provide the correct notebook search param for anon users

client/src/workflows/Workflows.present.tsx, tests/cypress/e2e/workflows.spec.ts, tests/cypress/fixtures/workflows/workflows-list-links-mappings-inactive.json
The workflows list passed from RTK query is read-only, but we call `.sort()` to order the workflow list. As a fix, we simply copy the list into a new array when we list all workflows ("show inactive workflows" toggle).
Fixes #2488.
=> fix(client): do not crash the UI when showing all workflows

client/.storybook/preview.js, client/.storybook/store.js, client/src/components/Logs.tsx, client/src/components/entityHeader/EntityHeader.tsx, client/src/components/ssh/ssh.tsx, client/src/features/dashboard/components/InactiveKgProjects.tsx, client/src/features/dashboard/components/ProjectsDashboard.tsx, client/src/features/display/displaySlice.ts, client/src/features/display/index.ts, client/src/features/inactiveKgProjects/InactiveKgProjects.tsx, client/src/features/inactiveKgProjects/inactiveKgProjectsSlice.ts, client/src/features/workflows/WorkflowsSlice.ts, client/src/model/Model.js, client/src/utils/customHooks/UseSliceSelector.ts, client/src/utils/helpers/EnhancedState.ts, client/src/workflows/Workflows.container.tsx
The new `createSliceSelector()` helper function creates a React hook which simplifies writing state selectors for RTK slices.
Other updates:
* Moved `client/src/utils/helpers/EnhancedState.js` to TypeScript and export only one function, `createStore()`.
/deploy #persist #cypress renku=leafty/update-tests-renku-ui-2495
=> refactor(client): update RTK slice selector hooks

client/src/utils/helpers/Time.js, tests/cypress/e2e/workflows.spec.ts
It seems that `tests/cypress/e2e/workflows.spec.ts` often fails due to fixture data not providing datetimes when expected.
/deploy #persist #cypress renku=0000-ui-3.5.0
=> fix(client): update Time.js to not throw an error on invalid dates

tests/cypress/e2e/workflows.spec.ts
See https://github.com/SwissDataScienceCenter/renku-ui/actions/runs/5078713055/jobs/9123592615?pr=2546:
the UI updates too fast for cypress.
=> fix(tests): force the UI to wait in "expand a workflow - waiting"

client/src/components/entityHeader/EntityHeader.tsx, client/src/components/list/ListBar.tsx, client/src/components/list/ListBarSessions.tsx, client/src/components/list/ListCard.tsx
=> fix(client): make the text not selectable in entity cards

client/.eslintrc.json, client/src/components/dateFilter/DateFilter.tsx, client/src/components/entities/Entities.d.ts, client/src/components/list/List.d.tsx, client/src/components/progress/Progress.tsx, client/src/components/progress/ProgressSteps.tsx, client/src/components/sortingEntities/SortingEntities.tsx, client/src/components/visibility/Visibility.tsx, client/src/features/dashboard/Dashboard.tsx, client/src/features/kgSearch/KgSearch.d.ts, client/src/features/project/ProjectEntityHeader.tsx, client/src/utils/helpers/url/Url.test.js, client/src/workflows/Workflows.present.tsx
Vars and args can start with `_` to indicate that they are unused.
=> minor: change to lint rule for var and arg

client/craco.config.js
Fixes a Webpack deprecation warning:
```
[DEP_WEBPACK_TEMPLATE_PATH_PLUGIN_REPLACE_PATH_VARIABLES_HASH] DeprecationWarning: [hash] is now [fullhash] (also consider using [chunkhash] or [contenthash], see documentation for details)
```
=> chore(client): fix webpack warning

client/src/notebooks/NotebookStart.present.js
Do not let the user start a session until the options have been populated from the project settings or defaults.
=> fix(client): enable start session button after load

client/src/components/Tree.tsx, client/src/components/entities/Executions.tsx
Fixes #2578.
The "last execution" tooltip in the "Workflows" view can sometimes crash the UI because the worflow id is not sanitized to create a valid CSS id.
This code change makes use of a `ref` instead of assigning a CSS id.
Also, the component has been refactored to make the rendering logic more readable.
/deploy renku-core=develop renku=2315ui-project-status #persist #notest #cypress
=> fix(client): fix the workflow view crashing the UI in some cases

client/src/features/project/components/ProjectSettingsGeneralDeleteProject.tsx
The autocomplete suggestions offered by the browser are not useful (other project names which were deleted).
/deploy renku-core=develop renku=2315ui-project-status #persist #cypress
=> fix(client): set autocomplete to off for the delete project confirmation box

client/src/features/dashboard/Dashboard.tsx
Fixes #2593.
Explanation: the current version of the code runs `notebookCoordinator.fetchNotebooks()` only the first time the Dashboard component is rendered.
=> fix(client): fix sessions not showing on dashboard

client/src/features/projects/projectsApi.ts, client/src/utils/customHooks/UseGetNamespaces.ts
Some users have more than 20 namespaces. Increase the limit used when showing the namespace list in the project creation dropdown.
=> fix: allow up to 100 namespaces and sort them

client/src/features/dataServices/dataServices.d.ts, client/src/features/dataServices/dataServicesApi.ts, client/src/features/project/Project.d.ts, client/src/features/project/projectCoreApi.ts, client/src/features/project/useProjectCoreSupport.ts, client/src/notebooks/NotebookStart.present.js, client/src/notebooks/Notebooks.container.js, client/src/notebooks/Notebooks.state.js, client/src/notebooks/components/StartSessionLoader.tsx, client/src/notebooks/components/options/SessionClassOption.module.scss, client/src/notebooks/components/options/SessionClassOption.tsx, client/src/notebooks/components/options/SessionStorageOption.tsx, client/src/project/components/ProjectSettingsSessions.tsx, tests/cypress/fixtures/dataServices/resource-pools.json, tests/cypress/support/renkulab-fixtures/dataServices.ts
* Update the session start options to show which session classes match the compute requirements.
* Update the quick start flow to auto-select a suitable session class or fall back to the option screen if non is suitable.
Start options:
Quick start not finding a suitable session class:
/deploy extra-values=crc.image.tag=sha-d9cef4d renku=crac-service-helm-chart renku-notebooks=feat-work-with-crac #persist #cypress
=> feat(client): update session start options and flow for resource pools 

client/src/features/project/projectCoreApi.ts
This can cause issue for projects using an unsupported metadata version.
=> fix(client): fix `versionedUrlEndpoint()`

client/package-lock.json, client/src/features/project/dataset/ProjectDatasetsView.tsx
If the backend cannot return datasets, do not try to get them.
/deploy #persist #cypress renku=core-svc-horizontal-scaling renku-core=v2.6.0 extra-values=global.renku.cli_version=2.6.0rc1 renku-gateway=master
=> fix: do not query for datasets if it is not possible

.github/workflows/acceptance-tests.yml, .github/workflows/test-and-ci.yml, client/package-lock.json
Updating the Cypress acceptance tests action to support changes in https://github.com/SwissDataScienceCenter/renku-actions/pull/54 and https://github.com/SwissDataScienceCenter/renku/pull/3150
/deploy #persist #notest #cypress renku=renku-ui-3.10-tests
=> ci: update Cypress acceptance tests action

server/package-lock.json, server/package.json, server/src/websocket/handlers/sessions.ts
There seems to be an [annoying error with Winston](https://github.com/winstonjs/winston/issues/1338) that results in non-expanded errors when logging.
This PR updates the library. Since it's unclear from the linked issues/PRs whether _all_ errors are handled correctly, I also added a log to print the error message for sessions.
/deploy #persist renku=renku-ui-3.10-tests
=> chore: prevent swallowing session errors

.github/workflows/acceptance-tests.yml
Add the URL of the deployment to the `environment` section.
This adds a button in GitHub:
Clicking "View deployment" opens the Renku UI in a new tab.
/deploy #notest #persist
=> chore(build): update acceptance-tests.yml

client/src/help/HelpRelease.tsx
If dev versions of core and/or notebooks were deployed, they were incorrectly displayed as tagged versions. This PR fixes that problem.
/deploy #persist renku=renku-ui/3.11-acceptance-tests
=> minor: support dev versions of core and notebooks

client/src/components/Loader.tsx
Fixes a small DOM error for the loader spinner when it is inserted in `<p>` elements:
```
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
```
The spinner now uses `<span>` when `inline` is set to `true`.
There is no visual change introduced.
=> fix(client): fix DOM nesting error for the loader spinner

client/src/components/entityHeader/EntityHeader.tsx, client/src/components/list/ListBarSessions.tsx, client/src/components/shareLinkSession/ShareLinkSession.tsx, client/src/features/session/components/SessionButton.tsx, client/src/features/session/components/SessionHibernated.tsx, client/src/features/session/components/StartNewSession.tsx, client/src/features/session/components/StopSessionModal.tsx, client/src/features/session/components/status/SessionHibernationStatusDetails.tsx, client/src/features/session/components/status/SessionStatusBadge.tsx, client/src/features/session/components/status/SessionStatusText.tsx, client/src/notebooks/NotebookStart.present.js, client/src/notebooks/components/SessionListStatus.tsx, tests/cypress/e2e/project.spec.ts, tests/cypress/support/renkulab-fixtures/projects.ts
* Fix the share session link functionality
* Update the paused session status in the dashboard
* Update the pause session modal
Dashboard info:
Pause session modal:
/deploy #persist extra-values=notebooks.userSessionPersistentVolumes.enabled=true,notebooks.amalthea.image.repository=renku/amalthea,notebooks.amalthea.image.tag=db70f80ef1983d49a1b167faa57d02d9d8b9554f renku-notebooks=pitch/session-persistence
=> Persistent sessions: small UI updates

client/src/features/project/projectCoreApi.ts
This fixes a bug accidentally introduced in #2717 
=> fix(client): use the migrations_check endpoint on the latest core version

client/src/landing/NavBar.js
There is a mistake in the logic to determine if a deployment is a dev deployment.
**Before**
**After**
=> fix: correctly determine if a deployment is a dev deployment

client/src/components/list/ListBar.scss, client/src/components/list/ListBarSessions.tsx
/deploy #persist extra-values=notebooks.userSessionPersistentVolumes.enabled=true,notebooks.amalthea.image.repository=leafty/renku-amalthea,notebooks.amalthea.image.tag=pitch-session-hibernation,notebooks.amalthea.image.pullPolicy=Always,renku-notebooks=pitch/session-persistence-final
=> show the unsaved work warning on the dashboard

client/src/project/new/ProjectNew.container.js, client/src/project/new/ProjectNew.state.js, client/src/project/new/components/Automated.tsx, tests/cypress/e2e/newProject.spec.ts, tests/cypress/fixtures/templates.json
There was a rather annoying bug causing an infinite loop when using project creation links embedding custom variables.
Actually, some of the `useEffect` hooks in the ProjectNew container were triggered indefinitely (it would have been easier to spot if we didn't explicitly ignore the `react-hooks/exhaustive-deps` warnings...) but that was not causing issues in most other cases.
This PR also introduces better feedback messages when using the project creation links (see Cypress tests for examples).
Cypress tests were added to be sure we don't accidentally introduce further regressions on the feedback messages or the optional template variables.
=> fix(client): handle embedded template variables in project creation links

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
This is a bugfix release including the fix from 3.11.1
Using the renku-core versioning is also included, but that's probably not enough to mark this as a full release: the change is nothing visible to users, more of a refactoring on how we invoke renku-core APIs.
=> build: release 3.12.1

client/src/components/FileExplorer.tsx, client/src/components/form-field/DropzoneFileUploader.js, client/src/features/project/dataset/datasetCore.api.ts
Pull request for resolving the issue with uploading dataset files in the "Add/Modify Dataset" form. 
1. Issue with displaying subfolders in unzipped dataset files.
* Before
* After
2. Error when sending several dataset files
* Before
* After
Fix #2754 
=> fix: unzip multiple dataset files (#2754)

client/src/features/session/components/ShowSession.tsx
Removes the extra title tooltip on hover and adds hidden text for accessibility.
Removes this:
=> fix(client): remove extra title on hover for session buttons

client/src/components/form-field/DropzoneFileUploader.js, client/src/features/project/dataset/DatasetModify.tsx
Adding files to a dataset by URL was broken, it should be fixed now
=> fix adding files by URL to datasets

README.md
This PR restructures the Readme file to provide more consistent information to the developers.
* The initial `Development` section explains how to start developing code for the whole UI.
* The `UI client` and `UI server` have been restructured and expanded (especially the Client section). Grouping should be more intuitive going through the "tool stack", then the "code structure", then "testing" and finally mentioning other utilities useful for the development.
fix #2775
=> chore: update the readme file

client/src/features/project/components/AddCloudStorageButton.tsx, client/src/features/project/components/ProjectSettingsCloudStorage.tsx, client/src/features/project/projectCloudStorage.constants.ts, client/src/features/session/components/options/SessionCloudStorageOption.tsx, tests/cypress.config.ts, tests/cypress/e2e/newSession.spec.ts, tests/cypress/e2e/projectSettings.spec.ts
The 3rd party library we use for mounting cloud storage breaks down when in read/write mode.
We will swap this for a better library. But we want to release this with read-only support and not delay the feature further. Because swapping this library cannot be done that quickly and it needs some testing to make sure it works well.
You can see this deployed at https://github.com/SwissDataScienceCenter/renku/pull/3214
=> chore: always use read-only for cloud storage

client/src/statuspage/Statuspage.present.js, client/src/statuspage/statuspage.css, tests/cypress/e2e/home.spec.ts, tests/cypress/e2e/maintenance.spec.ts, tests/cypress/fixtures/statuspage/statuspage-outage.json, tests/cypress/support/renkulab-fixtures/global.ts
If there is a major or critical incident reported on the statuspage, show information about it in a banner.
Fix #2767
/deploy
=> Show status banner as loud during major incidents

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
/deploy renku=leafty/feat-admin-panel renku-gateway=master renku-data-services=main extra-values=global.gitlab.url=https://gitlab.dev.renku.ch,dataService.image.pullPolicy=Always,notebooks.cloudstorage.s3.enabled=true,amalthea.extraChildResources[0].group=com.ie.ibm.hpsys,amalthea.extraChildResources[0].name=datasets,notebooks.cloudstorage.s3.installDatashim=false
=> build: release 3.15.0

server/src/utils/middlewares/lastProjectsMiddleware.ts
The full path for a project is case-insensitive (e.g. foo/bar is equivalent to FOO/bar), so we should normalize project paths before saving.
/deploy
=> fix(server): save lower case project path for last-visited

client/src/components/ssh/ssh.tsx, client/src/features/session/components/SessionButton.tsx, client/src/project/components/GitLabConnect.tsx, client/src/styles/bootstrap_ext/_button.scss
The `DropdownItem` component should render either a button or a link based on its properties.
Since we use `Link` lo link local resources, we ended up nesting the 2 components instead of using `<DropdownItem href=...>`. That renders an anchor inside a button, with some undesired side effects, like making the areas next to the borders clickable but with no effect (in the gif, the fixed version is on the right).
/deploy
=> fix(client): adjust dropdown menus  with anchors nested in buttons

client/src/components/list/EntityCardSkeleton.module.scss, client/src/components/list/EntityCardSkeleton.stories.tsx, client/src/components/list/EntityCardSkeleton.tsx, client/src/components/progress/Progress.stories.tsx, client/src/components/progress/ProgressSteps.stories.tsx
PR storybook for EntityCardSkeleton component.
`npm run storybook`
or https://renku-ci-ui-2937.dev.renku.ch/storybook/?path=/story/components-loaders-entitycardskeleton--entity-card-skeleton-loader
Fix #2909 
/deploy extra-values=global.renku.cli_version=2.8.0rc3 #persist
=> feat(client): Update EntityCardSkeleton animation and add its storybook

client/src/features/project/GitLab.types.ts, client/src/features/project/projectGitLab.api.ts, client/src/features/session/components/StartNewSession.tsx, client/src/features/session/components/options/SessionProjectDockerImage.tsx
Fixes #2906.
Update the session start warning when the image has finished building.
/deploy
=> chore(client): update the session start warning

client/src/components/clipboard/Clipboard.tsx, client/src/components/commandCopy/CommandCopy.module.scss, client/src/components/commandCopy/CommandCopy.tsx, client/src/components/commits/Commits.js, client/src/components/icons/BootstrapCopyIcon.tsx, client/src/project/clone/CloneButton.tsx, client/src/styleguide/StyleGuide.js
Updates the copy icon to use the one from Bootstrap.
Clone button and command copy component:
Commit buttons:
/deploy
=> chore(client): update copy icon to bootstrap

client/src/project/components/ProjectSettingsSessions.tsx
While testing other PRs, I noticed the badge in the project's session settings shown as feedback to the user's action has become _very_ big.
I assume that was not intentional; this PR brings it back to the default size.
/deploy
=> fix(client): resize feedback badge in session settings

tests/package.json
The change to vite requires changes to how the tests are started.
=> Adapt test setup for vite-based server

client/package.json
This prevents a memory error when building locally through `npm run build`:
```
<--- JS stacktrace --->
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
1: 0xb83f50 node::Abort() [node]
2: 0xa94834  [node]
3: 0xd647c0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
4: 0xd64b67 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
5: 0xf42265  [node]
6: 0xf5474d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
7: 0xf2ee4e v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
8: 0xf30217 …
```
=> build: prevent memory heap error when building locally

.github/workflows/acceptance-tests.yml, client/src/features/project/components/cloudStorage/AddOrEditCloudStorage.tsx, client/src/features/project/components/cloudStorage/CloudStorageItem.tsx, client/src/features/project/components/cloudStorage/projectCloudStorage.api.ts, client/src/features/project/components/cloudStorage/projectCloudStorage.constants.ts, client/src/features/project/components/cloudStorage/projectCloudStorage.types.ts, client/src/features/project/utils/projectCloudStorage.utils.ts
This PR fixes a few issues when adding/editing storage:
- Prevents a bunch of default values to be set automatically, especially when many advanced options exist.
- Correct use of placeholders for default values and examples.
- Remove values correctly when editing an existing storage.
- Handles non-stringy values correctly when listing the storage options in the storage list.
- Use `<datalist>` to pick values from the examples list.
- Mind that examples from the backend are not 100% reliable; we can't use a `<select>` here, and I would rather keep a simple solution than mess up with autocomplete examples and "use-react-form." Support for the datalist tag is pretty good on Firefox, while the UX on Chrome is still not that good, especially for longer lists.
/deploy renku=rclone-sessions …
=> [ShapeUp] improve UX when adding/editing storage

CHANGELOG.md, client/package-lock.json, client/package.json, helm-chart/renku-ui/Chart.yaml, helm-chart/renku-ui/values.yaml, server/package-lock.json, server/package.json
New Renku UI release.
There are quite some dependencies this time :grin: 
/deploy renku=rclone-sessions renku-notebooks=master amalthea=main renku-data-services=main extra-values=notebooks.cloudstorage.enabled=true,notebooks.cloudstorage.storageClass=csi-rclone-test,notebooks.cloudstorage.installRCloneCSI=true,csi-rclone.storageClassName=csi-rclone-test,csi-rclone.csiNodepluginRclone.tolerations[0].key=renku.io/dedicated,csi-rclone.csiNodepluginRclone.tolerations[0].operator=Equal,csi-rclone.csiNodepluginRclone.tolerations[0].value=user,csi-rclone.csiNodepluginRclone.tolerations[0].effect=NoSchedule
=> build: release 3.18.0

client/src/api-client/dataset.js, client/src/dataset/Dataset.container.jsx, client/src/dataset/Dataset.present.jsx, client/src/dataset/Dataset.state.js, client/src/dataset/addtoproject/DatasetAddToProject.tsx, client/src/features/datasets/datasetsCore.api.ts, client/src/features/project/Project.d.ts, client/src/features/project/dataset/ProjectDatasetShow.tsx, client/src/features/project/projectCoreApi.ts, client/src/project/datasets/delete/DeleteDataset.tsx, client/src/project/datasets/import/DatasetImport.tsx
There is a breaking change from the renku-core APIs that requires the clients to either _always_ or _never_ specify the branch name. The reason is that the branch is used for caching, and not sending one results in falling back to a default name instead of picking the default branch name.
Since we know the default branch and we are already using it somewhere, this PR updates the code to always pass the default branch name.
/deploy renku=remove-v9 renku-core=develop
=> Always specify the branch when dealing with datasets

client/src/landing/SectionShowcase.tsx, client/src/landing/sectionShowcase.module.scss, client/src/styles/components/_renku_home.scss
Match the font size and color in the showcase section with the rest of the homepage.
**Large viewport**
**Small viewport**
Fix #2963
/deploy extra-values=ui.homepage.showcase.enabled=true,ui.homepage.showcase.title=Renku,ui.homepage.showcase.description=Description,ui.homepage.showcase.projects[0].identifier=hdbi/data-management/cccooci
=> fix: align font size and text color with rest of the home page

client/src/components/navbar/NavBarItem.module.scss, client/src/components/navbar/NavBarItems.tsx
Fixes #2934.
Use `1100` as a z-index for the dropdown content of the top bar menu items.
/deploy
=> fix(client): fix z-index clash in the search page

client/run-telepresence.sh, server/run-telepresence.sh
Update the `telepresence` to be inline with the current version of [Telepresence OSS](https://www.getambassador.io/docs/telepresence-oss/latest/install).
The current version prefers that the `connect` command is used before the `intercept` command. The scripts now check the `telepresence status` and re-connect to the correct k8s namespace if needed.
=> chore: update telepresence scripts

client/src/features/project/components/ProjectSettingsCloudStorage.tsx
We should not show the button to add a new storage service in deployments that do not support it
/deploy renku=000-cypress-storage-off
=> fix(client): hide button to add storage when the feature is turned off

client/package-lock.json, client/package.json
See #3006.
Removes `popper.js` and `uuid`.
/deploy
=> chore(client): remove unused dependencies

.github/workflows/test-and-ci.yml
The current client unit tests (`npm run test`) usually run in ~11 seconds, but in some cases the test is stuck and takes more than 10 minutes (e.g. https://github.com/SwissDataScienceCenter/renku-ui/actions/runs/7727771816/attempts/1?pr=3011).
This adds a timeout to the corresponding step so that it fails fast and can be re-tried if needed.
=> chore(ci/cd): add a timeout for the unit tests

client/src/App.jsx
Restore logged in and out notifications in the UI.
/deploy
=> fix(clent): restore logged in/out notifications

client/src/components/quicknav/QuickNav.container.jsx, client/src/components/quicknav/QuickNav.present.jsx, client/src/landing/AnonymousHome.tsx
Component styles which leaked global classes where used in other places; now that pages are loaded lazily, this breaks styling for components which used to rely on "hidden" global styles.
Before:
After:
=> fix(client): temporarily fix search bar styles

client/src/App.jsx, client/src/features/projectsV2/list/ProjectV2List.tsx, client/src/features/projectsV2/new/ProjectV2New.tsx, client/src/features/projectsV2/show/ProjectV2Show.tsx, client/src/utils/helpers/url/Url.js, tests/cypress/e2e/projectV2.spec.ts
Change the URL structure for renku-native projects from `projectsV2` to `native/projects` to allow introducing other native (v1) entities under the `native` path.
/deploy
=> refactor: change the url structure for renku-native projects

client/.eslintrc.json, client/src/App.jsx, client/src/components/router/Router.tsx, client/src/features/projectsV2/show/ProjectV2Show.tsx, client/src/features/rootV2/LazyRootV2.tsx, client/src/features/rootV2/NavbarV2.tsx, client/src/features/rootV2/RootV2.tsx, client/src/project/Project.present.jsx
Adds an additional top bar when navigating paths under `/v2`.
/deploy renku=release-0.48.x
=> feat(client): add an additional top bar for Renku 1.0

client/src/components/navbar/NavBarItems.tsx, client/src/features/rootV2/RootV2.tsx, client/src/index.jsx, client/src/utils/feature-flags/featureFlags.constants.ts, client/src/utils/feature-flags/featureFlags.slice.ts, client/src/utils/feature-flags/featureFlags.types.ts, client/src/utils/feature-flags/useFeatureFlagSync.hook.ts, client/src/utils/feature-flags/useLocalStorageFeatureFlags.ts, client/src/utils/helpers/EnhancedState.ts
Add a "Renku 1.0" menu entry once the user visits any page within `/v2`.
/deploy
=> feat: ad-hoc feature flag for Renku 1.0

client/src/features/admin/AddSessionEnvironmentButton.tsx, client/src/features/admin/SessionEnvironmentFormContent.tsx, client/src/features/admin/SessionEnvironmentsSection.tsx, client/src/features/admin/UpdateSessionEnvironmentButton.tsx, client/src/features/admin/adminSessions.types.ts, client/src/features/sessionsV2/AddSessionLauncherButton.tsx, client/src/features/sessionsV2/SessionLauncherFormContent.tsx, client/src/features/sessionsV2/SessionsV2.tsx, client/src/features/sessionsV2/UpdateSessionLauncherModal.tsx, client/src/features/sessionsV2/sessionsV2.types.ts
See https://github.com/SwissDataScienceCenter/renku-data-services/issues/134.
/deploy #notest renku=build/new-sessions renku-data-services=leafty/134-default-url extra-values=initDb.image.repository=registry.dev.renku.ch/tasko.olevski/renku-images/init-db,initDb.image.tag=0.44.1-1.ebb0e80,keycloakx.initRealm.image.repository=registry.dev.renku.ch/tasko.olevski/renku-images/init-realm,keycloakx.initRealm.image.tag=0.44.1-1.ebb0e80.git.2200.h26267d0e
=> feat(client): add default URL to Renku 1.0 session entities

client/src/features/searchV2/components/SearchV2Bar.tsx, client/src/features/searchV2/components/SearchV2DateFilter.tsx, client/src/features/searchV2/components/SearchV2Filters.tsx, client/src/features/searchV2/components/SearchV2Header.tsx, client/src/features/searchV2/components/SearchV2Results.tsx, client/src/features/searchV2/components/SearchV2UserFilter.tsx, client/src/features/searchV2/searchV2.api.ts, client/src/features/searchV2/searchV2.slice.ts, client/src/features/searchV2/searchV2.types.ts, client/src/features/searchV2/searchV2.utils.test.ts, client/src/features/searchV2/searchV2.utils.ts, client/src/features/searchV2/useStartSearch.hook.ts, tests/cypress/e2e/searchV2.spec.ts, tests/cypress/support/renkulab-fixtures/searchV2.ts
This PR adds the following:
- Handles pagination (feel free to raise the default `perPage` value, currently at `10`, before merging).
- Automatically refresh the search result when changes on the UI require it (e.g. sorting, filtering, page number, ...)
- Search by Creation Date
/deploy renku=build/search-and-discovery-1.0 #notest renku-data-services=main renku-gateway=master
=> feat: support pagination and refresh query automatically

tests/tsconfig.json
Update `tsconfig.json` in `tests/` to allow the use of `tsc` (the TypeScript compiler) without emitting `.js` files.
/deploy
=> chore(tests): update tsconfig.json

.github/workflows/cleanup-old-deployments.js, .github/workflows/cleanup-old-deployments.yml, .github/workflows/playground.mjs
Fixes #3068.
Add a manual action which cleans up old deployment environments from GitHub.
After cleanup, the PR will show that the git branch was previously deployed, but is not active:
Removing old environments will de-clutter the "Deployments" section from the GitHub page:
=> chore(ci/cd): add an action to cleanup old deployments

client/src/file/File.present.jsx, client/src/file/Lineage.present.jsx
Fix the appearance of the "copy path" buttons in the file view.
Before:
After:
/deploy
=> fix(client): update appearance of copy button in file view

client/.eslintrc.json, client/package.json, client/src/features/projectsV2/api/projectV2.api.ts, client/src/features/projectsV2/api/projectV2.enhanced-api.ts, client/src/features/projectsV2/api/projectV2.openapi.json, client/src/features/projectsV2/show/ProjectV2EditForm.tsx
Adds support for entity tags on Renku 2.0 projects.
* Send `If-Match` header with `ETag` value if such a value exists.
With this update, the UI supports the Renku 2.0 projects API both with ETags and without ETags.
/deploy renku=release-0.50.x
=> feat(client): add support for entity tags on Renku 2.0 projects

client/src/landing/anonymousHomeNav.tsx, client/src/utils/constants/Docs.js
Fixes #3059.
See also: https://github.com/SwissDataScienceCenter/renku-blog/pull/33.
=> fix(client): update footer links with Mastodon

tests/package-lock.json, tests/package.json
Fixes the headless e2e tests when running on Apple Silicon (ensures headless chrome).
=> chore(tests): update headless tests command

client/src/features/projectsV2/api/projectV2.api.ts, client/src/features/projectsV2/api/projectV2.enhanced-api.ts, client/src/features/projectsV2/api/projectV2.openapi.json, client/src/features/projectsV2/list/ProjectV2List.tsx, client/src/features/projectsV2/new/ProjectV2New.tsx, client/src/features/projectsV2/show/ProjectV2Show.tsx, client/src/features/projectsV2/show/groupEditForms.tsx, client/src/features/rootV2/NavbarV2.tsx, client/src/features/rootV2/RootV2.tsx, client/src/features/searchV2/components/SearchV2Results.tsx, client/src/features/sessionsV2/AddSessionLauncherButton.tsx, client/src/features/sessionsV2/PauseOrDeleteSessionModal.tsx, client/src/features/sessionsV2/SessionStartPage.tsx, client/src/features/sessionsV2/SessionsV2.tsx, client/src/features/sessionsV2/ShowSessionPage.tsx, client/src/features/sessionsV2/StartSessionButton.tsx, client/src/landing/NavBar.jsx, client/src/utils/helpers/url/Url.js, tests/cypress/e2e/projectV2.spec.ts, tests/cypress/fixtures/projectV2/list-projectV2.json, tests/cypress/support/renkulab-fixtures/projectV2.ts
* Changes to use namespace/slug in the URL for the project page (instead of project Id)
* Minor changes like rename `v2Projects` to `projectV2` and use Navigate instead of Redirect
Fix #3096 
/deploy renku-data-services=main
=> feat(client): use namespace/slug to identify projects (#3096)

.github/workflows/acceptance-tests.yml, client/src/features/secrets/SecretDelete.tsx, client/src/features/secrets/SecretEdit.tsx, client/src/features/secrets/SecretNew.tsx, client/src/features/secrets/Secrets.tsx, client/src/features/secrets/SecretsList.tsx, client/src/features/secrets/SecretsListItem.tsx, client/src/features/secrets/secrets.api.ts, client/src/features/secrets/secrets.module.scss, client/src/features/secrets/secrets.types.ts, client/src/features/secrets/secrets.utils.tsx, client/src/utils/helpers/EnhancedState.ts, tests/cypress/e2e/secrets.spec.ts, tests/cypress/support/renkulab-fixtures/index.ts, tests/cypress/support/renkulab-fixtures/secrets.ts
This PR implements the first part of #3100 , adding a new page to list and manage user secrets.
The new page is accessible from the User dropdown menu on the top right.
re #3100
/deploy #notest renku=build/secrets-in-sessions renku-data-services=pitch/secret-storage secrets-storage=pitch/secret-storage extra-values=secretsStorage.encryptionKey=vMqdVXcSIwjwONvGiNE2vjzRjmi8NJ8Y9lTB8m3l/Xg=
=> [ShapeUp] feat: add new secret page

client/src/features/projectsV2/shared/WipBadge.tsx, client/src/features/secrets/LazySecrets.tsx, client/src/features/secrets/SecretNew.tsx, client/src/features/secrets/Secrets.tsx, client/src/features/session/components/StartNewSession.tsx, client/src/features/session/components/options/AutostartSessionOptions.tsx, client/src/features/session/components/options/SessionUserSecrets.tsx, client/src/features/session/sessions.api.ts, client/src/features/session/sessions.types.ts, client/src/features/session/startSessionOptions.types.ts, client/src/features/session/startSessionOptionsSlice.ts, client/src/utils/helpers/url/Url.js, tests/cypress/e2e/newSession.spec.ts
This PR implements the second part of https://github.com/SwissDataScienceCenter/renku-ui/issues/3100 ,changing the "Start with options" page to include secrets.
re https://github.com/SwissDataScienceCenter/renku-ui/issues/3100
/deploy #notest renku=build/secrets-in-sessions renku-data-services=pitch/secret-storage secrets-storage=pitch/secret-storage extra-values=secretsStorage.encryptionKey=vMqdVXcSIwjwONvGiNE2vjzRjmi8NJ8Y9lTB8m3l/Xg=
=> [ShapeUp] feat: update start session with options

client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/CodeRepositoryDisplay.tsx, client/src/styles/bootstrap/_custom_bootstrap_variables2.0.scss, tests/cypress/e2e/dashboard.spec.ts
PR to add project overview content. It includes:
Display session and code repositories.
Display session launcher info in side panel.
Add new session (custom image/existing environment).
Link existing code repository (Renku repo only).
Delete session launcher.
Remove code repository.
Edit session launcher.
Not included to handle cases where a user has no rights on the project.
=> feat: project page overview V2 (sessions and code repositories)

client/src/features/ProjectPageV2/ProjectPageContent/ProjectInformation/ProjectInformation.tsx, client/src/features/ProjectPageV2/ProjectPageContent/Settings/ProjectSettingsMembers.tsx, client/src/features/ProjectPageV2/utils/roleUtils.ts, tests/cypress/e2e/projectV2.spec.ts, tests/cypress/fixtures/projectV2/list-projectV2-members-many.json
Show the names of the members in the project information page.
Check the following:
- Project members are shown if you have access to the project
- At most 5 project members are shown
- No project members are shown if the user is not logged in
=> Show project members in the project information page

client/src/project/new/ProjectNew.state.js, client/src/utils/Utils.test.jsx, client/src/utils/helpers/HelperFunctions.js, client/src/utils/helpers/verifyTitleCharacters.utils.ts
The `verifyTitleCharacters()` method is the only method which imports `xregexp`. Moving it to a separate file allows for bundle size optimization.
Before:
```
build/assets/index-zwCpWK0N.js                              1,960.44 kB │ gzip: 493.50 kB │ map: 6,098.69 kB
```
After:
```
build/assets/index-TyZG-yHr.js                              1,874.07 kB │ gzip: 456.83 kB │ map: 5,793.17 kB
```
/deploy
=> chore(client): move verifyTitleCharacters() to optimize bundle size

.github/workflows/prepare-release.yml
The changelog is now deprecated, do not update it.
=> chore: do not update the changelog in prepare-release

client/src/landing/WhoWeAre/WhoWeAre.tsx
Fixes #3241.
/deploy renku=release-0.55.0
=> chore: update the "who we are" section

client/src/features/dashboardV2/DashboardV2.tsx, client/src/features/projectsV2/shared/WipBadge.tsx, client/src/features/rootV2/NavbarV2.tsx, client/src/features/secrets/Secrets.tsx
Details:
* Change "Alpha" badge to "Beta" badge
* Update the roadmap link on the Renku 2.0 dashboard
/deploy renku=release-0.55.0
=> feat: move Renku 2.0 from "alpha" to "beta"

client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/CodeRepositoryDisplay.tsx, client/src/utils/helpers/safeNewUrl.utils.ts
Fixes #3246.
Example: https://renku-ci-ui-3247.dev.renku.ch/v2/projects/flora.thiebaut/flora-test
/deploy renku=release-0.55.0
=> fix: use safe URL for repository icon

client/src/features/session/components/SessionHibernated.tsx, client/src/features/sessionsV2/PauseOrDeleteSessionModal.tsx, client/src/features/sessionsV2/components/SessionStatus/SessionStatus.tsx
PR to remove copy text Inconsistencies referring to stopping/deleting sessions.
/deploy
=> fix: unify texts when deleting a session Renku 2.0

client/src/styles/renku_bootstrap_customization.scss
New semantic colors.
The info color is less bright
The `success` color is lighter, with stronger differentiations from the `primary` color
=> design - update semantic colors

client/src/components/Alert.constants.ts, client/src/components/Alert.jsx
New style for alerts :nail_care: 
=> design - change style for alerts

client/src/components/Logs.tsx, client/src/features/sessionsV2/ShowSessionPage.tsx, client/src/features/sessionsV2/components/SessionButton/ActiveSessionButton.tsx
PR to address small issues in Renku v2
Issues:
- Display Launcher names in session page
- When I go to Resources in a Renku 2.0 session, I see the cheat sheet for the Renku CLI (this should be removed)
What is included in this PR:
- Show the project name and launcher name in the session view navbar title.
- Open a modal with project name and session details when the title in the navbar is clicked.
- Remove the Resources Modal, so only session log modal is displayed on the session page.
/deploy
=> feat: display session details in session page Renku 2.0

client/src/features/projectsV2/fields/DescriptionFormField.tsx, client/src/features/projectsV2/fields/SlugFormField.tsx
This fixes the wrong text in the fields' descriptions on the group creation page.
/deploy
=> fix: use the correct entity name in the descriptions for creating groups

client/src/features/ProjectPageV2/ProjectPageContent/DataSources/DataSourceDisplay.tsx, client/src/features/ProjectPageV2/ProjectPageContent/DataSources/DataSourceView.tsx, client/src/features/project/components/cloudStorage/AddOrEditCloudStorage.tsx, client/src/features/project/components/cloudStorage/AddStorageMountSaveCredentialsInfo.tsx, client/src/features/project/components/cloudStorage/CloudStorageModal.tsx, client/src/features/project/components/cloudStorage/cloudStorageModalComponents.tsx, client/src/features/project/components/cloudStorage/projectCloudStorage.constants.ts, client/src/features/project/components/cloudStorage/projectCloudStorage.types.ts, client/src/features/projectsV2/api/projectV2.enhanced-api.ts, client/src/features/secrets/SecretDelete.tsx, client/src/features/secrets/Secrets.tsx, client/src/features/sessionsV2/CloudStorageSecretsModal.tsx, client/src/features/sessionsV2/SessionStartPage.tsx, tests/cypress/e2e/projectV2DataSourceCredentials.spec.ts, tests/cypress/e2e/projectV2setup.spec.ts, tests/cypress/fixtures/cloudStorage/cloud-storage-secrets-partial.json, tests/cypress/fixtures/cloudStorage/cloud-storage-secrets.json, tests/cypress/fixtures/cloudStorage/cloud-storage-with-secrets-values-full.json, tests/cypress/support/renkulab-fixtures/cloudStorage.ts, tests/cypress/support/renkulab-fixtures/secrets.ts
Allow storing credentials when a storage is created.
Add an option to save credentials to the last page of the add data source flow
When checked, the credentials will be stored after the data source is added. This can be verified by looking at the data source, the credential field will be displayed as <saved secret>
Add a data source that requires credentials to a project (or example an S3 or polybox data source). Check that the credentials used to test are stored. Also, check that there is no option to store credentials for a public data source (like a public S3 bucket).
/deploy renku-notebooks=master renku-data-services=main
=> feat: save secrets on storage create

client/src/features/project/components/cloudStorage/projectCloudStorage.constants.ts, tests/cypress/e2e/projectSettings.spec.ts
Change default to read-only when a data source is added. See 
* https://www.notion.so/renku/When-I-add-a-data-connector-the-default-should-be-read-only-with-the-read-write-an-optional-overrid-716f02eb42354f709a1cfb1607a0d447
/deploy renku=ciyer/ui-3275-data-source
=> Set default to read only in add data source

.github/workflows/acceptance-tests.yml, .github/workflows/test-and-ci.yml
As discussed this will allow you to deploy the new amalthea through a PR comment
=> chore: update renku actions to 1.12.3

server/src/authentication/authenticator.ts
Fixes `uiserver` crash looping when Sentry is enabled.
See also: #3319.
/deploy
Tested:
* Running `3.35.0` with Sentry enabled -> crash loop
* Running this version with Sentry enabled -> start and no error logs
=> fix: provide empty auth header

client/src/features/sessionsV2/ShowSessionPage.tsx
When starting a session, the `session_launchers` endpoints is invoked too early when the project id isn't available yet. This prevents it
/deploy
=> fix: prevent querying sessions launchers without project id

client/.eslintrc.json, client/src/features/admin/AddConnectedServiceButton.tsx, client/src/features/admin/AdminPage.tsx, client/src/features/admin/ConnectedServiceFormContent.tsx, client/src/features/admin/ConnectedServicesSection.tsx, client/src/features/admin/DeleteConnectedServiceButton.tsx, client/src/features/admin/IncidentsAndMaintenanceSection.tsx, client/src/features/admin/SessionEnvironmentsSection.tsx, client/src/features/admin/UpdateConnectedServiceButton.tsx, client/src/features/connectedServices/ConnectedServicesPage.tsx, client/src/features/connectedServices/connectedServices.api.ts, client/src/features/connectedServices/connectedServices.types.ts
Handle connected services in the admin panel.
/deploy
=> feat: handle connected services in the admin panel

client/src/features/dashboardV2/DashboardV2.tsx
PR to move Renku 2.0 beta warning alert from dashboard
/deploy
=> chore: remove Renku 2.0 beta warning alert from dashboard

client/src/features/sessionsV2/SessionLauncherFormContent.tsx
PR to fix broken styles for Environment list when editing a launcher.
- Before
- After
/deploy
=> fix: styles for edit launcher environment list

client/src/features/dataConnectorsV2/components/DataConnectorModal/DataConnectorModalBody.tsx
Fixes an issue in the data connector modal where typing a slug by hand would not get taken into account.
/deploy renku=leafty/fix-ui-permissions
=> fix: slug field in data connector modal

CODING_GUIDELINES.md
Some counter-examples include the session row in the Renku 2.0 project page, it is not possible to open the session launcher offcanvas using the keyboard at the moment because we have `<li onclick={...}>`.
=> chore: add onclick coding guideline

client/src/features/ProjectPageV2/ProjectPageContent/DataConnectors/ProjectConnectDataConnectorsModal.tsx, client/src/features/dataConnectorsV2/components/DataConnectorActions.tsx, client/src/features/dataConnectorsV2/components/DataConnectorModal/DataConnectorSaveCredentialsInfo.tsx, client/src/features/dataConnectorsV2/components/DataConnectorModal/index.tsx, client/src/features/dataConnectorsV2/components/DataConnectorView.tsx, client/src/features/dataConnectorsV2/components/DataConnectorsBox.tsx, client/src/features/dataConnectorsV2/utils/useDataConnectorPermissions.hook.ts, client/src/features/groupsV2/settings/GroupSettingsMembers.tsx, client/src/features/groupsV2/show/GroupV2Show.tsx, client/src/features/groupsV2/utils/useGroupPermissions.hook.ts, client/src/features/sessionsV2/DataConnectorSecretsModal.tsx, client/src/utils/helpers/ApiErrors.ts, tests/cypress/e2e/groupV2.spec.ts, tests/cypress/e2e/groupV2DataConnectorCredentials.spec.ts, tests/cypress/e2e/projectV2DataConnectorCredentials.spec.ts, tests/cypress/e2e/projectV2Session.spec.ts, tests/cypress/e2e/projectV2setup.spec.ts, tests/cypress/fixtures/dataConnector/data-connector-permissions.json, tests/cypress/fixtures/groupV2/groupV2-permissions-none.json, tests/cypress/fixtures/sessions/sessionV2.json, tests/cypress/support/renkulab-fixtures/dataConnectors.ts
=> Some minor improvements to data connectors

client/src/features/dashboardV2/DashboardV2Sessions.tsx, client/src/features/sessionsV2/SessionList/SessionItemDisplay.tsx, client/src/features/sessionsV2/SessionView/SessionView.tsx, client/src/features/sessionsV2/SessionsV2.tsx, client/src/utils/customHooks/useLocationHash.hook.ts
Controls the session offcanvas with a URL hash, e.g.
- `https://renku-ci-ui-3382.dev.renku.ch/v2/projects/flora.thiebaut/flora-test` -> project page
- `https://renku-ci-ui-3382.dev.renku.ch/v2/projects/flora.thiebaut/flora-test#launcher-01JAWVJ544MHTX98Y5FGDSCHTK`-> project page with session offcanvas open
The session row on the dashboard page has also been updated: clicking on the session row now opens the offcanvas for that session. Note that it will not work for orphan sessions.
/deploy
=> refactor: use URL hash to control session offcanvas

client/src/components/progress/ProgressSteps.tsx, client/src/features/sessionsV2/SessionStartPage.tsx, client/src/features/sessionsV2/sessionsV2.types.ts, client/src/features/sessionsV2/startSessionOptionsV2.slice.ts, client/src/features/sessionsV2/startSessionOptionsV2.types.ts, client/src/features/sessionsV2/useSessionLaunchState.hook.ts
PR to show an error if the docker image identifier is invalid.
Notion ref: https://www.notion.so/renku/Show-an-error-if-the-docker-image-identifier-is-invalid-1190df2efafc809682caee2d8c485285
/deploy renku=feat-jupyter-free-sessions renku-data-services=release-amaltheas-migration amalthea-sessions=main renku-notebooks=master extra-values=amalthea-sessions.deployCrd=false
=> feat: show an error if the docker image identifier is invalid

client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/RepositoriesBox.tsx, client/src/features/ProjectPageV2/ProjectPageContent/DataConnectors/ProjectDataConnectorsBox.tsx, client/src/features/ProjectPageV2/ProjectPageContent/Settings/ProjectSettingsMembers.tsx, client/src/features/dataConnectorsV2/components/DataConnectorsBox.tsx, client/src/features/projectsV2/fields/ProjectNamespaceFormField.tsx, client/src/features/projectsV2/fields/UserSelector.tsx, client/src/features/sessionsV2/AddSessionLauncherButton.tsx, client/src/storybook/bootstrap/Button.stories.tsx
Fixes icon alignment; the `icon-text` class does not exist. Only `bi` (bootstrap-icon) should be used for icon alignment.
Before (icon too low):
After (icon perfectly centered vertically):
=> fix: remove uses of icon-text class name

client/src/features/dataConnectorsV2/components/DataConnectorModal/DataConnectorModalFooter.tsx, client/src/features/dataConnectorsV2/components/DataConnectorModal/DataConnectorModalResult.tsx, client/src/features/projectsV2/fields/ProjectNamespaceFormField.module.scss, client/src/features/projectsV2/fields/ProjectNamespaceFormField.tsx, tests/cypress/e2e/groupV2DataConnectorCredentials.spec.ts
* minor: fix DOM structure issue
* minor: use dropdown z-index for namespace select menu
* fix: only save credentials when there are sensitive values
/deploy renku=feat-jupyter-free-sessions renku-data-services=main amalthea-sessions=main renku-notebooks=master extra-values=amalthea-sessions.deployCrd=false
=> Fix several minor data-connector bugs

client/src/features/ProjectPageV2/ProjectPageContent/DataConnectors/ProjectDataConnectorsBox.tsx, client/src/features/dataConnectorsV2/components/DataConnectorActions.tsx, client/src/features/dataConnectorsV2/components/DataConnectorModal/DataConnectorModalFooter.tsx, client/src/features/dataConnectorsV2/components/DataConnectorModal/dataConnectorModalButtons.tsx, client/src/features/dataConnectorsV2/components/DataConnectorModal/index.tsx, client/src/features/dataConnectorsV2/state/dataConnectors.slice.ts, tests/cypress/e2e/projectV2DataConnectorCredentials.spec.ts, tests/cypress/e2e/projectV2setup.spec.ts, tests/cypress/support/renkulab-fixtures/dataConnectors.ts
After closing the data connector modal, some state would be retained, causing bugs.
The bugs would occur when a second data connector was created immediately after the first. For example, one data connector was created, and then a second data connector was started, but canceled (e.g., by closing the dialog), the second would get created anyway. Check that these situations do not happen anymore
/deploy renku=release-0.61.0
=> fix: reset state of data connectors on modal close

client/src/features/admin/AddResourcePoolButton.tsx
Fixes #3417.
Manually tested, working as intended.
/deploy
=> fix: make the pre-populated quota large enough

client/src/features/session/components/StartSessionProgressBar.tsx
=> fix: correctly report session v2 status on launch

client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/CodeRepositoryDisplay.tsx, client/src/features/dataConnectorsV2/components/DataConnectorView.tsx, client/src/features/sessionsV2/SessionView/SessionView.tsx
Fixes #3431.
Note that other broken UI elements for long titles are not fixed in this PR.
/deploy
=> fix: break titles in offcanvas if too long

client/src/features/ProjectPageV2/ProjectPageContent/SessionSecrets/AddSessionSecretButton.tsx, client/src/features/ProjectPageV2/ProjectPageContent/SessionSecrets/ProjectSessionSecrets.tsx, client/src/features/ProjectPageV2/ProjectPageContent/SessionSecrets/SessionSecretActions.tsx, client/src/features/ProjectPageV2/ProjectPageContent/SessionSecrets/SessionSecretSlotItem.tsx, client/src/features/ProjectPageV2/ProjectPageContent/SessionSecrets/SessionViewSessionSecrets.tsx, client/src/features/ProjectPageV2/ProjectPageContent/SessionSecrets/UpdateSecretsMountDirectoryButton.tsx, client/src/features/ProjectPageV2/ProjectPageContent/SessionSecrets/fields/FilenameField.tsx, client/src/features/ProjectPageV2/ProjectPageContent/SessionSecrets/sessionSecrets.constants.ts, client/src/features/projectsV2/api/projectV2.api.ts, client/src/features/projectsV2/api/projectV2.openapi.json, client/src/features/projectsV2/fields/SecretsMountDirectoryField.tsx, client/src/features/secretsV2/GeneralSecretItem.tsx, client/src/features/sessionsV2/SessionView/SessionView.tsx, tests/cypress/fixtures/projectV2/create-projectV2.json, tests/cypress/fixtures/projectV2/list-projectV2.json, tests/cypress/fixtures/projectV2/read-projectV2-empty.json, tests/cypress/fixtures/projectV2/read-projectV2.json, tests/cypress/fixtures/projectV2/update-projectV2-metadata.json, tests/cypress/fixtures/projectV2/update-projectV2-one-repository.json, tests/cypress/fixtures/projectV2/update-projectV2-repositories.json
Part of #3412, merging into `build/session-secrets`.
Update the "Session Secrets" section to allow for the mount location to be configured.
/deploy #notest renku=build/session-secrets renku-data-services=build/session-secrets
=> feat: make the session secret mount location configurable

client/src/features/ProjectPageV2/ProjectPageContent/SessionSecrets/AddSessionSecretButton.tsx, client/src/features/ProjectPageV2/ProjectPageContent/SessionSecrets/ProjectSessionSecrets.tsx, client/src/features/ProjectPageV2/ProjectPageContent/SessionSecrets/ProvideSessionSecretModalContent.tsx, client/src/features/ProjectPageV2/ProjectPageContent/SessionSecrets/SecretsMountDirectoryComponent.tsx, client/src/features/ProjectPageV2/ProjectPageContent/SessionSecrets/SessionSecretActions.tsx, client/src/features/ProjectPageV2/ProjectPageContent/SessionSecrets/SessionSecretSlotItem.tsx, client/src/features/ProjectPageV2/ProjectPageContent/SessionSecrets/SessionViewSessionSecrets.tsx, client/src/features/ProjectPageV2/ProjectPageContent/SessionSecrets/UpdateSecretsMountDirectoryButton.tsx, client/src/features/projectsV2/api/projectV2.enhanced-api.ts, client/src/features/secrets/Secrets.tsx, client/src/features/secrets/SecretsListItem.tsx, client/src/features/secretsV2/DataConnectorSecretItem.tsx, client/src/features/secretsV2/GeneralSecretItem.tsx, client/src/features/secretsV2/ReplaceSecretValueModal.tsx, client/src/features/secretsV2/SecretItemActions.tsx, client/src/features/secretsV2/SecretsV2.tsx, client/src/features/sessionsV2/SessionSecretsModal.tsx, client/src/features/sessionsV2/useSessionSecrets.hook.ts, client/src/features/usersV2/api/users.api.ts, tests/cypress/e2e/projectV2SessionSecrets.spec.ts, tests/cypress/support/renkulab-fixtures/secrets.ts
Part of #3412, merging into `build/session-secrets`.
Polishes the session secrets feature.
* Launch interrupt for anon users
* Re-designed user secrets page v2
* Updated UI for session secrets and session secret slots
* Ask for secret value after creating a new secret slot
/deploy renku=build/session-secrets renku-data-services=build/session-secrets
=> feat: nice-to-haves for the build

client/src/features/ProjectPageV2/ProjectPageContent/Settings/ProjectSettings.tsx, client/src/features/ProjectPageV2/ProjectPageContent/Settings/ProjectUnlinkTemplate.tsx, tests/cypress/e2e/projectV2.spec.ts, tests/cypress/e2e/projectV2SessionSecrets.spec.ts, tests/cypress/support/renkulab-fixtures/projectV2.ts
Support breaking the link to the template project
- Create a project
- Use the copy feature to copy the project
- On the copy, go to the settings page and fill out the form to unlink the project
After that, the project should no longer show a link to the template
/deploy renku=release-0.62.0
=> feat: break copy link

client/src/features/dashboardV2/DashboardV2.tsx
=> fix: use hash links for new projects/groups

client/src/App.jsx, client/src/dataset/Dataset.container.jsx, client/src/dataset/Dataset.present.jsx, client/src/dataset/DatasetFunctions.js, client/src/features/project/dataset/DatasetModify.tsx, client/src/features/project/dataset/ProjectDatasetImport.tsx, client/src/features/project/dataset/ProjectDatasetNewEdit.tsx, client/src/features/project/dataset/ProjectDatasetShow.tsx, client/src/features/project/dataset/ProjectDatasetsView.tsx, client/src/project/Project.present.jsx, client/src/project/datasets/delete/DeleteDataset.tsx, client/src/project/datasets/import/DatasetImport.tsx
Setup CompatRoute for dataset routes.
* `/projects/<project>/datasets/*`
See:
* #3028
* #3041
* #3151
/deploy
=> refactor(client): some migration step for `react-router@v6`

client/.eslintignore, client/src/components/PrimaryAlert.module.scss, client/src/components/PrimaryAlert.tsx, client/src/components/buttons/Button.tsx, client/src/features/ProjectPageV2/ProjectPageContent/ProjectInformation/ProjectInformation.tsx, client/src/features/ProjectPageV2/ProjectPageContent/ProjectInformation/ProjectInformationButton.tsx, client/src/features/ProjectPageV2/ProjectPageContent/ProjectOverviewPage.tsx, client/src/features/ProjectPageV2/ProjectPageContent/Settings/ProjectSettings.tsx, client/src/features/ProjectPageV2/ProjectPageContent/Settings/ProjectUnlinkTemplate.tsx, client/src/features/ProjectPageV2/ProjectPageHeader/ProjectCopyBanner.tsx, client/src/features/ProjectPageV2/ProjectPageHeader/ProjectCopyButton.tsx, client/src/features/ProjectPageV2/ProjectPageHeader/ProjectCopyModal.tsx, client/src/features/ProjectPageV2/ProjectPageHeader/ProjectPageHeader.tsx, client/src/features/ProjectPageV2/ProjectPageHeader/ProjectTemplateInfoBanner.module.css, client/src/features/ProjectPageV2/ProjectPageHeader/ProjectTemplateInfoBanner.tsx, client/src/features/projectsV2/api/projectV2.enhanced-api.ts, client/src/features/projectsV2/api/projectV2.openapi.json, client/src/features/projectsV2/fields/ProjectOwnerSlugFormField.tsx, tests/cypress/e2e/projectV2.spec.ts, tests/cypress/e2e/projectV2SessionSecrets.spec.ts, tests/cypress/fixtures/namespaceV2/list-namespaceV2.json, tests/cypress/fixtures/namespaceV2/namespaceV2-user1.json, tests/cypress/fixtures/projectV2/update-projectV2-metadata.json, tests/cypress/support/renkulab-fixtures/projectV2.ts
- copy a regular project
- break the copy link
- mark a project as a template and see that banners are shown
- when viewing a project that is a template, but for which you are not an owner
- when viewing a project that is a template, where you are an owner
/deploy renku=release-0.63.0
=> feat!: allow copying projects (#3393)

client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/CodeRepositoryDisplay.tsx, client/src/features/ProjectPageV2/utils/useProjectPermissions.hook.ts, client/src/features/dataConnectorsV2/components/DataConnectorActions.tsx, client/src/features/dataConnectorsV2/utils/useDataConnectorPermissions.hook.ts, client/src/features/sessionsV2/SessionsV2.tsx, tests/cypress/e2e/groupV2.spec.ts, tests/cypress/e2e/groupV2DataConnectorCredentials.spec.ts, tests/cypress/e2e/projectV2setup.spec.ts
Closes #3446.
Update the actions buttons on the project / group / user pages to be presented only when the corresponding action is available to the user.
**Can edit project**
**Cannot edit project**
**Can edit project**
**Cannot edit project**
**Can edit data connector & Can edit project**
**Can edit data connector & Cannot edit project**
**Cannot edit data connector & Can edit project**
**Cannot edit data connector & Cannot edit project**
**Anonymous user (cannot save credentials)**
**Can delete data connector (owner)**
**Can edit data connector**
**Cannot edit data connector**
**Anonymous user (cannot save credentials)**
/deploy
=> fix: hide the edit button when the user does not have permissions

client/src/features/ProjectPageV2/ProjectPageContent/SessionSecrets/ProjectSessionSecrets.tsx, client/src/features/ProjectPageV2/ProjectPageContent/Settings/ProjectDelete.tsx, client/src/features/ProjectPageV2/ProjectPageContent/Settings/ProjectSettings.tsx, client/src/features/ProjectPageV2/ProjectPageContent/Settings/ProjectSettingsMembers.tsx, client/src/features/groupsV2/settings/GroupSettingsMembers.tsx, client/src/features/groupsV2/settings/GroupSettingsMetadata.tsx, tests/cypress/e2e/projectV2.spec.ts
There were a few glitches and inconsistencies on those pages found while addressing https://github.com/SwissDataScienceCenter/renku-ui/issues/3460. I decided to separate them into this PR to simplify the review process.
This cleanup includes:
- Adjusting spacing and visualizations.
- Update the visualization for users without permissions and remove redundant PermissionsGuard elements.
- ![Screenshot_20250107_163913](https://github.com/user-attachments/assets/fa299980-7a8c-4393-8f0b-22dfbb1201bc)
- Remove card's subtitles and reuse the same solution for members to keep consistency across the pages.
- ![image](https://github.com/user-attachments/assets/dc3a7846-d6b5-4e0e-b5c0-5b51229156a9)
- ![image](https://github.com/user-attachments/assets/3ab00254-2e10-4501-a8d4-851e194df9ec)
/deploy
=> fix: cleanup the project and group settings pages

client/src/features/project/components/cloudStorage/AddOrEditCloudStorage.tsx
This PR reverts the data connector option default values to the previous behavior.
It also prevents showing objects converted to strings as placeholders.
/deploy
=> fix: use placeholders for data connectors

client/src/features/dashboardV2/DashboardV2.tsx
Fixes #3486.
The links should direct to the "site", not to the notion "app".
See: https://swiss-data-science.slack.com/archives/C67N59QL8/p1736239159632489
/deploy
=> fix: use renku.notion.site links for the documentation

client/src/App.jsx, client/src/components/navbar/AnonymousNavBar.tsx, client/src/components/navbar/LoggedInNavBar.tsx, client/src/components/navbar/NavBarItems.tsx, client/src/features/rootV1/LazyRootV1.tsx, client/src/features/rootV1/RootV1.tsx, client/src/features/rootV2/RootV2.tsx, client/src/index.jsx, client/src/landing/GetSarted/GetStarted.tsx, client/src/landing/HeroLanding/HeroLanding.tsx, client/src/landing/NavBar.jsx, client/src/landing/SectionShowcase.tsx, client/src/landing/Teaching/Teaching.tsx, client/src/landing/WhatIsRenku/WhatIsRenku.tsx, client/src/landing/WhoWeAre/WhoWeAre.tsx, client/src/landing/anonymousHomeNav.tsx, client/src/not-found/NotFound.tsx, client/src/notifications/Notifications.present.jsx, client/src/routing/routes.constants.ts, client/src/utils/helpers/HelperFunctions.js, client/src/utils/helpers/HelperFunctionsV2.ts, tests/cypress/e2e/dashboard.spec.ts, tests/cypress/e2e/datasets.spec.ts, tests/cypress/e2e/home.spec.ts, tests/cypress/e2e/kgSearch.spec.ts, tests/cypress/e2e/secrets.spec.ts
PR to handle atyles for new routing
fix #3499 
Tests will be handled in [#3503](https://github.com/SwissDataScienceCenter/renku-ui/issues/3503).
Functionalities such as creating a new v2 project or v2 group will be addressed in [#3501](https://github.com/SwissDataScienceCenter/renku-ui/issues/3501).
* Landing Page: Now loads with styles v2 
* Renku 1.0 Compatibility:
*` /v1` now loads the Renku 1.0 dashboard when the user is authenticated.
* Routes under `/v1/*` load the corresponding Renku 1.0 pages:
* `/v1/search`
* `/v1/help`
* `/v1/notifications`
* `/v1/secrets`
* Projects and Datasets:
* Routes under `/projects/*` now load Renku 1.0 project pages.
* Similarly, `/datasets/*` routes load the appropriate content from Renku 1.0. 
* Style Guide: The style guide is currently broken and …
=> feat: set styles for new routing

client/vite.config.ts
See:
* https://github.com/vitejs/vite/security/advisories/GHSA-vg6x-rcgg-rjx6
* https://vite.dev/config/server-options.html#server-allowedhosts
=> fix: add allowed hosts to vite config

client/run-telepresence.sh, server/run-telepresence.sh
In `client/`, you can now do:
```bash
$ ./run-telepresence.sh
Detected current PR: 3491
Exchanging k8s deployments for the following context/namespace: 
renku-dev/renku-ci-ui-3491
The deployment URL is expected to be: 
https://renku-ci-ui-3491.dev.renku.ch
[...]
```
The script assumes that the GitHub CLI is available as `gh`, but this can be overriden with `GH_CLI="github" ./run-telepresence.sh`.
Also, the script does not crash if the CLI is not available or if the current branch does not correspond to a PR.
=> dev: auto-detect telepresence context

tests/cypress/e2e/maintenance.spec.ts
Fixes a flakey test in `maintenance.spec.ts` introduced by the "Early access" banner.
=> fix: correct alert test in maintenance.spec.ts

client/src/features/dataConnectorsV2/components/DataConnectorModal/DataConnectorModalBody.tsx, client/src/features/dataConnectorsV2/components/DataConnectorModal/index.tsx, client/src/features/dataConnectorsV2/components/DataConnectorsBox.tsx, client/src/features/project/components/cloudStorage/AddOrEditCloudStorage.tsx, client/src/features/project/components/cloudStorage/CloudStorageModal.tsx, client/src/features/project/components/cloudStorage/cloudStorageModalComponents.tsx, client/src/features/projectsV2/api/namespace.enhanced-api.ts, client/src/features/projectsV2/api/projectV2.enhanced-api.ts, client/src/features/projectsV2/fields/ProjectNamespaceFormField.tsx, client/src/features/projectsV2/list/ProjectV2ListDisplay.tsx, tests/cypress/e2e/projectV2DataConnectorCredentials.spec.ts, tests/cypress/e2e/projectV2setup.spec.ts
This is the initial implementation.
Things that are missing:
- no tests
- the way that data connectors in projects are displayed is not right
- the backend is still a bit wonky and will not support everything (i.e. launching sessions fails)
/deploy renku-data-services=feat-add-project-as-dc-owner-pt2
=> feat: create data connector in project

client/src/features/sessionsV2/SessionView/EnvironmentCard.tsx, client/src/features/sessionsV2/SessionsV2.tsx, client/src/features/sessionsV2/api/sessionLaunchersV2.api.ts, client/src/features/sessionsV2/api/sessionLaunchersV2.generated-api.ts, client/src/features/sessionsV2/api/sessionLaunchersV2.openapi.json
PR stack:
* (this) #3529
* #3534
* #3536
* #3511
Update the UI for session environments created from code repositories.
* Get the build status and show it in the session offcanvas
* Allow users with edit permissions on the project to trigger builds and to cancel in-progress builds.
/deploy #notest renku=build/session-env-builders renku-data-services=kpack-resources renku-notebooks=leafty/shipwright-buildrun-cache extra-values=dataService.imageBuilders.enabled=true,dataService.imageBuilders.pushSecretName=flora-docker-secret,dataService.imageBuilders.buildRunRetentionAfterFailedSeconds=86400,dataService.imageBuilders.outputImagePrefix=harbor.dev.renku.ch/flora-dev/
=> feat: get build status and trigger builds

client/src/features/sessionsV2/SessionView/EnvironmentCard.tsx, client/src/features/sessionsV2/SessionsV2.tsx, client/src/features/sessionsV2/api/sessionLaunchersV2.api.ts, client/src/features/sessionsV2/components/SessionForm/EnvironmentKindField.tsx
PR stack:
* #3529
* (this) #3534
* #3536
* #3511
Add an action to retrieve the logs from the last build (or the current build if a build is in progress).
Also, improve the build actions logic.
/deploy #notest renku=build/session-env-builders renku-data-services=kpack-resources renku-notebooks=leafty/shipwright-buildrun-cache extra-values=dataService.imageBuilders.enabled=true,dataService.imageBuilders.pushSecretName=flora-docker-secret,dataService.imageBuilders.buildRunRetentionAfterFailedSeconds=86400,dataService.imageBuilders.outputImagePrefix=harbor.dev.renku.ch/flora-dev/
=> feat: show last build's logs

client/src/features/sessionsV2/SessionView/EnvironmentCard.tsx, client/src/features/sessionsV2/SessionsV2.tsx, client/src/features/sessionsV2/api/sessionLaunchersV2.api.ts, client/src/features/sessionsV2/components/SessionForm/BuilderEnvironmentFields.tsx, client/src/features/sessionsV2/components/SessionForm/BuilderFrontendSelector.tsx, client/src/features/sessionsV2/components/SessionForm/BuilderSelectorCommon.tsx, client/src/features/sessionsV2/components/SessionForm/BuilderTypeSelector.tsx, client/src/features/sessionsV2/components/SessionForm/EnvironmentKindField.tsx, client/src/features/sessionsV2/session.constants.ts, client/src/features/sessionsV2/session.constants.tsx, client/src/features/sessionsV2/sessionsV2.types.ts
PR stack:
* #3529
* #3534
* (this) #3536
* #3511
New UI:
/deploy #notest renku=build/session-env-builders renku-data-services=kpack-resources renku-notebooks=leafty/shipwright-buildrun-cache extra-values=dataService.imageBuilders.enabled=true,dataService.imageBuilders.pushSecretName=flora-docker-secret,dataService.imageBuilders.buildRunRetentionAfterFailedSeconds=86400,dataService.imageBuilders.outputImagePrefix=harbor.dev.renku.ch/flora-dev/
=> refine: improve the selector fields for repo-based environments

client/src/features/sessionsV2/SessionView/EnvironmentCard.tsx, client/src/features/sessionsV2/api/sessionLaunchersV2.generated-api.ts, client/src/features/sessionsV2/api/sessionLaunchersV2.openapi.json, client/src/features/sessionsV2/components/SessionForm/BuilderTypeSelector.tsx, client/src/features/sessionsV2/session.constants.tsx, client/src/features/sessionsV2/session.utils.ts
Improve the user experience around image builds when the image build process fails.
Example can be found here: https://renku-ci-ui-3543.dev.renku.ch/v2/projects/flora.thiebaut/flora-test
/deploy #notest renku=build/session-env-builders renku-data-services=pitch/custom-environment-build renku-notebooks=leafty/shipwright-buildrun-cache extra-values=dataService.imageBuilders.enabled=true,dataService.imageBuilders.pushSecretName=flora-docker-secret,dataService.imageBuilders.buildRunTimeoutSeconds=30,dataService.imageBuilders.buildRunRetentionAfterFailedSeconds=86400,dataService.imageBuilders.nodeSelector.renku\.io/node-purpose=image-build,dataService.imageBuilders.tolerations[0].key=renku.io/dedicated,dataService.imageBuilders.tolerations[0].operator=Equal,dataService.imageBuilders.tolerations …
=> refine: improve build error reporting

client/src/features/dashboardV2/DashboardV2Sessions.tsx
Closes #3569.
/deploy renku=build/session-env-builders
=> fix: do not set z-index for session actions

.github/workflows/acceptance-tests.yml, .github/workflows/test-and-ci.yml
We can now disable running legacy acceptance tests by default
/deploy
=> ci: do not run legacy tests by default

client/src/components/modal/ModalHeader.tsx, client/src/features/ProjectPageV2/ProjectPageContent/DataConnectors/ProjectConnectDataConnectorsModal.tsx, client/src/features/ProjectPageV2/ProjectPageContent/Documentation/Documentation.tsx, client/src/features/groupsV2/new/GroupNew.tsx, client/src/features/projectsV2/new/ProjectV2New.tsx
There are multiple ways these problems can be fixed, but in discussion with @leafty, it seems that the best solution is just to ensure that the modal dialog titles are short, adding further information in their own header blocks.
Fix #3410
/deploy
=> refactor: improve modal headers, fix close button position

client/src/features/ProjectPageV2/ProjectPageContent/DataConnectors/ProjectDataConnectorsBox.tsx
A space was missing in this sentence
Fixed in this PR
/deploy
=> fix: add missing space in the hidden data connectors popover

client/package-lock.json, client/package.json, client/src/components/Pagination.tsx, client/src/features/dataConnectorsV2/components/DataConnectorsBox.tsx, client/src/features/projectsV2/list/ProjectV2ListDisplay.tsx
This PR removes the dependency `react-js-pagination` using a standard solution based on Bootstrap 5.
This will fix the following 2 high-level vulnerabilities:
https://github.com/SwissDataScienceCenter/renku-ui/security/dependabot/24
https://github.com/SwissDataScienceCenter/renku-ui/security/dependabot/20
/deploy
=> Use a standard component for pagination

client/package-lock.json, client/package.json, client/scripts/update_api_spec.js, client/src/features/usersV2/api/users.openapi.json
Add a new script to automatically update `src/features/usersV2/api/users.openapi.json`. More spec files will be supported soon.
Run:
```bash
$ npm run update-api:users
```
=> build: add script to automate API spec retrieval

client/run-telepresence.sh
Sometimes the config file isn't created correctly because the `$OSTYPE` is set to "linux"
=> fix: create config.json correctly in linux

client/src/features/sessionsV2/SessionsV2.tsx
This fixes the badge showing the number of sessions in the project page.
/deploy
=> fix: show badge for session numbers in project

client/src/features/sessionsV2/SessionStartPage.tsx, client/src/features/sessionsV2/api/sessionsV2.generated-api.ts, client/src/features/sessionsV2/api/sessionsV2.openapi.json
This PR allows overriding environment variables by passing in values as query parameters. To test, create a project and add a session launcher. In the sidebar for the launcher, you can find and copy the session start link.
1. No variable defined
If an override is provided for a variable that is not defined in the launcher, the session will not start. Take the session start link and add a query parameter (e..g., `?FOO=value`). When following this link you should get an error message:
2. Variable defined
Add an environment variable to the session launcher. Then provide a different value as a query parameter to the session start link. In this case, the session should start, and the environment should have the variable defined and set to the value provided in the query parameter.
/deploy …
=> Pass through env variables specified in query parameters

client/Dockerfile, client/src/features/sessionsV2/components/SessionForm/BuilderSelectorCommon.tsx, client/src/features/sessionsV2/session.constants.tsx
There is a working CI deployment over at https://github.com/SwissDataScienceCenter/renku-data-services/pull/801 which is using this PR for the ui.
=> feat: add jupyterlab option for builders

client/src/features/dataConnectorsV2/components/DataConnectorView.tsx, client/src/features/dataConnectorsV2/components/dataConnector.utils.ts
Use a standard DOI reference to avoid showing specific flavours used once the global connector was created the first time.
See: https://github.com/SwissDataScienceCenter/renku/issues/4025.
/deploy renku=leafty/update-search-tests
=> fix: parse doi reference on the data connector view

client/src/features/dashboard/components/ProjectsDashboard.tsx, client/src/utils/constants/Docs.js
The "First time" message still points people to the legacy docs and tutorial. This redirects them to 2.0. 
The banner now looks like this: 
/deploy
=> chore: update first-time legacy message

.github/workflows/test-and-ci.yml
This PR implements building and publishing images for both amd64 and arm64 architecture.
This make renku-ui follow other packages such as renku-data-services that are available for both platforms.
=> feat: create images for both amd64 and arm64

client/src/features/sessionsV2/components/SessionModals/ModifyResourcesLauncher.tsx
This PR prevents the overflow problem described here https://github.com/SwissDataScienceCenter/renku-ui/discussions/3754
Mind that switching to a non-scrolling modal maintains consistency with the custom resource class selection modal, which can be triggered when launching a new session.
/deploy renku=release-2.5.0
=> fix: prevent overflow problems with setting default resource class

client/src/features/session/components/SessionButton.tsx
As pointed out here https://github.com/SwissDataScienceCenter/renku/pull/4119#pullrequestreview-3111672244 , the "Start with options" button on the dropdown button reads white on white when Legacy sessions are disabled.
This PR fixes it
/deploy
=> fix: prevent white-on-white text on disabled session button menu

client/src/not-found/NotFound.tsx, client/src/root.tsx, client/src/routes/catchall.tsx, tests/cypress/e2e/home.spec.ts, tests/cypress/e2e/routing.spec.ts
=> Return 404 for not-found routes

client/src/components/keywords/KeywordBadge.tsx
This prevents longer keywords with wraps to align on the middle as in the following example
/deploy
=> fix: align longer keywords on the left

client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/CodeRepositoryDisplay.tsx, client/src/features/admin/AddConnectedServiceButton.tsx, client/src/features/admin/ConnectedServiceFormContent.tsx, client/src/features/admin/ConnectedServicesSection.tsx, client/src/features/admin/UpdateConnectedServiceButton.tsx, client/src/features/connectedServices/ConnectedServicesPage.tsx, client/src/features/connectedServices/api/connectedServices.api.ts, client/src/features/connectedServices/api/connectedServices.openapi.json, client/src/features/connectedServices/connectedServices.constants.ts, client/src/features/sessionsV2/DataConnectorSecretsModal.tsx, client/src/features/sessionsV2/SessionImageModal.tsx, client/src/features/sessionsV2/SessionList/SessionLauncherCard.tsx, client/src/features/sessionsV2/SessionSecretsModal.tsx, client/src/features/sessionsV2/SessionStartPage.tsx, client/src/features/sessionsV2/SessionView/EnvironmentCard.tsx, client/src/features/sessionsV2/StartSessionButton.tsx, client/src/features/sessionsV2/api/sessionsV2.generated-api.ts, client/src/features/sessionsV2/api/sessionsV2.openapi.json, client/src/features/sessionsV2/components/SessionForm/CustomEnvironmentFields.tsx, client/src/features/sessionsV2/components/SessionForm/EnvironmentField.tsx, client/src/features/sessionsV2/components/SessionLauncherButtons.tsx, client/src/features/sessionsV2/components/SessionModals/NewSessionLauncherModal.tsx, client/src/features/sessionsV2/components/SessionStatus/SessionImageBadge.tsx, client/src/features/sessionsV2/startSessionOptionsV2.slice.ts, client/src/features/sessionsV2/startSessionOptionsV2.types.ts, client/src/features/sessionsV2/useSessionLaunchState.hook.ts
This PR adds support for private images. Changes touch the following areas:
* Project page: check the image status for launchers using external images and let users go to the integration page to log in
* Session page: give feedback about image (un)availability when necessary
* Integrations page: highlight when redirected and disconnect button
* Admin page: minor adjustments
A few follow-ups are planned and will be part of a short pitch in the write:
* Add better feedback while creating the launcher and pasting the image URL (require some design)
* Show the required integrations in a modal or integrate in the current panel instead of redirecting (require update on connection APIs)
* Improve how we check code repos
Reference: https://www.notion.so/renku/Support-Private-images-from-external-r …
=>  feat: support private images and connected registries
